# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

import textwrap

from odoo import fields, models

__NAMESPACE__ = "http://www.reinf.esocial.gov.br/schemas/evtTabProcesso/v2_01_02"


class Reinf(models.AbstractModel):
    """Escrituracao Fiscal Digital de Retencoes e Outras Informacoes Fiscais
    (EFD-Reinf)"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.reinf"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf"

    reinf21_evtTabProcesso = fields.Many2one(
        comodel_name="reinf.21.evttabprocesso",
        string="Evento tabela de processos",
        xsd_required=True,
    )


class EvtTabProcesso(models.AbstractModel):
    "Evento tabela de processos"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttabprocesso"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso"

    reinf21_ideEvento = fields.Many2one(
        comodel_name="reinf.21.evttabprocesso_ideevento",
        string="Informacoes de identificacao do evento",
        xsd_required=True,
    )

    reinf21_ideContri = fields.Many2one(
        comodel_name="reinf.21.evttabprocesso_idecontri",
        string="Informacoes de identificacao",
        xsd_required=True,
        help="Informacoes de identificacao do contribuinte",
    )

    reinf21_infoProcesso = fields.Many2one(
        comodel_name="reinf.21.infoprocesso",
        string="Informacoes do processo",
        xsd_required=True,
    )

    reinf21_id = fields.Char(string="Identificacao unica do evento", xsd_required=True)


class EvtTabProcessoIdeEvento(models.AbstractModel):
    "Informacoes de identificacao do evento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttabprocesso_ideevento"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.IdeEvento"

    reinf21_tpAmb = fields.Char(string="Tipo de ambiente", xsd_required=True)

    reinf21_procEmi = fields.Char(
        string="Processo de emissao do evento", xsd_required=True
    )

    reinf21_verProc = fields.Char(
        string="Versao do processo de emissao do evento", xsd_required=True
    )


class EvtTabProcessoIdeContri(models.AbstractModel):
    "Informacoes de identificacao do contribuinte"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttabprocesso_idecontri"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.IdeContri"

    reinf21_tpInsc = fields.Char(string="Tipo de Inscricao", xsd_required=True)

    reinf21_nrInsc = fields.Char(string="Numero de Inscricao", xsd_required=True)


class InfoProcesso(models.AbstractModel):
    "Informacoes do processo"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infoprocesso"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.InfoProcesso"

    reinf21_inclusao = fields.Many2one(
        comodel_name="reinf.21.evttabprocesso_inclusao",
        string="Inclusao de novas informacoes",
        choice="infoprocesso",
        xsd_choice_required=True,
    )

    reinf21_alteracao = fields.Many2one(
        comodel_name="reinf.21.evttabprocesso_alteracao",
        string="Alteracao de informacoes",
        choice="infoprocesso",
        xsd_choice_required=True,
    )

    reinf21_exclusao = fields.Many2one(
        comodel_name="reinf.21.evttabprocesso_exclusao",
        string="Exclusao de informacoes",
        choice="infoprocesso",
        xsd_choice_required=True,
    )


class EvtTabProcessoInclusao(models.AbstractModel):
    "Inclusao de novas informacoes"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttabprocesso_inclusao"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.InfoProcesso.Inclusao"

    reinf21_ideProcesso = fields.Many2one(
        comodel_name="reinf.21.inclusao_ideprocesso",
        string="Informacoes de identificacao do processo",
        xsd_required=True,
    )


class InclusaoIdeProcesso(models.AbstractModel):
    "Informacoes de identificacao do processo"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.inclusao_ideprocesso"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.InfoProcesso.Inclusao.IdeProcesso"

    reinf21_tpProc = fields.Char(string="Tipo de Processo", xsd_required=True)

    reinf21_nrProc = fields.Char(string="Numero do Processo", xsd_required=True)

    reinf21_iniValid = fields.Char(
        string="Inicio da validade (AAAA-MM)", xsd_required=True
    )

    reinf21_fimValid = fields.Char(
        string="Periodo final da validade",
        help="Periodo final da validade, no formato (AAAA-MM)",
    )

    reinf21_indAutoria = fields.Char(string="Autoria da Acao Judicial")

    reinf21_infoSusp = fields.One2many(
        "reinf.21.inclusao_infosusp",
        "reinf21_infoSusp_ideProcesso_id",
        string="Informacoes de suspensao de exibilidade",
        help="Informacoes de suspensao de exibilidade de tributos",
    )

    reinf21_dadosProcJud = fields.Many2one(
        comodel_name="reinf.21.inclusao_dadosprocjud",
        string="Informacoes Complementares",
        help="Informacoes Complementares do Processo Judicial",
    )


class InclusaoInfoSusp(models.AbstractModel):
    "Informacoes de suspensao de exibilidade de tributos"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.inclusao_infosusp"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.InfoProcesso.Inclusao.IdeProcesso.InfoSusp"

    reinf21_infoSusp_ideProcesso_id = fields.Many2one(
        comodel_name="reinf.21.inclusao_ideprocesso",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_codSusp = fields.Char(string="Codigo do indicativo da suspensao")

    reinf21_indSusp = fields.Char(
        string="Indicativo de suspensao da exigibilidade", xsd_required=True
    )

    reinf21_dtDecisao = fields.Char(
        string="Data da decisao",
        xsd_required=True,
        help="Data da decisao, sentenca ou despacho",
    )

    reinf21_indDeposito = fields.Char(
        string="Deposito do Montante Integral", xsd_required=True
    )


class InclusaoDadosProcJud(models.AbstractModel):
    "Informacoes Complementares do Processo Judicial"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.inclusao_dadosprocjud"
    _inherit = "spec.mixin.reinf"
    _binding_type = (
        "Reinf.EvtTabProcesso.InfoProcesso.Inclusao.IdeProcesso.DadosProcJud"
    )

    reinf21_ufVara = fields.Char(
        string="Identificacao da UF da Secao Judiciaria", xsd_required=True
    )

    reinf21_codMunic = fields.Char(string="Codigo do Municipio", xsd_required=True)

    reinf21_idVara = fields.Char(
        string="Codigo de Identificacao da Vara", xsd_required=True
    )


class EvtTabProcessoAlteracao(models.AbstractModel):
    "Alteracao de informacoes"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttabprocesso_alteracao"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.InfoProcesso.Alteracao"

    reinf21_ideProcesso = fields.Many2one(
        comodel_name="reinf.21.alteracao_ideprocesso",
        string="Informacoes de identificacao do processo",
        xsd_required=True,
    )

    reinf21_novaValidade = fields.Many2one(
        comodel_name="reinf.21.evttabprocesso_novavalidade",
        string="Novo periodo de validade das informacoes",
        help=("Novo periodo de validade das informacoes que estao sendo alteradas"),
    )


class AlteracaoIdeProcesso(models.AbstractModel):
    "Informacoes de identificacao do processo"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.alteracao_ideprocesso"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.InfoProcesso.Alteracao.IdeProcesso"

    reinf21_tpProc = fields.Char(string="Tipo de Processo", xsd_required=True)

    reinf21_nrProc = fields.Char(string="Numero do Processo", xsd_required=True)

    reinf21_iniValid = fields.Char(
        string="Inicio da validade (AAAA-MM)", xsd_required=True
    )

    reinf21_fimValid = fields.Char(
        string="Periodo final da validade",
        help="Periodo final da validade, no formato (AAAA-MM)",
    )

    reinf21_indAutoria = fields.Char(string="Autoria da Acao Judicial")

    reinf21_infoSusp = fields.One2many(
        "reinf.21.alteracao_infosusp",
        "reinf21_infoSusp_ideProcesso_id",
        string="Informacoes de suspensao",
        help="Informacoes de suspensao de exigibilidade de tributos",
    )

    reinf21_dadosProcJud = fields.Many2one(
        comodel_name="reinf.21.alteracao_dadosprocjud",
        string="Informacoes complementares",
        help="Informacoes complementares do processo judicial",
    )


class AlteracaoInfoSusp(models.AbstractModel):
    "Informacoes de suspensao de exibilidade de tributos"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.alteracao_infosusp"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.InfoProcesso.Alteracao.IdeProcesso.InfoSusp"

    reinf21_infoSusp_ideProcesso_id = fields.Many2one(
        comodel_name="reinf.21.alteracao_ideprocesso",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_codSusp = fields.Char(string="Codigo do indicativo da suspensao")

    reinf21_indSusp = fields.Char(
        string="Indicativo de suspensao da exigibilidade", xsd_required=True
    )

    reinf21_dtDecisao = fields.Char(
        string="Data da decisao",
        xsd_required=True,
        help="Data da decisao, sentenca ou despacho",
    )

    reinf21_indDeposito = fields.Char(
        string="Deposito do Montante Integral", xsd_required=True
    )


class AlteracaoDadosProcJud(models.AbstractModel):
    "Informacoes Complementares do Processo Judicial"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.alteracao_dadosprocjud"
    _inherit = "spec.mixin.reinf"
    _binding_type = (
        "Reinf.EvtTabProcesso.InfoProcesso.Alteracao.IdeProcesso.DadosProcJud"
    )

    reinf21_ufVara = fields.Char(
        string="Identificacao da UF da Secao Judiciaria", xsd_required=True
    )

    reinf21_codMunic = fields.Char(string="Codigo do Municipio", xsd_required=True)

    reinf21_idVara = fields.Char(
        string="Codigo de Identificacao da Vara", xsd_required=True
    )


class EvtTabProcessoNovaValidade(models.AbstractModel):
    "Novo periodo de validade das informacoes que estao sendo alteradas"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttabprocesso_novavalidade"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.InfoProcesso.Alteracao.NovaValidade"

    reinf21_iniValid = fields.Char(
        string="Inicio da validade (AAAA-MM)", xsd_required=True
    )

    reinf21_fimValid = fields.Char(
        string="Periodo final da validade",
        help="Periodo final da validade, no formato (AAAA-MM)",
    )


class EvtTabProcessoExclusao(models.AbstractModel):
    "Exclusao de informacoes"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttabprocesso_exclusao"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.InfoProcesso.Exclusao"

    reinf21_ideProcesso = fields.Many2one(
        comodel_name="reinf.21.exclusao_ideprocesso",
        string="Informacoes de identificacao do processo",
        xsd_required=True,
    )


class ExclusaoIdeProcesso(models.AbstractModel):
    "Informacoes de identificacao do processo"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.exclusao_ideprocesso"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTabProcesso.InfoProcesso.Exclusao.IdeProcesso"

    reinf21_tpProc = fields.Char(string="Tipo de Processo", xsd_required=True)

    reinf21_nrProc = fields.Char(string="Numero do Processo", xsd_required=True)

    reinf21_iniValid = fields.Char(
        string="Inicio da validade (AAAA-MM)", xsd_required=True
    )

    reinf21_fimValid = fields.Char(
        string="Periodo final da validade",
        help="Periodo final da validade, no formato (AAAA-MM)",
    )
