# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

import textwrap

from odoo import fields, models

__NAMESPACE__ = "http://www.reinf.esocial.gov.br/schemas/evtTomadorServicos/v2_01_02"


class Reinf(models.AbstractModel):
    """Escrituracao Fiscal Digital de Retencoes e Outras Informacoes Fiscais
    (EFD-Reinf)"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.reinf"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf"

    reinf21_evtServTom = fields.Many2one(
        comodel_name="reinf.21.evtservtom",
        string="Evento servicos tomados",
        xsd_required=True,
    )


class EvtServTom(models.AbstractModel):
    "Evento servicos tomados"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtservtom"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtServTom"

    reinf21_ideEvento = fields.Many2one(
        comodel_name="reinf.21.evtservtom_ideevento",
        string="Informacoes de identificacao do evento",
        xsd_required=True,
    )

    reinf21_ideContri = fields.Many2one(
        comodel_name="reinf.21.evtservtom_idecontri",
        string="Informacoes de identificacao",
        xsd_required=True,
        help="Informacoes de identificacao do contribuinte",
    )

    reinf21_infoServTom = fields.Many2one(
        comodel_name="reinf.21.infoservtom",
        string="Servicos tomados com cessao de mao",
        xsd_required=True,
        help="Servicos tomados com cessao de mao de obra ou empreitada",
    )

    reinf21_id = fields.Char(string="Identificacao unica do evento", xsd_required=True)


class EvtServTomIdeEvento(models.AbstractModel):
    "Informacoes de identificacao do evento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtservtom_ideevento"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtServTom.IdeEvento"

    reinf21_indRetif = fields.Char(
        string="Indicativo de Retificacao", xsd_required=True
    )

    reinf21_nrRecibo = fields.Char(string="Recibo arquivo a ser retificado")

    reinf21_perApur = fields.Char(string="Periodo de apuracao", xsd_required=True)

    reinf21_tpAmb = fields.Char(string="Tipo de ambiente", xsd_required=True)

    reinf21_procEmi = fields.Char(
        string="Processo de emissao do evento", xsd_required=True
    )

    reinf21_verProc = fields.Char(
        string="Versao do processo de emissao do evento", xsd_required=True
    )


class EvtServTomIdeContri(models.AbstractModel):
    "Informacoes de identificacao do contribuinte"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtservtom_idecontri"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtServTom.IdeContri"

    reinf21_tpInsc = fields.Char(string="Tipo de Inscricao", xsd_required=True)

    reinf21_nrInsc = fields.Char(string="Numero de Inscricao", xsd_required=True)


class InfoServTom(models.AbstractModel):
    "Servicos tomados com cessao de mao de obra ou empreitada"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infoservtom"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtServTom.InfoServTom"

    reinf21_ideEstabObra = fields.Many2one(
        comodel_name="reinf.21.ideestabobra",
        string="Identificacao",
        xsd_required=True,
        help=("Identificacao do estabelecimento/obra contratante dos servicos"),
    )


class IdeEstabObra(models.AbstractModel):
    "Identificacao do estabelecimento/obra contratante dos servicos"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.ideestabobra"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtServTom.InfoServTom.IdeEstabObra"

    reinf21_tpInscEstab = fields.Char(
        string="Tipo de inscricao do estabelecimento", xsd_required=True
    )

    reinf21_nrInscEstab = fields.Char(
        string="Numero de inscricao do estabelecimento", xsd_required=True
    )

    reinf21_indObra = fields.Char(
        string="Indicativo de prestacao de servicos",
        xsd_required=True,
        help=("Indicativo de prestacao de servicos em obra de construcao civil"),
    )

    reinf21_idePrestServ = fields.Many2one(
        comodel_name="reinf.21.ideprestserv",
        string="Identificacao do prestador",
        xsd_required=True,
        help=(
            "Identificacao do prestador de servicos mediante cessao de mao de "
            "obra ou empreitada"
        ),
    )


class IdePrestServ(models.AbstractModel):
    """Identificacao do prestador de servicos mediante cessao de mao de obra ou
    empreitada"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.ideprestserv"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtServTom.InfoServTom.IdeEstabObra.IdePrestServ"

    reinf21_cnpjPrestador = fields.Char(
        string="CNPJ do Prestador de Servicos", xsd_required=True
    )

    reinf21_vlrTotalBruto = fields.Char(string="Valor Total bruto", xsd_required=True)

    reinf21_vlrTotalBaseRet = fields.Char(
        string="Base de calculo da retencao",
        xsd_required=True,
        help="Base de calculo da retencao da contribuicao previdenciaria.",
    )

    reinf21_vlrTotalRetPrinc = fields.Char(
        string="Valor da retencao principal",
        xsd_required=True,
        help="Valor da retencao principal das notas fiscais de servico",
    )

    reinf21_vlrTotalRetAdic = fields.Char(
        string="Soma do valor do adicional de retencao",
        help="Soma do valor do adicional de retencao das notas fiscais",
    )

    reinf21_vlrTotalNRetPrinc = fields.Char(
        string="vlrTotalNRetPrinc",
        help="Valor da retencao principal que deixou de ser efetuada",
    )

    reinf21_vlrTotalNRetAdic = fields.Char(
        string="Valor da retencao adicional",
        help="Valor da retencao adicional que deixou de ser efetuada",
    )

    reinf21_indCPRB = fields.Char(
        string="Indicativo se o prestador e contribuinte",
        xsd_required=True,
        help="Indicativo se o prestador e contribuinte da CPRB",
    )

    reinf21_nfs = fields.One2many(
        "reinf.21.evtservtom_nfs", "reinf21_nfs_idePrestServ_id", string="Notas fiscais"
    )

    reinf21_infoProcRetPr = fields.One2many(
        "reinf.21.evtservtom_infoprocretpr",
        "reinf21_infoProcRetPr_idePrestServ_id",
        string="Informacoes de processo",
    )

    reinf21_infoProcRetAd = fields.One2many(
        "reinf.21.evtservtom_infoprocretad",
        "reinf21_infoProcRetAd_idePrestServ_id",
        string="Informacoes de processo (infoProcRetAd)",
    )


class EvtServTomNfs(models.AbstractModel):
    "Notas fiscais"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtservtom_nfs"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtServTom.InfoServTom.IdeEstabObra.IdePrestServ.Nfs"

    reinf21_nfs_idePrestServ_id = fields.Many2one(
        comodel_name="reinf.21.ideprestserv",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_serie = fields.Char(string="Serie da Nota Fiscal/Fatura", xsd_required=True)

    reinf21_numDocto = fields.Char(
        string="Numero da Nota Fiscal/Fatura",
        xsd_required=True,
        help=("Numero da Nota Fiscal/Fatura ou outro documento fiscal valido"),
    )

    reinf21_dtEmissaoNF = fields.Char(
        string="Data de emissao da nota fiscal/fatura", xsd_required=True
    )

    reinf21_vlrBruto = fields.Char(string="Valor bruto", xsd_required=True)

    reinf21_obs = fields.Char(string="Observacao")

    reinf21_infoTpServ = fields.One2many(
        "reinf.21.evtservtom_infotpserv",
        "reinf21_infoTpServ_nfs_id",
        string="Informacoes sobre os tipos",
        help=("Informacoes sobre os tipos de servicos constantes da nota fiscal"),
    )


class EvtServTomInfoTpServ(models.AbstractModel):
    "Informacoes sobre os tipos de servicos constantes da nota fiscal"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtservtom_infotpserv"
    _inherit = "spec.mixin.reinf"
    _binding_type = (
        "Reinf.EvtServTom.InfoServTom.IdeEstabObra.IdePrestServ.Nfs.InfoTpServ"
    )

    reinf21_infoTpServ_nfs_id = fields.Many2one(
        comodel_name="reinf.21.evtservtom_nfs",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_tpServico = fields.Char(string="Tipo de servico", xsd_required=True)

    reinf21_vlrBaseRet = fields.Char(
        string="Valor da base de calculo da retencao",
        xsd_required=True,
        help=("Valor da base de calculo da retencao da contribuicao previdenciaria."),
    )

    reinf21_vlrRetencao = fields.Char(string="Valor da retencao", xsd_required=True)

    reinf21_vlrRetSub = fields.Char(string="Valor da retencao da subcontratacao")

    reinf21_vlrNRetPrinc = fields.Char(
        string="Valor da retencao principal",
        help=(
            "Valor da retencao principal que deixou de ser efetuada pelo contratante..."
        ),
    )

    reinf21_vlrServicos15 = fields.Char(
        string="Valor dos servicos prestados",
        help=(
            "Valor dos servicos prestados por segurados em condicoes especiais"
            " - aposentadoria especial 15 anos"
        ),
    )

    reinf21_vlrServicos20 = fields.Char(
        string="vlrServicos20",
        help=(
            "Valor dos servicos prestados por segurados em condicoes especiais"
            " - aposentadoria especial 20 anos"
        ),
    )

    reinf21_vlrServicos25 = fields.Char(
        string="vlrServicos25",
        help=(
            "Valor dos servicos prestados por segurados em condicoes especiais"
            " - aposentadoria especial 25 anos"
        ),
    )

    reinf21_vlrAdicional = fields.Char(
        string="Adicional de retencao na NF relativo",
        help=(
            "Adicional de retencao na NF relativo a servicos prestados sob "
            "condicoes especiais que ensejem aposentadoria especial aos "
            "trabalhadores"
        ),
    )

    reinf21_vlrNRetAdic = fields.Char(
        string="Valor da retencao adicional",
        help="Valor da retencao adicional que deixou de ser efetuada",
    )


class EvtServTomInfoProcRetPr(models.AbstractModel):
    "Informacoes de processo"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtservtom_infoprocretpr"
    _inherit = "spec.mixin.reinf"
    _binding_type = (
        "Reinf.EvtServTom.InfoServTom.IdeEstabObra.IdePrestServ.InfoProcRetPr"
    )

    reinf21_infoProcRetPr_idePrestServ_id = fields.Many2one(
        comodel_name="reinf.21.ideprestserv",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_tpProcRetPrinc = fields.Char(string="Tipo de Processo", xsd_required=True)

    reinf21_nrProcRetPrinc = fields.Char(string="Numero do Processo", xsd_required=True)

    reinf21_codSuspPrinc = fields.Char(string="Codigo do indicativo da suspensao")

    reinf21_valorPrinc = fields.Char(
        string="Valor da retencao nao efetuada",
        xsd_required=True,
        help=(
            "Valor da retencao nao efetuada ou depositada em juizo em "
            "decorrencia da decisao judicial/administrativa"
        ),
    )


class EvtServTomInfoProcRetAd(models.AbstractModel):
    "Informacoes de processo"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtservtom_infoprocretad"
    _inherit = "spec.mixin.reinf"
    _binding_type = (
        "Reinf.EvtServTom.InfoServTom.IdeEstabObra.IdePrestServ.InfoProcRetAd"
    )

    reinf21_infoProcRetAd_idePrestServ_id = fields.Many2one(
        comodel_name="reinf.21.ideprestserv",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_tpProcRetAdic = fields.Char(string="Tipo de Processo", xsd_required=True)

    reinf21_nrProcRetAdic = fields.Char(string="Numero do Processo", xsd_required=True)

    reinf21_codSuspAdic = fields.Char(string="Codigo do Indicativo da Suspensao")

    reinf21_valorAdic = fields.Char(
        string="Valor da retencao nao efetuada",
        xsd_required=True,
        help=(
            "Valor da retencao nao efetuada ou depositada em juizo em "
            "decorrencia da decisao judicial/administrativa"
        ),
    )
