# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

import textwrap

from odoo import fields, models

__NAMESPACE__ = (
    "http://www.reinf.esocial.gov.br/schemas/evt4020PagtoBeneficiarioPJ/v2_01_02"
)


class Reinf(models.AbstractModel):
    """Escrituracao Fiscal Digital de Retencoes e Outras Informacoes Fiscais
    (EFD-Reinf)"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.reinf"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf"

    reinf21_evtRetPJ = fields.Many2one(
        comodel_name="reinf.21.evtretpj",
        string="Evento retencoes na fonte PJ",
        xsd_required=True,
    )


class EvtRetPj(models.AbstractModel):
    "Evento retencoes na fonte PJ"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj"

    reinf21_ideEvento = fields.Many2one(
        comodel_name="reinf.21.evtretpj_ideevento",
        string="Informacoes de identificacao do evento",
        xsd_required=True,
    )

    reinf21_ideContri = fields.Many2one(
        comodel_name="reinf.21.evtretpj_idecontri",
        string="Informacoes de identificacao",
        xsd_required=True,
        help="Informacoes de identificacao do contribuinte",
    )

    reinf21_ideEstab = fields.Many2one(
        comodel_name="reinf.21.evtretpj_ideestab",
        string="Informacoes de identificacao (ideEstab)",
        xsd_required=True,
        help="Informacoes de identificacao do estabelecimento",
    )

    reinf21_id = fields.Char(string="Identificacao unica do evento", xsd_required=True)


class EvtRetPjIdeEvento(models.AbstractModel):
    "Informacoes de identificacao do evento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_ideevento"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj.IdeEvento"

    reinf21_indRetif = fields.Char(
        string="Indicativo de Retificacao", xsd_required=True
    )

    reinf21_nrRecibo = fields.Char(string="Recibo arquivo a ser retificado")

    reinf21_perApur = fields.Char(string="Periodo de apuracao", xsd_required=True)

    reinf21_tpAmb = fields.Char(string="Tipo de ambiente", xsd_required=True)

    reinf21_procEmi = fields.Char(
        string="Processo de emissao do evento", xsd_required=True
    )

    reinf21_verProc = fields.Char(
        string="Versao do processo de emissao do evento", xsd_required=True
    )


class EvtRetPjIdeContri(models.AbstractModel):
    "Informacoes de identificacao do contribuinte"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_idecontri"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj.IdeContri"

    reinf21_tpInsc = fields.Char(string="Tipo de Inscricao", xsd_required=True)

    reinf21_nrInsc = fields.Char(string="Numero de Inscricao", xsd_required=True)

    reinf21_infoComplContri = fields.Many2one(
        comodel_name="reinf.21.evtretpj_infocomplcontri",
        string="Informacoes complementares",
        help="Informacoes complementares do contribuinte",
    )


class EvtRetPjInfoComplContri(models.AbstractModel):
    "Informacoes complementares do contribuinte"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_infocomplcontri"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj.IdeContri.InfoComplContri"

    reinf21_natJur = fields.Char(
        string="Natureza juridica do declarante", xsd_required=True
    )


class EvtRetPjIdeEstab(models.AbstractModel):
    "Informacoes de identificacao do estabelecimento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_ideestab"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj.IdeEstab"

    reinf21_tpInscEstab = fields.Char(
        string="Tipo de inscricao do estabelecimento", xsd_required=True
    )

    reinf21_nrInscEstab = fields.Char(
        string="Numero de inscricao do estabelecimento", xsd_required=True
    )

    reinf21_ideBenef = fields.Many2one(
        comodel_name="reinf.21.evtretpj_idebenef",
        string="Identificacao do beneficiario",
        xsd_required=True,
        help="Identificacao do beneficiario do rendimento",
    )


class EvtRetPjIdeBenef(models.AbstractModel):
    "Identificacao do beneficiario do rendimento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_idebenef"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj.IdeEstab.IdeBenef"

    reinf21_cnpjBenef = fields.Char(string="CNPJ do beneficiario")

    reinf21_nmBenef = fields.Char(string="Nome do beneficiario")

    reinf21_isenImun = fields.Char(string="Informacoes sobre isencao e imunidade")

    reinf21_ideEvtAdic = fields.Char(
        string="Identificador de evento adicional",
        help=(
            "Identificador de evento adicional por beneficiario, a criterio do"
            " declarante."
        ),
    )

    reinf21_idePgto = fields.One2many(
        "reinf.21.evtretpj_idepgto",
        "reinf21_idePgto_ideBenef_id",
        string="Identificacao do rendimento",
    )


class EvtRetPjIdePgto(models.AbstractModel):
    "Identificacao do rendimento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_idepgto"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto"

    reinf21_idePgto_ideBenef_id = fields.Many2one(
        comodel_name="reinf.21.evtretpj_idebenef",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_natRend = fields.Char(string="Natureza do Rendimento", xsd_required=True)

    reinf21_observ = fields.Char(string="Observacoes")

    reinf21_infoPgto = fields.One2many(
        "reinf.21.evtretpj_infopgto",
        "reinf21_infoPgto_idePgto_id",
        string="Informacoes relativas ao pagamento",
    )


class EvtRetPjInfoPgto(models.AbstractModel):
    "Informacoes relativas ao pagamento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_infopgto"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto"

    reinf21_infoPgto_idePgto_id = fields.Many2one(
        comodel_name="reinf.21.evtretpj_idepgto",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_dtFG = fields.Char(string="Data do pagamento", xsd_required=True)

    reinf21_vlrBruto = fields.Char(string="Valor bruto")

    reinf21_indFciScp = fields.Char(string="Indicativo de FCI ou SCP")

    reinf21_nrInscFciScp = fields.Char(string="CNPJ do FCI ou SCP")

    reinf21_percSCP = fields.Char(string="Percentual de participacao na SCP")

    reinf21_indJud = fields.Char(
        string="Indicativo de rendimento oriundo",
        help="Indicativo de rendimento oriundo de decisao judicial",
    )

    reinf21_paisResidExt = fields.Char(string="Codigo do Pais")

    reinf21_dtEscrCont = fields.Char(
        string="Data da escrituracao contabil referente",
        help=(
            "Data da escrituracao contabil referente ao IRRF dos juros sobre "
            "capital proprio informada no evento R-4040."
        ),
    )

    reinf21_observ = fields.Char(string="Observacoes")

    reinf21_retencoes = fields.Many2one(
        comodel_name="reinf.21.retencoes",
        string="Informacoes relativas a retencoes",
        help="Informacoes relativas a retencoes na fonte",
    )

    reinf21_infoProcRet = fields.One2many(
        "reinf.21.evtretpj_infoprocret",
        "reinf21_infoProcRet_infoPgto_id",
        string="Processos relacionados a nao retencao",
        help="Processos relacionados a nao retencao de tributos",
    )

    reinf21_infoProcJud = fields.Many2one(
        comodel_name="reinf.21.evtretpj_infoprocjud",
        string="Informacoes complementares relativas",
        help=(
            "Informacoes complementares relativas a rendimentos decorrentes de"
            " decisao judicial"
        ),
    )

    reinf21_infoPgtoExt = fields.Many2one(
        comodel_name="reinf.21.evtretpj_infopgtoext",
        string="infoPgtoExt",
        help=("Informacoes complementares relativas a pagamentos no Exterior"),
    )


class Retencoes(models.AbstractModel):
    "Informacoes relativas a retencoes na fonte"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.retencoes"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.Retencoes"

    reinf21_vlrBaseIR = fields.Char(string="Valor da base do IR")

    reinf21_vlrIR = fields.Char(string="Valor da retencao do IR")

    reinf21_vlrBaseAgreg = fields.Char(string="Valor da base retencoes agregadas")

    reinf21_vlrAgreg = fields.Char(
        string="Valor retencao de tributos",
        help="Valor retencao de tributos em valor agregado",
    )

    reinf21_vlrBaseCSLL = fields.Char(string="Valor da base da CSLL")

    reinf21_vlrCSLL = fields.Char(string="Retencao CSLL")

    reinf21_vlrBaseCofins = fields.Char(string="Valor da base Cofins")

    reinf21_vlrCofins = fields.Char(string="Valor Cofins")

    reinf21_vlrBasePP = fields.Char(string="Valor da base do PIS/PASEP")

    reinf21_vlrPP = fields.Char(string="Retencao do PIS/PASEP")


class EvtRetPjInfoProcRet(models.AbstractModel):
    "Processos relacionados a nao retencao de tributos"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_infoprocret"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoProcRet"

    reinf21_infoProcRet_infoPgto_id = fields.Many2one(
        comodel_name="reinf.21.evtretpj_infopgto",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_tpProcRet = fields.Char(string="Tipo de Processo", xsd_required=True)

    reinf21_nrProcRet = fields.Char(string="Numero do Processo", xsd_required=True)

    reinf21_codSusp = fields.Char(string="Codigo do indicativo da suspensao")

    reinf21_vlrBaseSuspIR = fields.Char(
        string="Valor da base do IR",
        help="Valor da base do IR com exigibilidade suspensa",
    )

    reinf21_vlrNIR = fields.Char(string="Valor nao retido de IR")

    reinf21_vlrDepIR = fields.Char(string="Valor do deposito judicial de IR")

    reinf21_vlrBaseSuspCSLL = fields.Char(string="Valor da base CSLL suspenso")

    reinf21_vlrNCSLL = fields.Char(string="Valor CSLL nao retido")

    reinf21_vlrDepCSLL = fields.Char(string="Valor deposito judicial de CSLL")

    reinf21_vlrBaseSuspCofins = fields.Char(
        string="Valor da base Cofins",
        help="Valor da base Cofins com exibilidade suspensa",
    )

    reinf21_vlrNCofins = fields.Char(
        string="Valor da retencao Cofins que deixou",
        help="Valor da retencao Cofins que deixou de ser efetuada",
    )

    reinf21_vlrDepCofins = fields.Char(string="Valor deposito judicial de Cofins")

    reinf21_vlrBaseSuspPP = fields.Char(
        string="Valor da base do PIS/PASEP",
        help="Valor da base do PIS/PASEP com exigibilidade suspensa",
    )

    reinf21_vlrNPP = fields.Char(string="Valor do PIS/PASEP nao retido")

    reinf21_vlrDepPP = fields.Char(string="Valor deposito judicial de PIS/PASEP")


class EvtRetPjInfoProcJud(models.AbstractModel):
    """Informacoes complementares relativas a rendimentos decorrentes de
    decisao judicial"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_infoprocjud"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoProcJud"

    reinf21_nrProc = fields.Char(string="Numero do Processo", xsd_required=True)

    reinf21_indOrigRec = fields.Char(
        string="Indicativo de origem dos recursos", xsd_required=True
    )

    reinf21_cnpjOrigRecurso = fields.Char(
        string="CNPJ da empresa que repassou os recursos"
    )

    reinf21_cpfOrigRecurso = fields.Char(string="CPF da origem dos recursos")

    reinf21_desc = fields.Char(string="Descricao")

    reinf21_despProcJud = fields.Many2one(
        comodel_name="reinf.21.evtretpj_infoprocjud_despprocjud",
        string="Despesas com processo judicial",
    )


class EvtRetPjInfoProcJudDespProcJud(models.AbstractModel):
    "Despesas com processo judicial"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_infoprocjud_despprocjud"
    _inherit = "spec.mixin.reinf"
    _binding_type = (
        "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoProcJud.DespProcJud"
    )

    reinf21_vlrDespCustas = fields.Char(
        string="Valor da despesa com custas judiciais", xsd_required=True
    )

    reinf21_vlrDespAdvogados = fields.Char(
        string="Valor da despesa com advogado(s)", xsd_required=True
    )

    reinf21_ideAdv = fields.One2many(
        "reinf.21.evtretpj_infoprocjud_ideadv",
        "reinf21_ideAdv_despProcJud_id",
        string="Identificacao do advogado",
    )


class EvtRetPjInfoProcJudIdeAdv(models.AbstractModel):
    "Identificacao do advogado"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_infoprocjud_ideadv"
    _inherit = "spec.mixin.reinf"
    _binding_type = (
        "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoProcJud"
        ".DespProcJud.IdeAdv"
    )

    reinf21_ideAdv_despProcJud_id = fields.Many2one(
        comodel_name="reinf.21.evtretpj_infoprocjud_despprocjud",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_tpInscAdv = fields.Char(
        string="Tipo de inscricao do advogado", xsd_required=True
    )

    reinf21_nrInscAdv = fields.Char(
        string="numero de inscricao do advogado", xsd_required=True
    )

    reinf21_vlrAdv = fields.Char(string="Valor da despesa com o advogado")


class EvtRetPjInfoPgtoExt(models.AbstractModel):
    "Informacoes complementares relativas a pagamentos no Exterior"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_infopgtoext"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoPgtoExt"

    reinf21_indNIF = fields.Char(
        string="Indicativo do preenchimento do NIF", xsd_required=True
    )

    reinf21_nifBenef = fields.Char(string="NIF do beneficiario")

    reinf21_relFontPg = fields.Char(
        string="Relacao da fonte pagadora PJ",
        xsd_required=True,
        help="Relacao da fonte pagadora PJ e beneficiario",
    )

    reinf21_frmTribut = fields.Char(string="Forma de tributacao", xsd_required=True)

    reinf21_endExt = fields.Many2one(
        comodel_name="reinf.21.evtretpj_endext",
        string="Endereco do beneficiario residente",
        help=("Endereco do beneficiario residente ou domiciliado no exterior"),
    )


class EvtRetPjEndExt(models.AbstractModel):
    "Endereco do beneficiario residente ou domiciliado no exterior"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretpj_endext"
    _inherit = "spec.mixin.reinf"
    _binding_type = (
        "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoPgtoExt.EndExt"
    )

    reinf21_dscLograd = fields.Char(string="Descricao do logradouro")

    reinf21_nrLograd = fields.Char(string="Numero do imovel no logradouro")

    reinf21_complem = fields.Char(string="Complemento")

    reinf21_bairro = fields.Char(string="Nome do bairro/distrito")

    reinf21_cidade = fields.Char(string="Nome da cidade")

    reinf21_estado = fields.Char(string="Nome da provincia/estado")

    reinf21_codPostal = fields.Char(string="CEP")

    reinf21_telef = fields.Char(string="Telefone")
