# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

import textwrap

from odoo import fields, models

__NAMESPACE__ = "http://www.reinf.esocial.gov.br/schemas/evt4099FechamentoDirf/v2_01_02"


class Reinf(models.AbstractModel):
    """Escrituracao Fiscal Digital de Retencoes e Outras Informacoes Fiscais
    (EFD-Reinf)"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.reinf"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf"

    reinf21_evtFech = fields.Many2one(
        comodel_name="reinf.21.evtfech",
        string="Evento de fechamento",
        xsd_required=True,
    )


class EvtFech(models.AbstractModel):
    "Evento de fechamento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtfech"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtFech"

    reinf21_ideEvento = fields.Many2one(
        comodel_name="reinf.21.evtfech_ideevento",
        string="Informacoes de Identificacao do Evento",
        xsd_required=True,
    )

    reinf21_ideContri = fields.Many2one(
        comodel_name="reinf.21.evtfech_idecontri",
        string="Informacoes de identificacao",
        xsd_required=True,
        help="Informacoes de identificacao do contribuinte",
    )

    reinf21_ideRespInf = fields.Many2one(
        comodel_name="reinf.21.evtfech_iderespinf",
        string="Responsavel pelas informacoes",
    )

    reinf21_infoFech = fields.Many2one(
        comodel_name="reinf.21.evtfech_infofech",
        string="Fechamento/reabertura do PA relativo",
        xsd_required=True,
        help="Fechamento/reabertura do PA relativo as retencoes na fonte",
    )

    reinf21_id = fields.Char(string="Identificacao unica do evento", xsd_required=True)


class EvtFechIdeEvento(models.AbstractModel):
    "Informacoes de Identificacao do Evento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtfech_ideevento"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtFech.IdeEvento"

    reinf21_perApur = fields.Char(string="Periodo de apuracao", xsd_required=True)

    reinf21_tpAmb = fields.Char(string="Tipo de ambiente", xsd_required=True)

    reinf21_procEmi = fields.Char(
        string="Processo de emissao do evento", xsd_required=True
    )

    reinf21_verProc = fields.Char(
        string="Versao do processo de emissao do evento", xsd_required=True
    )


class EvtFechIdeContri(models.AbstractModel):
    "Informacoes de identificacao do contribuinte"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtfech_idecontri"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtFech.IdeContri"

    reinf21_tpInsc = fields.Char(string="Tipo de Inscricao", xsd_required=True)

    reinf21_nrInsc = fields.Char(string="Numero de Inscricao", xsd_required=True)


class EvtFechIdeRespInf(models.AbstractModel):
    "Responsavel pelas informacoes"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtfech_iderespinf"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtFech.IdeRespInf"

    reinf21_nmResp = fields.Char(
        string="Responsavel pelas informacoes", xsd_required=True
    )

    reinf21_cpfResp = fields.Char(
        string="Numero de Inscricao no CPF", xsd_required=True
    )

    reinf21_telefone = fields.Char(string="Numero do telefone com DDD")

    reinf21_email = fields.Char(string="Endereco eletronico")


class EvtFechInfoFech(models.AbstractModel):
    "Fechamento/reabertura do PA relativo as retencoes na fonte"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtfech_infofech"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtFech.InfoFech"

    reinf21_fechRet = fields.Char(
        string="Indicativo de fechamento/reabertura", xsd_required=True
    )
