# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

import textwrap

from odoo import fields, models

__NAMESPACE__ = "http://www.reinf.esocial.gov.br/schemas/evtExclusao/v2_01_02"


class Reinf(models.AbstractModel):
    """Escrituracao Fiscal Digital de Retencoes e Outras Informacoes Fiscais
    (EFD-Reinf)"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.reinf"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf"

    reinf21_evtExclusao = fields.Many2one(
        comodel_name="reinf.21.evtexclusao",
        string="Evento de exclusao",
        xsd_required=True,
    )


class EvtExclusao(models.AbstractModel):
    "Evento de exclusao"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtexclusao"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtExclusao"

    reinf21_ideEvento = fields.Many2one(
        comodel_name="reinf.21.evtexclusao_ideevento",
        string="Informacoes de identificacao do evento",
        xsd_required=True,
    )

    reinf21_ideContri = fields.Many2one(
        comodel_name="reinf.21.evtexclusao_idecontri",
        string="Informacoes de identificacao",
        xsd_required=True,
        help="Informacoes de identificacao do contribuinte",
    )

    reinf21_infoExclusao = fields.Many2one(
        comodel_name="reinf.21.infoexclusao",
        string="Registro que identifica o evento objeto",
        xsd_required=True,
        help="Registro que identifica o evento objeto da exclusao",
    )

    reinf21_id = fields.Char(string="Identificacao unica do evento", xsd_required=True)


class EvtExclusaoIdeEvento(models.AbstractModel):
    "Informacoes de identificacao do evento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtexclusao_ideevento"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtExclusao.IdeEvento"

    reinf21_tpAmb = fields.Char(string="Tipo de ambiente", xsd_required=True)

    reinf21_procEmi = fields.Char(
        string="Processo de emissao do evento", xsd_required=True
    )

    reinf21_verProc = fields.Char(
        string="Versao do processo de emissao do evento", xsd_required=True
    )


class EvtExclusaoIdeContri(models.AbstractModel):
    "Informacoes de identificacao do contribuinte"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtexclusao_idecontri"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtExclusao.IdeContri"

    reinf21_tpInsc = fields.Char(string="Tipo de Inscricao", xsd_required=True)

    reinf21_nrInsc = fields.Char(string="Numero de Inscricao", xsd_required=True)


class InfoExclusao(models.AbstractModel):
    "Registro que identifica o evento objeto da exclusao"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infoexclusao"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtExclusao.InfoExclusao"

    reinf21_tpEvento = fields.Char(string="Tipo de Evento", xsd_required=True)

    reinf21_nrRecEvt = fields.Char(
        string="Numero do recibo do evento", xsd_required=True
    )
