# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

import textwrap

from odoo import fields, models

__NAMESPACE__ = "http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_02"


class Reinf(models.AbstractModel):
    """Escrituracao Fiscal Digital de Retencoes e Outras Informacoes Fiscais
    (EFD-Reinf)"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.reinf"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf"

    reinf21_evtRetCons = fields.Many2one(
        comodel_name="reinf.21.evtretcons",
        string="Evento totalizador por contribuinte",
        xsd_required=True,
    )


class EvtRetCons(models.AbstractModel):
    "Evento totalizador por contribuinte"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretcons"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons"

    reinf21_ideEvento = fields.Many2one(
        comodel_name="reinf.21.evtretcons_ideevento",
        string="Informacoes de identificacao do evento",
        xsd_required=True,
    )

    reinf21_ideContri = fields.Many2one(
        comodel_name="reinf.21.evtretcons_idecontri",
        string="Informacoes de identificacao",
        xsd_required=True,
        help="Informacoes de identificacao do contribuinte",
    )

    reinf21_ideRecRetorno = fields.Many2one(
        comodel_name="reinf.21.evtretcons_iderecretorno",
        string="Informacoes do recibo de retorno",
        xsd_required=True,
    )

    reinf21_infoRecEv = fields.Many2one(
        comodel_name="reinf.21.evtretcons_inforecev",
        string="Informacoes de processamento do evento",
        xsd_required=True,
    )

    reinf21_infoCR_CNR = fields.Many2one(
        comodel_name="reinf.21.infocrcnr",
        string="Informacoes relativas a totalizadores",
        help=(
            "Informacoes relativas a totalizadores pela natureza do rendimento"
            " e codigo de receita"
        ),
    )

    reinf21_infoTotalCR = fields.Many2one(
        comodel_name="reinf.21.infototalcr",
        string="Informacoes consolidadas dos tributos",
        help="Informacoes consolidadas dos tributos da empresa",
    )

    reinf21_id = fields.Char(string="Identificacao unica do evento", xsd_required=True)


class EvtRetConsIdeEvento(models.AbstractModel):
    "Informacoes de identificacao do evento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretcons_ideevento"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.IdeEvento"

    reinf21_perApur = fields.Char(string="Periodo de apuracao", xsd_required=True)


class EvtRetConsIdeContri(models.AbstractModel):
    "Informacoes de identificacao do contribuinte"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretcons_idecontri"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.IdeContri"

    reinf21_tpInsc = fields.Char(string="Tipo de Inscricao", xsd_required=True)

    reinf21_nrInsc = fields.Char(string="Numero de Inscricao", xsd_required=True)


class EvtRetConsIdeRecRetorno(models.AbstractModel):
    "Informacoes do recibo de retorno"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretcons_iderecretorno"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.IdeRecRetorno"

    reinf21_ideStatus = fields.Many2one(
        comodel_name="reinf.21.evtretcons_idestatus",
        string="Situacao atual do evento",
        xsd_required=True,
    )


class EvtRetConsIdeStatus(models.AbstractModel):
    "Situacao atual do evento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretcons_idestatus"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.IdeRecRetorno.IdeStatus"

    reinf21_cdRetorno = fields.Char(string="Codigo do Retorno", xsd_required=True)

    reinf21_descRetorno = fields.Char(string="Descricao do retorno", xsd_required=True)

    reinf21_regOcorrs = fields.One2many(
        "reinf.21.evtretcons_regocorrs",
        "reinf21_regOcorrs_ideStatus_id",
        string="Informacoes de ocorrencias registradas",
    )


class EvtRetConsRegOcorrs(models.AbstractModel):
    "Informacoes de ocorrencias registradas"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretcons_regocorrs"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.IdeRecRetorno.IdeStatus.RegOcorrs"

    reinf21_regOcorrs_ideStatus_id = fields.Many2one(
        comodel_name="reinf.21.evtretcons_idestatus",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_tpOcorr = fields.Char(string="Tipo da ocorrencia", xsd_required=True)

    reinf21_localErroAviso = fields.Char(string="Campo que originou o erro ou aviso")

    reinf21_codResp = fields.Char(
        string="Codigo do status da resposta",
        xsd_required=True,
        help="Codigo do status da resposta do processamento da consulta",
    )

    reinf21_dscResp = fields.Char(
        string="Descricao literal da resposta",
        xsd_required=True,
        help="Descricao literal da resposta do processamento da consulta",
    )


class EvtRetConsInfoRecEv(models.AbstractModel):
    "Informacoes de processamento do evento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evtretcons_inforecev"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoRecEv"

    reinf21_nrRecArqBase = fields.Char(
        string="Recibo do arquivo de origem", xsd_required=True
    )

    reinf21_nrProtLote = fields.Char(string="Numero do protocolo de entrega do lote")

    reinf21_dhRecepcao = fields.Datetime(
        string="Data e hora da recepcao do evento", xsd_required=True
    )

    reinf21_dhProcess = fields.Datetime(
        string="Data e hora do processamento", xsd_required=True
    )

    reinf21_tpEv = fields.Char(string="Tipo do evento", xsd_required=True)

    reinf21_idEv = fields.Char(string="ID do Evento", xsd_required=True)

    reinf21_hash = fields.Char(string="Hash do arquivo processado", xsd_required=True)

    reinf21_fechRet = fields.Char(
        string="Indicativo da finalidade do evento",
        xsd_required=True,
        help="Indicativo da finalidade do evento de origem.",
    )


class InfoCrCnr(models.AbstractModel):
    """Informacoes relativas a totalizadores pela natureza do rendimento e
    codigo de receita"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infocrcnr"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoCrCnr"

    reinf21_indExistInfo = fields.Char(string="Existe informacoes", xsd_required=True)

    reinf21_identEscritDCTF = fields.Char(
        string="Identificacao da escrituracao fiscal",
        xsd_required=True,
        help="Identificacao da escrituracao fiscal (EFD-Reinf) na DCTFWeb",
    )

    reinf21_totApurMen = fields.One2many(
        "reinf.21.infocrcnr_totapurmen",
        "reinf21_totApurMen_infoCR_CNR_id",
        string="Totalizador de tributos com periodo",
        help="Totalizador de tributos com periodo de apuracao mensal",
    )

    reinf21_totApurQui = fields.One2many(
        "reinf.21.infocrcnr_totapurqui",
        "reinf21_totApurQui_infoCR_CNR_id",
        string="totApurQui",
        help="Totalizador de tributos com periodo de apuracao quinzenal",
    )

    reinf21_totApurDec = fields.One2many(
        "reinf.21.infocrcnr_totapurdec",
        "reinf21_totApurDec_infoCR_CNR_id",
        string="Totalizador dos tributos com periodo",
        help="Totalizador dos tributos com periodo de apuracao decendial",
    )

    reinf21_totApurSem = fields.One2many(
        "reinf.21.infocrcnr_totapursem",
        "reinf21_totApurSem_infoCR_CNR_id",
        string="totApurSem",
        help="Totalizador dos tributos com periodo de apuracao semanal",
    )

    reinf21_totApurDia = fields.One2many(
        "reinf.21.infocrcnr_totapurdia",
        "reinf21_totApurDia_infoCR_CNR_id",
        string="totApurDia",
        help="Totalizador dos tributos com periodo de apuracao diario",
    )


class InfoCrCnrTotApurMen(models.AbstractModel):
    "Totalizador de tributos com periodo de apuracao mensal"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infocrcnr_totapurmen"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoCrCnr.TotApurMen"

    reinf21_totApurMen_infoCR_CNR_id = fields.Many2one(
        comodel_name="reinf.21.infocrcnr",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_CRMen = fields.Char(string="Codigo de Receita - CR", xsd_required=True)

    reinf21_vlrCRMenInf = fields.Char(
        string="Valor do tributo retido",
        xsd_required=True,
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRMenCalc = fields.Char(
        string="Valor do tributo retido (vlrCRMenCalc)",
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRMenDCTF = fields.Char(
        string="Valor do tributo retido (vlrCRMenDCTF)",
        xsd_required=True,
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRMenSuspInf = fields.Char(
        string="Valor da base do tributo",
        help="Valor da base do tributo de apuracao mensal suspenso",
    )

    reinf21_vlrCRMenSuspCalc = fields.Char(
        string="Valor do tributo", help="Valor do tributo de apuracao mensal suspenso"
    )

    reinf21_vlrCRMenSuspDCTF = fields.Char(
        string="vlrCRMenSuspDCTF", help="Valor do tributo retido com apuracao mensal"
    )

    reinf21_natRend = fields.Char(string="Natureza do Rendimento", xsd_required=True)


class InfoCrCnrTotApurQui(models.AbstractModel):
    "Totalizador de tributos com periodo de apuracao quinzenal"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infocrcnr_totapurqui"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoCrCnr.TotApurQui"

    reinf21_totApurQui_infoCR_CNR_id = fields.Many2one(
        comodel_name="reinf.21.infocrcnr",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_perApurQui = fields.Char(
        string="Periodo de apuracao quinzenal", xsd_required=True
    )

    reinf21_CRQui = fields.Char(
        string="Codigo de Receita",
        xsd_required=True,
        help="Codigo de Receita - CR de tributo com apuracao quinzenal",
    )

    reinf21_vlrCRQuiInf = fields.Char(
        string="Valor do tributo retido",
        xsd_required=True,
        help="Valor do tributo retido com apuracao quinzenal",
    )

    reinf21_vlrCRQuiCalc = fields.Char(
        string="Valor do tributo retido (vlrCRQuiCalc)",
        help="Valor do tributo retido com apuracao quinzenal",
    )

    reinf21_vlrCRQuiDCTF = fields.Char(
        string="Valor do tributo retido (vlrCRQuiDCTF)",
        xsd_required=True,
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRQuiSuspInf = fields.Char(
        string="Valor da base do tributo",
        help="Valor da base do tributo de apuracao quinzenal suspenso",
    )

    reinf21_vlrCRQuisSuspCalc = fields.Char(
        string="vlrCRQuisSuspCalc",
        help="Valor da base do tributo de apuracao quinzenal suspenso",
    )

    reinf21_vlrCRQuiSuspDCTF = fields.Char(
        string="vlrCRQuiSuspDCTF", help="Valor do tributo retido com apuracao mensal"
    )

    reinf21_natRend = fields.Char(string="Natureza do Rendimento", xsd_required=True)


class InfoCrCnrTotApurDec(models.AbstractModel):
    "Totalizador dos tributos com periodo de apuracao decendial"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infocrcnr_totapurdec"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoCrCnr.TotApurDec"

    reinf21_totApurDec_infoCR_CNR_id = fields.Many2one(
        comodel_name="reinf.21.infocrcnr",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_perApurDec = fields.Char(
        string="Periodo de apuracao decenal", xsd_required=True
    )

    reinf21_CRDec = fields.Char(
        string="Codigo de Receita",
        xsd_required=True,
        help="Codigo de Receita - CR de tributo com apuracao decendial",
    )

    reinf21_vlrCRDecInf = fields.Char(
        string="Valor do tributo retido",
        xsd_required=True,
        help="Valor do tributo retido com apuracao decendial",
    )

    reinf21_vlrCRDecCalc = fields.Char(
        string="Valor do tributo retido (vlrCRDecCalc)",
        help="Valor do tributo retido com apuracao decendial",
    )

    reinf21_vlrCRDecDCTF = fields.Char(
        string="Valor do tributo retido (vlrCRDecDCTF)",
        xsd_required=True,
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRDecSuspInf = fields.Char(
        string="Valor do tributo",
        help="Valor do tributo de apuracao decendial suspenso informado",
    )

    reinf21_vlrCRDecSuspCalc = fields.Char(
        string="Valor do tributo (vlrCRDecSuspCalc)",
        help="Valor do tributo de apuracao decendial suspenso calculado",
    )

    reinf21_vlrCRDecSuspDCTF = fields.Char(
        string="vlrCRDecSuspDCTF", help="Valor do tributo retido com apuracao mensal"
    )

    reinf21_natRend = fields.Char(string="Natureza do Rendimento", xsd_required=True)


class InfoCrCnrTotApurSem(models.AbstractModel):
    "Totalizador dos tributos com periodo de apuracao semanal"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infocrcnr_totapursem"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoCrCnr.TotApurSem"

    reinf21_totApurSem_infoCR_CNR_id = fields.Many2one(
        comodel_name="reinf.21.infocrcnr",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_perApurSem = fields.Char(
        string="Periodo de apuracao semanal", xsd_required=True
    )

    reinf21_CRSem = fields.Char(
        string="Codigo de Receita",
        xsd_required=True,
        help="Codigo de Receita - CR de tributo com apuracao semanal",
    )

    reinf21_vlrCRSemInf = fields.Char(
        string="Valor do tributo retido",
        xsd_required=True,
        help="Valor do tributo retido com apuracao semanal",
    )

    reinf21_vlrCRSemCalc = fields.Char(
        string="Valor do tributo retido (vlrCRSemCalc)",
        help="Valor do tributo retido com apuracao semanal",
    )

    reinf21_vlrCRSemDCTF = fields.Char(
        string="Valor do tributo retido (vlrCRSemDCTF)",
        xsd_required=True,
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRSemSuspInf = fields.Char(
        string="Valor da base do tributo",
        help="Valor da base do tributo de apuracao semanal suspenso",
    )

    reinf21_vlrCRSemSuspCalc = fields.Char(
        string="vlrCRSemSuspCalc",
        help="Valor da base do tributo de apuracao semanal suspenso",
    )

    reinf21_vlrCRSemSuspDCTF = fields.Char(
        string="vlrCRSemSuspDCTF", help="Valor do tributo retido com apuracao mensal"
    )

    reinf21_natRend = fields.Char(string="Natureza do Rendimento", xsd_required=True)


class InfoCrCnrTotApurDia(models.AbstractModel):
    "Totalizador dos tributos com periodo de apuracao diario"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infocrcnr_totapurdia"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoCrCnr.TotApurDia"

    reinf21_totApurDia_infoCR_CNR_id = fields.Many2one(
        comodel_name="reinf.21.infocrcnr",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_perApurDia = fields.Char(
        string="Periodo de apuracao diario", xsd_required=True
    )

    reinf21_CRDia = fields.Char(
        string="Codigo de Receita",
        xsd_required=True,
        help="Codigo de Receita - CR de tributo com apuracao diario",
    )

    reinf21_vlrCRDiaInf = fields.Char(
        string="Valor do tributo retido",
        xsd_required=True,
        help="Valor do tributo retido com apuracao diaria",
    )

    reinf21_vlrCRDiaCalc = fields.Char(
        string="Valor do tributo retido (vlrCRDiaCalc)",
        help="Valor do tributo retido com apuracao diaria",
    )

    reinf21_vlrCRDiaDCTF = fields.Char(
        string="Valor do tributo retido (vlrCRDiaDCTF)",
        xsd_required=True,
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRDiaSuspInf = fields.Char(
        string="Valor da base do tributo",
        help="Valor da base do tributo de apuracao diario suspenso",
    )

    reinf21_vlrCRDiaSuspCalc = fields.Char(
        string="vlrCRDiaSuspCalc",
        help="Valor da base do tributo de apuracao diario suspenso",
    )

    reinf21_vlrCRDiaSuspDCTF = fields.Char(
        string="vlrCRDiaSuspDCTF", help="Valor do tributo retido com apuracao mensal"
    )

    reinf21_natRend = fields.Char(string="Natureza do Rendimento", xsd_required=True)


class InfoTotalCr(models.AbstractModel):
    "Informacoes consolidadas dos tributos da empresa"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infototalcr"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoTotalCr"

    reinf21_totApurMen = fields.One2many(
        "reinf.21.infototalcr_totapurmen",
        "reinf21_totApurMen_infoTotalCR_id",
        string="Totalizador de tributos com periodo",
        help="Totalizador de tributos com periodo de apuracao mensal",
    )

    reinf21_totApurQui = fields.One2many(
        "reinf.21.infototalcr_totapurqui",
        "reinf21_totApurQui_infoTotalCR_id",
        string="totApurQui",
        help="Totalizador de tributos com periodo de apuracao quinzenal",
    )

    reinf21_totApurDec = fields.One2many(
        "reinf.21.infototalcr_totapurdec",
        "reinf21_totApurDec_infoTotalCR_id",
        string="Totalizador dos tributos com periodo",
        help="Totalizador dos tributos com periodo de apuracao decendial",
    )

    reinf21_totApurSem = fields.One2many(
        "reinf.21.infototalcr_totapursem",
        "reinf21_totApurSem_infoTotalCR_id",
        string="totApurSem",
        help="Totalizador dos tributos com periodo de apuracao semanal",
    )

    reinf21_totApurDia = fields.One2many(
        "reinf.21.infototalcr_totapurdia",
        "reinf21_totApurDia_infoTotalCR_id",
        string="totApurDia",
        help="Totalizador dos tributos com periodo de apuracao diario",
    )


class InfoTotalCrTotApurMen(models.AbstractModel):
    "Totalizador de tributos com periodo de apuracao mensal"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infototalcr_totapurmen"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoTotalCr.TotApurMen"

    reinf21_totApurMen_infoTotalCR_id = fields.Many2one(
        comodel_name="reinf.21.infototalcr",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_CRMen = fields.Char(string="Codigo de Receita - CR", xsd_required=True)

    reinf21_vlrCRMenDCTF = fields.Char(
        string="Valor do tributo retido",
        xsd_required=True,
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRMenSuspDCTF = fields.Char(
        string="vlrCRMenSuspDCTF", help="Valor do tributo retido com apuracao mensal"
    )


class InfoTotalCrTotApurQui(models.AbstractModel):
    "Totalizador de tributos com periodo de apuracao quinzenal"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infototalcr_totapurqui"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoTotalCr.TotApurQui"

    reinf21_totApurQui_infoTotalCR_id = fields.Many2one(
        comodel_name="reinf.21.infototalcr",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_perApurQui = fields.Char(
        string="Periodo de apuracao quinzenal", xsd_required=True
    )

    reinf21_CRQui = fields.Char(
        string="Codigo de Receita",
        xsd_required=True,
        help="Codigo de Receita - CR de tributo com apuracao quinzenal",
    )

    reinf21_vlrCRQuiDCTF = fields.Char(
        string="Valor do tributo retido",
        xsd_required=True,
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRQuiSuspDCTF = fields.Char(
        string="vlrCRQuiSuspDCTF", help="Valor do tributo retido com apuracao mensal"
    )


class InfoTotalCrTotApurDec(models.AbstractModel):
    "Totalizador dos tributos com periodo de apuracao decendial"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infototalcr_totapurdec"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoTotalCr.TotApurDec"

    reinf21_totApurDec_infoTotalCR_id = fields.Many2one(
        comodel_name="reinf.21.infototalcr",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_perApurDec = fields.Char(
        string="Periodo de apuracao decenal", xsd_required=True
    )

    reinf21_CRDec = fields.Char(
        string="Codigo de Receita",
        xsd_required=True,
        help="Codigo de Receita - CR de tributo com apuracao decendial",
    )

    reinf21_vlrCRDecDCTF = fields.Char(
        string="Valor do tributo retido",
        xsd_required=True,
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRDecSuspDCTF = fields.Char(
        string="vlrCRDecSuspDCTF", help="Valor do tributo retido com apuracao mensal"
    )


class InfoTotalCrTotApurSem(models.AbstractModel):
    "Totalizador dos tributos com periodo de apuracao semanal"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infototalcr_totapursem"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoTotalCr.TotApurSem"

    reinf21_totApurSem_infoTotalCR_id = fields.Many2one(
        comodel_name="reinf.21.infototalcr",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_perApurSem = fields.Char(
        string="Periodo de apuracao semanal", xsd_required=True
    )

    reinf21_CRSem = fields.Char(
        string="Codigo de Receita",
        xsd_required=True,
        help="Codigo de Receita - CR de tributo com apuracao semanal",
    )

    reinf21_vlrCRSemDCTF = fields.Char(
        string="Valor do tributo retido",
        xsd_required=True,
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRSemSuspDCTF = fields.Char(
        string="vlrCRSemSuspDCTF", help="Valor do tributo retido com apuracao mensal"
    )


class InfoTotalCrTotApurDia(models.AbstractModel):
    "Totalizador dos tributos com periodo de apuracao diario"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.infototalcr_totapurdia"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtRetCons.InfoTotalCr.TotApurDia"

    reinf21_totApurDia_infoTotalCR_id = fields.Many2one(
        comodel_name="reinf.21.infototalcr",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_perApurDia = fields.Char(
        string="Periodo de apuracao diario", xsd_required=True
    )

    reinf21_CRDia = fields.Char(
        string="Codigo de Receita",
        xsd_required=True,
        help="Codigo de Receita - CR de tributo com apuracao diario",
    )

    reinf21_vlrCRDiaDCTF = fields.Char(
        string="Valor do tributo retido",
        xsd_required=True,
        help="Valor do tributo retido com apuracao mensal",
    )

    reinf21_vlrCRDiaSuspDCTF = fields.Char(
        string="vlrCRDiaSuspDCTF", help="Valor do tributo retido com apuracao mensal"
    )
