# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

import textwrap

from odoo import fields, models

__NAMESPACE__ = "http://www.reinf.esocial.gov.br/schemas/evtTotal/v2_01_02"


class Reinf(models.AbstractModel):
    """Escrituracao Fiscal Digital de Retencoes e Outras Informacoes Fiscais
    (EFD-Reinf)"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.reinf"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf"

    reinf21_evtTotal = fields.Many2one(
        comodel_name="reinf.21.evttotal", string="Evento totalizacao", xsd_required=True
    )


class EvtTotal(models.AbstractModel):
    "Evento totalizacao"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal"

    reinf21_ideEvento = fields.Many2one(
        comodel_name="reinf.21.evttotal_ideevento",
        string="Informacoes de identificacao do evento",
    )

    reinf21_ideContri = fields.Many2one(
        comodel_name="reinf.21.evttotal_idecontri",
        string="Informacoes de identificacao",
        xsd_required=True,
        help="Informacoes de identificacao do contribuinte",
    )

    reinf21_ideRecRetorno = fields.Many2one(
        comodel_name="reinf.21.evttotal_iderecretorno",
        string="Informacoes do recibo de retorno",
        xsd_required=True,
    )

    reinf21_infoRecEv = fields.Many2one(
        comodel_name="reinf.21.evttotal_inforecev",
        string="Informacoes de processamento dos eventos",
        xsd_required=True,
    )

    reinf21_infoTotal = fields.Many2one(
        comodel_name="reinf.21.evttotal_infototal",
        string="Informacoes relativas as Totalizacoes",
    )

    reinf21_id = fields.Char(string="Identificacao unica do evento", xsd_required=True)


class EvtTotalIdeEvento(models.AbstractModel):
    "Informacoes de identificacao do evento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_ideevento"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.IdeEvento"


class EvtTotalIdeContri(models.AbstractModel):
    "Informacoes de identificacao do contribuinte"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_idecontri"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.IdeContri"

    reinf21_tpInsc = fields.Char(string="Tipo de Inscricao", xsd_required=True)

    reinf21_nrInsc = fields.Char(string="Numero de Inscricao", xsd_required=True)


class EvtTotalIdeRecRetorno(models.AbstractModel):
    "Informacoes do recibo de retorno"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_iderecretorno"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.IdeRecRetorno"

    reinf21_ideStatus = fields.Many2one(
        comodel_name="reinf.21.evttotal_idestatus",
        string="Situacao atual do evento",
        xsd_required=True,
    )


class EvtTotalIdeStatus(models.AbstractModel):
    "Situacao atual do evento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_idestatus"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.IdeRecRetorno.IdeStatus"

    reinf21_cdRetorno = fields.Char(string="Codigo do Retorno", xsd_required=True)

    reinf21_descRetorno = fields.Char(string="Descricao do retorno", xsd_required=True)

    reinf21_regOcorrs = fields.One2many(
        "reinf.21.evttotal_regocorrs",
        "reinf21_regOcorrs_ideStatus_id",
        string="Informacoes de ocorrencias registradas",
    )


class EvtTotalRegOcorrs(models.AbstractModel):
    "Informacoes de ocorrencias registradas"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_regocorrs"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.IdeRecRetorno.IdeStatus.RegOcorrs"

    reinf21_regOcorrs_ideStatus_id = fields.Many2one(
        comodel_name="reinf.21.evttotal_idestatus",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_tpOcorr = fields.Char(string="Tipo da ocorrencia", xsd_required=True)

    reinf21_localErroAviso = fields.Char(string="Campo que originou o erro ou aviso")

    reinf21_codResp = fields.Char(
        string="Codigo do status da resposta",
        xsd_required=True,
        help="Codigo do status da resposta do processamento da consulta",
    )

    reinf21_dscResp = fields.Char(
        string="Descricao literal da resposta",
        xsd_required=True,
        help="Descricao literal da resposta do processamento da consulta",
    )


class EvtTotalInfoRecEv(models.AbstractModel):
    "Informacoes de processamento dos eventos"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_inforecev"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.InfoRecEv"

    reinf21_nrRecArqBase = fields.Char(string="Recibo do arquivo de origem")

    reinf21_nrProtEntr = fields.Char(string="Numero do protocolo de entrega do evento")

    reinf21_dhRecepcao = fields.Datetime(
        string="Data e hora da recepcao do evento", xsd_required=True
    )

    reinf21_dhProcess = fields.Datetime(
        string="Data e hora do processamento", xsd_required=True
    )

    reinf21_tpEv = fields.Char(string="Tipo do evento", xsd_required=True)

    reinf21_idEv = fields.Char(string="ID do Evento", xsd_required=True)

    reinf21_hash = fields.Char(string="Hash do arquivo processado", xsd_required=True)


class EvtTotalInfoTotal(models.AbstractModel):
    "Informacoes relativas as Totalizacoes"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_infototal"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.InfoTotal"

    reinf21_ideEstab = fields.Many2one(
        comodel_name="reinf.21.evttotal_ideestab",
        string="Identificacao do estabelecimento",
    )


class EvtTotalIdeEstab(models.AbstractModel):
    "Identificacao do estabelecimento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_ideestab"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.InfoTotal.IdeEstab"

    reinf21_tpInsc = fields.Char(string="Tipo de Inscricao", xsd_required=True)

    reinf21_nrInsc = fields.Char(string="Numero de Inscricao", xsd_required=True)

    reinf21_RTom = fields.Many2one(
        comodel_name="reinf.21.evttotal_rtom", string="Totalizador do evento R-2010"
    )

    reinf21_RPrest = fields.Many2one(
        comodel_name="reinf.21.evttotal_rprest", string="Totalizador do evento R-2020"
    )

    reinf21_RRecRepAD = fields.One2many(
        "reinf.21.evttotal_rrecrepad",
        "reinf21_RRecRepAD_ideEstab_id",
        string="Totalizador dos eventos R-2030 e R-2040",
    )

    reinf21_RComl = fields.One2many(
        "reinf.21.evttotal_rcoml",
        "reinf21_RComl_ideEstab_id",
        string="Totalizacao do evento R-2050",
    )

    reinf21_RAquis = fields.One2many(
        "reinf.21.evttotal_raquis",
        "reinf21_RAquis_ideEstab_id",
        string="Totalizacao do evento R-2055",
    )

    reinf21_RCPRB = fields.One2many(
        "reinf.21.evttotal_rcprb",
        "reinf21_RCPRB_ideEstab_id",
        string="Totalizador do evento R-2060",
    )

    reinf21_RRecEspetDesp = fields.Many2one(
        comodel_name="reinf.21.rrecespetdesp", string="Totalizador do evento R-3010"
    )


class EvtTotalRtom(models.AbstractModel):
    "Totalizador do evento R-2010"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_rtom"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.InfoTotal.IdeEstab.Rtom"

    reinf21_cnpjPrestador = fields.Char(
        string="CNPJ do Prestador de Servicos", xsd_required=True
    )

    reinf21_cno = fields.Char(string="Nro. CNO")

    reinf21_vlrTotalBaseRet = fields.Char(
        string="Base de calculo da retencao",
        xsd_required=True,
        help="Base de calculo da retencao da contribuicao previdenciaria.",
    )

    reinf21_infoCRTom = fields.One2many(
        "reinf.21.evttotal_infocrtom",
        "reinf21_infoCRTom_RTom_id",
        string="Informacoes",
        help="Informacoes de retencoes sobre servicos prestados",
    )


class EvtTotalInfoCrtom(models.AbstractModel):
    "Informacoes de retencoes sobre servicos prestados"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_infocrtom"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.InfoTotal.IdeEstab.Rtom.InfoCrtom"

    reinf21_infoCRTom_RTom_id = fields.Many2one(
        comodel_name="reinf.21.evttotal_rtom",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_CRTom = fields.Char(
        string="Cod. de Receita - Servicos Tomados", xsd_required=True
    )

    reinf21_vlrCRTom = fields.Char(
        string="Valor da CP correspondente",
        help="Valor da CP correspondente ao CR informado em {CRTom}",
    )

    reinf21_vlrCRTomSusp = fields.Char(string="Valor suspenso da CP")


class EvtTotalRprest(models.AbstractModel):
    "Totalizador do evento R-2020"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_rprest"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.InfoTotal.IdeEstab.Rprest"

    reinf21_tpInscTomador = fields.Char(
        string="Tipo de Inscricao",
        xsd_required=True,
        help="Tipo de Inscricao do Contratante(tomador)",
    )

    reinf21_nrInscTomador = fields.Char(string="Numero de Inscricao", xsd_required=True)

    reinf21_vlrTotalBaseRet = fields.Char(
        string="Base de calculo da retencao",
        xsd_required=True,
        help="Base de calculo da retencao da contribuicao previdenciaria.",
    )

    reinf21_vlrTotalRetPrinc = fields.Char(
        string="Valor da retencao principal",
        xsd_required=True,
        help="Valor da retencao principal das notas fiscais de servico",
    )

    reinf21_vlrTotalRetAdic = fields.Char(
        string="Soma do valor do adicional de retencao",
        help="Soma do valor do adicional de retencao das notas fiscais",
    )

    reinf21_vlrTotalNRetPrinc = fields.Char(
        string="vlrTotalNRetPrinc",
        help="Valor da retencao principal que deixou de ser efetuada",
    )

    reinf21_vlrTotalNRetAdic = fields.Char(
        string="Valor da retencao adicional",
        help="Valor da retencao adicional que deixou de ser efetuada",
    )


class EvtTotalRrecRepAd(models.AbstractModel):
    "Totalizador dos eventos R-2030 e R-2040"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_rrecrepad"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.InfoTotal.IdeEstab.RrecRepAd"

    reinf21_RRecRepAD_ideEstab_id = fields.Many2one(
        comodel_name="reinf.21.evttotal_ideestab",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_cnpjAssocDesp = fields.Char(string="CNPJ da Associacao Desportiva")

    reinf21_nmEmprExt = fields.Char(
        string="Nome da empresa nao sujeita a inscricao",
        help="Nome da empresa nao sujeita a inscricao no CNPJ",
    )

    reinf21_vlrTotalRep = fields.Char(string="Valor Total Repassado", xsd_required=True)

    reinf21_CRRecRepAD = fields.Char(
        string="Cod de Receita CP sobre repasses",
        xsd_required=True,
        help="Cod de Receita CP sobre repasses a associacoes desportivas",
    )

    reinf21_vlrCRRecRepAD = fields.Char(
        string="CP sobre Repasses",
        xsd_required=True,
        help="CP sobre Repasses a Associacoes Desportivas",
    )

    reinf21_vlrCRRecRepADSusp = fields.Char(
        string="Retencao de CP nao efetuada",
        help=(
            "Retencao de CP nao efetuada ou depositada em juizo por decisao "
            "judicial/administrativa"
        ),
    )


class EvtTotalRcoml(models.AbstractModel):
    "Totalizacao do evento R-2050"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_rcoml"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.InfoTotal.IdeEstab.Rcoml"

    reinf21_RComl_ideEstab_id = fields.Many2one(
        comodel_name="reinf.21.evttotal_ideestab",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_CRComl = fields.Char(
        string="Cod Receita - CRs/comercializacao", xsd_required=True
    )

    reinf21_vlrCRComl = fields.Char(
        string="Valor da CP correspondente",
        xsd_required=True,
        help="Valor da CP correspondente ao CR informado em {CRComl}",
    )

    reinf21_vlrCRComlSusp = fields.Char(
        string="Valor suspenso da CP correspondente",
        help=("Valor suspenso da CP correspondente ao CR informado em {CRComl}"),
    )


class EvtTotalRaquis(models.AbstractModel):
    "Totalizacao do evento R-2055"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_raquis"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.InfoTotal.IdeEstab.Raquis"

    reinf21_RAquis_ideEstab_id = fields.Many2one(
        comodel_name="reinf.21.evttotal_ideestab",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_CRAquis = fields.Char(string="Cod Receita - Aquisicao", xsd_required=True)

    reinf21_vlrCRAquis = fields.Char(
        string="Valor da CP correspondente",
        xsd_required=True,
        help="Valor da CP correspondente ao CR informado em {CRAquis}",
    )

    reinf21_vlrCRAquisSusp = fields.Char(
        string="Valor suspenso da CP correspondente",
        help=("Valor suspenso da CP correspondente ao CR informado em {CRAquis}"),
    )


class EvtTotalRcprb(models.AbstractModel):
    "Totalizador do evento R-2060"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.evttotal_rcprb"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.InfoTotal.IdeEstab.Rcprb"

    reinf21_RCPRB_ideEstab_id = fields.Many2one(
        comodel_name="reinf.21.evttotal_ideestab",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    reinf21_CRCPRB = fields.Char(string="CR relativo a CPRB", xsd_required=True)

    reinf21_vlrCRCPRB = fields.Char(string="Valor da CPRB", xsd_required=True)

    reinf21_vlrCRCPRBSusp = fields.Char(
        string="Valor da CPRB com exigibilidade suspensa"
    )


class RrecEspetDesp(models.AbstractModel):
    "Totalizador do evento R-3010"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "reinf.21.rrecespetdesp"
    _inherit = "spec.mixin.reinf"
    _binding_type = "Reinf.EvtTotal.InfoTotal.IdeEstab.RrecEspetDesp"

    reinf21_CRRecEspetDesp = fields.Char(
        string="Cod",
        xsd_required=True,
        help=("Cod. de Receita relativo a CP s/Receita de Espetaculos Desportivos"),
    )

    reinf21_vlrReceitaTotal = fields.Char(
        string="Valor da receita bruta total", xsd_required=True
    )

    reinf21_vlrCRRecEspetDesp = fields.Char(
        string="Valor da CP correspondente",
        xsd_required=True,
        help=("Valor da CP correspondente ao CR informado em {CRRecEspetDesp}."),
    )

    reinf21_vlrCRRecEspetDespSusp = fields.Char(
        string="Valor da CP com exigibilidade suspensa",
        help=("Valor da CP com exigibilidade suspensa - espetaculos desportivos"),
    )
