-
  In order to test taxes on products
-
  I apply fiscal classification taxes on products
-
  !python {model: account.product.fiscal.classification}: |
    fc_ids = self.search(cr, uid, [])
    res = self.button_update_products(cr, uid, fc_ids, {})
-
  I check taxes on products
-
  !python {model: product.product}: |
    product_id = ref('product.product_product_8')
    product = self.browse(cr, uid, product_id)
    assert len(product.taxes_id) == 3
    assert len(product.supplier_taxes_id) == 3
