# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

import textwrap

from odoo import fields, models

from .tipos_basico_gnre_v1_00 import (
    TCAMPOSGNRE,
    TSIMNAO,
    TTIPOCAMPOEXTRA,
    TUF,
)
from .tipos_basico_gnre_v2_00 import (
    TCAMPOSGNRE2,
    TSIMNAOOPCIONAL,
)

__NAMESPACE__ = "http://www.gnre.pe.gov.br"

TCONFIGUF_AMBIENTE = [
    ("1", "1"),
    ("2", "2"),
]

TTIPOVALOR = [
    ("P", "P"),
    ("T", "T"),
    ("A", "A"),
    ("N", "N"),
    ("PO", "PO"),
    ("TO", "TO"),
    ("AO", "AO"),
]

PERIODOAPURACAO_CODIGO = [
    ("0", "0"),
    ("1", "1"),
    ("2", "2"),
    ("3", "3"),
    ("4", "4"),
    ("5", "5"),
]

TIPOSGNREDAUF_TIPOGNRE = [
    ("0", "0"),
    ("1", "1"),
    ("2", "2"),
]

TIPOSGNRE_TIPOGNRE = [
    ("0", "0"),
    ("1", "1"),
    ("2", "2"),
]

VERSOESXMLCAMPOADICIONAL_VERSAO = [
    ("1.00", "1.00"),
    ("2.00", "2.00"),
]

VERSOESXMLDOCORIGEM_VERSAO = [
    ("1.00", "1.00"),
    ("2.00", "2.00"),
]

VERSOESXML_VERSAO = [
    ("1.00", "1.00"),
    ("2.00", "2.00"),
]


class TconfigUf(models.AbstractModel):
    _description = "TConfigUf"
    _name = "gnre.20.tconfiguf"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf"

    gnre20_ambiente = fields.Selection(
        TCONFIGUF_AMBIENTE, string="ambiente", xsd_required=True
    )

    gnre20_uf = fields.Selection(TUF, string="uf", xsd_type="tns:TUf")

    gnre20_situacaoConsulta = fields.Many2one(
        comodel_name="gnre.20.situacaoconsulta",
        string="situacaoConsulta",
        xsd_required=True,
    )

    gnre20_exigeUfFavorecida = fields.Many2one(
        comodel_name="gnre.20.exigeuffavorecida", string="exigeUfFavorecida"
    )

    gnre20_exigeReceita = fields.Many2one(
        comodel_name="gnre.20.exigereceita", string="exigeReceita"
    )

    gnre20_receitas = fields.Many2one(
        comodel_name="gnre.20.receitas", string="receitas"
    )

    gnre20_versoesXml = fields.Many2one(
        comodel_name="gnre.20.versoesxml", string="versoesXml"
    )

    gnre20_qtdMaximas = fields.Many2one(
        comodel_name="gnre.20.qtdmaximas", string="qtdMaximas"
    )

    gnre20_tiposGnreDaUF = fields.Many2one(
        comodel_name="gnre.20.tiposgnredauf", string="tiposGnreDaUF"
    )

    gnre20_enderecoObr = fields.Many2one(
        comodel_name="gnre.20.enderecoobr",
        string="Indicador de obrigatoriedade",
        xsd_required=True,
        help=(
            "Indicador de obrigatoriedade de preenchimento do campo Endereco "
            "quando o Emitente for identificado por CNPJ ou CPF."
        ),
    )


class SituacaoConsulta(models.AbstractModel):
    _description = "situacaoConsulta"
    _name = "gnre.20.situacaoconsulta"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.SituacaoConsulta"

    gnre20_codigo = fields.Char(string="codigo", xsd_required=True)

    gnre20_descricao = fields.Char(string="descricao", xsd_required=True)


class ExigeUfFavorecida(models.AbstractModel):
    _description = "exigeUfFavorecida"
    _name = "gnre.20.exigeuffavorecida"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.ExigeUfFavorecida"

    gnre20_value = fields.Selection(TSIMNAO, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class ExigeReceita(models.AbstractModel):
    _description = "exigeReceita"
    _name = "gnre.20.exigereceita"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.ExigeReceita"

    gnre20_value = fields.Selection(TSIMNAO, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class Receitas(models.AbstractModel):
    _description = "receitas"
    _name = "gnre.20.receitas"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas"

    gnre20_receita = fields.One2many(
        "gnre.20.tconfiguf_receita", "gnre20_receita_receitas_id", string="receita"
    )


class TconfigUfReceita(models.AbstractModel):
    _description = "receita"
    _name = "gnre.20.tconfiguf_receita"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita"

    gnre20_receita_receitas_id = fields.Many2one(
        comodel_name="gnre.20.receitas",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_exigeContribuinteEmitente = fields.Selection(
        TSIMNAO, string="exigeContribuinteEmitente", xsd_type="tns:TSimNao"
    )

    gnre20_exigeDetalhamentoReceita = fields.Many2one(
        comodel_name="gnre.20.exigedetalhamentoreceita",
        string="exigeDetalhamentoReceita",
        xsd_required=True,
    )

    gnre20_detalhamentosReceita = fields.Many2one(
        comodel_name="gnre.20.detalhamentosreceita", string="detalhamentosReceita"
    )

    gnre20_exigeProduto = fields.Many2one(
        comodel_name="gnre.20.exigeproduto", string="exigeProduto", xsd_required=True
    )

    gnre20_produtos = fields.Many2one(
        comodel_name="gnre.20.produtos", string="produtos"
    )

    gnre20_exigePeriodoReferencia = fields.Many2one(
        comodel_name="gnre.20.exigeperiodoreferencia",
        string="exigePeriodoReferencia",
        xsd_required=True,
    )

    gnre20_exigePeriodoApuracao = fields.Many2one(
        comodel_name="gnre.20.exigeperiodoapuracao", string="exigePeriodoApuracao"
    )

    gnre20_periodosApuracao = fields.Many2one(
        comodel_name="gnre.20.periodosapuracao", string="periodosApuracao"
    )

    gnre20_exigeParcela = fields.Many2one(
        comodel_name="gnre.20.exigeparcela", string="exigeParcela"
    )

    gnre20_valorExigido = fields.Many2one(
        comodel_name="gnre.20.valorexigido",
        string="P-Valor principal, T-Valor total",
        xsd_required=True,
        help=(
            "P-Valor principal, T-Valor total, A-Valor principal e total, PO-"
            "Valor principal opcional,\nTO-Valor total opcional, AO-Valor "
            "principal e total opcional e\nN-Nenhum (Não precisa informar um "
            "valor.Será informado pela UF)"
        ),
    )

    gnre20_exigeDocumentoOrigem = fields.Many2one(
        comodel_name="gnre.20.exigedocumentoorigem",
        string="exigeDocumentoOrigem",
        xsd_required=True,
    )

    gnre20_tiposDocumentosOrigem = fields.Many2one(
        comodel_name="gnre.20.tiposdocumentosorigem", string="tiposDocumentosOrigem"
    )

    gnre20_versoesXmlDocOrigem = fields.Many2one(
        comodel_name="gnre.20.versoesxmldocorigem",
        string="Versões (do XML)",
        help=("Versões (do XML) que\nexibirão os\nDocumentos de Origem\nda Receita."),
    )

    gnre20_exigeContribuinteDestinatario = fields.Selection(
        TSIMNAOOPCIONAL,
        string="N - Não exibe",
        xsd_required=True,
        xsd_type="tns:TSimNaoOpcional",
        help=(
            "N - Não exibe\n\t\t\t\t\t\t\t\t\t\t\t\t\tS - Sim "
            "(obrigatório)\n\t\t\t\t\t\t\t\t\t\t\t\t\tO - Opcional (exibe)"
        ),
    )

    gnre20_exigeDataVencimento = fields.Many2one(
        comodel_name="gnre.20.exigedatavencimento", string="exigeDataVencimento"
    )

    gnre20_exigeDataPagamento = fields.Many2one(
        comodel_name="gnre.20.exigedatapagamento", string="exigeDataPagamento"
    )

    gnre20_exigeConvenio = fields.Many2one(
        comodel_name="gnre.20.exigeconvenio",
        string="N - Não exigido",
        help=("N - Não exigido \nS -\tOpcional \nO - Exigido\t(deve-se informar)"),
    )

    gnre20_exigeValorFecp = fields.Many2one(
        comodel_name="gnre.20.exigevalorfecp",
        string="N - Não exigido (exigeValorFecp)",
        help=("N - Não exigido \nS -\tOpcional \nO - Exigido\t(deve-se informar)"),
    )

    gnre20_exigeCamposAdicionais = fields.Many2one(
        comodel_name="gnre.20.exigecamposadicionais",
        string="exigeCamposAdicionais",
        xsd_required=True,
    )

    gnre20_camposAdicionais = fields.Many2one(
        comodel_name="gnre.20.camposadicionais", string="camposAdicionais"
    )

    gnre20_tiposGnre = fields.Many2one(
        comodel_name="gnre.20.tiposgnre", string="tiposGnre"
    )

    gnre20_aceitaPgPix = fields.Selection(
        TSIMNAO, string="aceitaPgPix", xsd_required=True
    )

    gnre20_codigo = fields.Char(string="codigo", xsd_required=True)

    gnre20_descricao = fields.Char(string="descricao", xsd_required=True)

    gnre20_courier = fields.Selection(TSIMNAO, string="courier", xsd_type="tns:TSimNao")


class ExigeDetalhamentoReceita(models.AbstractModel):
    _description = "exigeDetalhamentoReceita"
    _name = "gnre.20.exigedetalhamentoreceita"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ExigeDetalhamentoReceita"

    gnre20_value = fields.Selection(TSIMNAO, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_type="tns:TCamposGNRE"
    )


class DetalhamentosReceita(models.AbstractModel):
    _description = "detalhamentosReceita"
    _name = "gnre.20.detalhamentosreceita"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.DetalhamentosReceita"

    gnre20_detalhamentoReceita = fields.One2many(
        "gnre.20.detalhamentoreceita",
        "gnre20_detalhamentoReceita_detalhamentosReceita_id",
        string="detalhamentoReceita",
    )


class DetalhamentoReceita(models.AbstractModel):
    _description = "detalhamentoReceita"
    _name = "gnre.20.detalhamentoreceita"
    _inherit = "spec.mixin.gnre"
    _binding_type = (
        "TconfigUf.Receitas.Receita.DetalhamentosReceita.DetalhamentoReceita"
    )

    gnre20_detalhamentoReceita_detalhamentosReceita_id = fields.Many2one(
        comodel_name="gnre.20.detalhamentosreceita",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_codigo = fields.Char(string="codigo", xsd_required=True)

    gnre20_descricao = fields.Char(string="descricao", xsd_required=True)


class ExigeProduto(models.AbstractModel):
    _description = "exigeProduto"
    _name = "gnre.20.exigeproduto"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ExigeProduto"

    gnre20_value = fields.Selection(TSIMNAO, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_type="tns:TCamposGNRE"
    )


class Produtos(models.AbstractModel):
    _description = "produtos"
    _name = "gnre.20.produtos"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.Produtos"

    gnre20_produto = fields.One2many(
        "gnre.20.produto", "gnre20_produto_produtos_id", string="produto"
    )


class Produto(models.AbstractModel):
    _description = "produto"
    _name = "gnre.20.produto"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.Produtos.Produto"

    gnre20_produto_produtos_id = fields.Many2one(
        comodel_name="gnre.20.produtos",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_codigo = fields.Char(string="codigo", xsd_required=True)

    gnre20_descricao = fields.Char(string="descricao", xsd_required=True)


class ExigePeriodoReferencia(models.AbstractModel):
    _description = "exigePeriodoReferencia"
    _name = "gnre.20.exigeperiodoreferencia"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ExigePeriodoReferencia"

    gnre20_value = fields.Selection(TSIMNAO, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class ExigePeriodoApuracao(models.AbstractModel):
    _description = "exigePeriodoApuracao"
    _name = "gnre.20.exigeperiodoapuracao"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ExigePeriodoApuracao"

    gnre20_value = fields.Selection(TSIMNAO, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class PeriodosApuracao(models.AbstractModel):
    _description = "periodosApuracao"
    _name = "gnre.20.periodosapuracao"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.PeriodosApuracao"

    gnre20_periodoApuracao = fields.One2many(
        "gnre.20.periodoapuracao",
        "gnre20_periodoApuracao_periodosApuracao_id",
        string="periodoApuracao",
    )


class PeriodoApuracao(models.AbstractModel):
    _description = "periodoApuracao"
    _name = "gnre.20.periodoapuracao"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.PeriodosApuracao.PeriodoApuracao"

    gnre20_periodoApuracao_periodosApuracao_id = fields.Many2one(
        comodel_name="gnre.20.periodosapuracao",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_codigo = fields.Selection(
        PERIODOAPURACAO_CODIGO, string="codigo", xsd_required=True
    )

    gnre20_descricao = fields.Char(
        string="descricao", xsd_required=True, xsd_type="tns:TString"
    )


class ExigeParcela(models.AbstractModel):
    _description = "exigeParcela"
    _name = "gnre.20.exigeparcela"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ExigeParcela"

    gnre20_value = fields.Selection(TSIMNAO, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class ValorExigido(models.AbstractModel):
    """P-Valor principal, T-Valor total, A-Valor principal e total, PO-Valor
    principal opcional,
    TO-Valor total opcional, AO-Valor principal e total opcional e
    N-Nenhum (Não precisa informar um valor.Será informado pela UF)"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.valorexigido"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ValorExigido"

    gnre20_value = fields.Selection(TTIPOVALOR, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_type="tns:TCamposGNRE"
    )


class ExigeDocumentoOrigem(models.AbstractModel):
    _description = "exigeDocumentoOrigem"
    _name = "gnre.20.exigedocumentoorigem"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ExigeDocumentoOrigem"

    gnre20_value = fields.Selection(TSIMNAO, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class TiposDocumentosOrigem(models.AbstractModel):
    _description = "tiposDocumentosOrigem"
    _name = "gnre.20.tiposdocumentosorigem"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.TiposDocumentosOrigem"

    gnre20_tipoDocumentoOrigem = fields.One2many(
        "gnre.20.tipodocumentoorigem",
        "gnre20_tipoDocumentoOrigem_tiposDocumentosOrigem_id",
        string="tipoDocumentoOrigem",
    )

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class TipoDocumentoOrigem(models.AbstractModel):
    _description = "tipoDocumentoOrigem"
    _name = "gnre.20.tipodocumentoorigem"
    _inherit = "spec.mixin.gnre"
    _binding_type = (
        "TconfigUf.Receitas.Receita.TiposDocumentosOrigem.TipoDocumentoOrigem"
    )

    gnre20_tipoDocumentoOrigem_tiposDocumentosOrigem_id = fields.Many2one(
        comodel_name="gnre.20.tiposdocumentosorigem",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_codigo = fields.Char(string="codigo", xsd_required=True)

    gnre20_descricao = fields.Char(
        string="descricao", xsd_required=True, xsd_type="tns:TString"
    )


class VersoesXmlDocOrigem(models.AbstractModel):
    """Versões (do XML) que
    exibirão os
    Documentos de Origem
    da Receita."""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.versoesxmldocorigem"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.VersoesXmlDocOrigem"


class ExigeDataVencimento(models.AbstractModel):
    _description = "exigeDataVencimento"
    _name = "gnre.20.exigedatavencimento"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ExigeDataVencimento"

    gnre20_value = fields.Selection(TSIMNAO, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class ExigeDataPagamento(models.AbstractModel):
    _description = "exigeDataPagamento"
    _name = "gnre.20.exigedatapagamento"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ExigeDataPagamento"

    gnre20_value = fields.Selection(TSIMNAO, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class ExigeConvenio(models.AbstractModel):
    """N - Não exigido
    S - Opcional
    O - Exigido (deve-se informar)"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.exigeconvenio"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ExigeConvenio"

    gnre20_value = fields.Selection(TSIMNAOOPCIONAL, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class ExigeValorFecp(models.AbstractModel):
    """N - Não exigido
    S - Opcional
    O - Exigido (deve-se informar)"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.exigevalorfecp"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ExigeValorFecp"

    gnre20_value = fields.Selection(TSIMNAOOPCIONAL, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE2, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE2"
    )


class ExigeCamposAdicionais(models.AbstractModel):
    _description = "exigeCamposAdicionais"
    _name = "gnre.20.exigecamposadicionais"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.ExigeCamposAdicionais"

    gnre20_value = fields.Selection(TSIMNAO, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class CamposAdicionais(models.AbstractModel):
    _description = "camposAdicionais"
    _name = "gnre.20.camposadicionais"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.CamposAdicionais"

    gnre20_campoAdicional = fields.One2many(
        "gnre.20.campoadicional",
        "gnre20_campoAdicional_camposAdicionais_id",
        string="campoAdicional",
    )


class CampoAdicional(models.AbstractModel):
    _description = "campoAdicional"
    _name = "gnre.20.campoadicional"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional"

    gnre20_campoAdicional_camposAdicionais_id = fields.Many2one(
        comodel_name="gnre.20.camposadicionais",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_obrigatorio = fields.Selection(
        TSIMNAO, string="obrigatorio", xsd_required=True, xsd_type="tns:TSimNao"
    )

    gnre20_codigo = fields.Many2one(
        comodel_name="gnre.20.codigo", string="codigo", xsd_required=True
    )

    gnre20_tipo = fields.Many2one(
        comodel_name="gnre.20.tipo", string="tipo", xsd_required=True
    )

    gnre20_tamanho = fields.Integer(string="tamanho", xsd_type="int")

    gnre20_casasDecimais = fields.Integer(string="casasDecimais", xsd_type="int")

    gnre20_titulo = fields.Char(
        string="titulo", xsd_required=True, xsd_type="tns:TString"
    )

    gnre20_versoesXmlCampoAdicional = fields.Many2one(
        comodel_name="gnre.20.versoesxmlcampoadicional",
        string="Para cada Campo Adicional da Receita",
        xsd_required=True,
        help=(
            "Para cada Campo Adicional da Receita, as versões (do XML) que o\nexibirão."
        ),
    )

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_required=True, xsd_type="tns:TCamposGNRE"
    )


class Codigo(models.AbstractModel):
    _description = "codigo"
    _name = "gnre.20.codigo"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.Codigo"

    gnre20_value = fields.Integer(string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_type="tns:TCamposGNRE"
    )


class Tipo(models.AbstractModel):
    _description = "tipo"
    _name = "gnre.20.tipo"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.Tipo"

    gnre20_value = fields.Selection(TTIPOCAMPOEXTRA, string="value", xsd_required=True)

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE, string="campo", xsd_type="tns:TCamposGNRE"
    )


class VersoesXmlCampoAdicional(models.AbstractModel):
    """Para cada Campo Adicional da Receita, as versões (do XML) que o
    exibirão."""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.versoesxmlcampoadicional"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.VersoesXmlCampoAdicional"  # noqa: E501


class TiposGnre(models.AbstractModel):
    _description = "tiposGnre"
    _name = "gnre.20.tiposgnre"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.Receitas.Receita.TiposGnre"


class VersoesXml(models.AbstractModel):
    _description = "versoesXml"
    _name = "gnre.20.versoesxml"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.VersoesXml"


class QtdMaximas(models.AbstractModel):
    _description = "qtdMaximas"
    _name = "gnre.20.qtdmaximas"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.QtdMaximas"

    gnre20_guiasPorLote = fields.Char(string="guiasPorLote", xsd_type="tns:TString")

    gnre20_itensPorGuia = fields.Char(string="itensPorGuia", xsd_type="tns:TString")

    gnre20_itensPorLote = fields.Char(string="itensPorLote", xsd_type="tns:TString")

    gnre20_qtdConsultas = fields.Char(string="qtdConsultas", xsd_type="tns:TString")


class TiposGnreDaUf(models.AbstractModel):
    _description = "tiposGnreDaUF"
    _name = "gnre.20.tiposgnredauf"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.TiposGnreDaUf"


class EnderecoObr(models.AbstractModel):
    """Indicador de obrigatoriedade de preenchimento do campo Endereco quando o
    Emitente for identificado por CNPJ ou CPF."""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.enderecoobr"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconfigUf.EnderecoObr"

    gnre20_emitCpf = fields.Selection(
        TSIMNAO, string="emitCpf", xsd_required=True, xsd_type="tns:TSimNao"
    )

    gnre20_emitCnpj = fields.Selection(
        TSIMNAO, string="emitCnpj", xsd_required=True, xsd_type="tns:TSimNao"
    )
