# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

from odoo import fields, models

from .tipos_basico_gnre_v1_00 import (
    TSIMNAO,
    TUF,
)

__NAMESPACE__ = "http://www.gnre.pe.gov.br"

TCONSULTACONFIGUF_AMBIENTE = [
    ("1", "1"),
    ("2", "2"),
]


class TconsultaConfigUf(models.AbstractModel):
    _description = "TConsultaConfigUf"
    _name = "gnre.20.tconsultaconfiguf"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconsultaConfigUf"

    gnre20_ambiente = fields.Selection(
        TCONSULTACONFIGUF_AMBIENTE, string="ambiente", xsd_required=True
    )

    gnre20_uf = fields.Selection(
        TUF, string="uf", xsd_required=True, xsd_type="tns:TUf"
    )

    gnre20_receita = fields.Many2one(
        comodel_name="gnre.20.tconsultaconfiguf_receita", string="receita"
    )

    gnre20_tiposGnre = fields.Selection(
        TSIMNAO, string="tiposGnre", xsd_type="tns:TSimNao"
    )


class TconsultaConfigUfReceita(models.AbstractModel):
    _description = "receita"
    _name = "gnre.20.tconsultaconfiguf_receita"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconsultaConfigUf.Receita"

    gnre20_value = fields.Char(string="value", xsd_required=True)

    gnre20_courier = fields.Selection(TSIMNAO, string="courier", xsd_type="tns:TSimNao")
