# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

__NAMESPACE__ = "http://www.gnre.pe.gov.br"

# tipoGnre
TDADOSGNRE_TIPOGNRE = [
    ("0", "GNRE Simples"),
    ("1", "GNRE Multiplos Doc. de Origem"),
    ("2", "GNRE Multiplas Receitas"),
]

# tipoGnre
DADOS_TIPOGNRE = [
    ("0", "GNRE Simples"),
    ("1", "GNRE Multiplos Doc. de Origem"),
    ("2", "GNRE Multiplas Receitas"),
]

# tipoGnre
GUIA_TIPOGNRE = [
    ("0", "GNRE Simples"),
    ("1", "GNRE Multiplos Doc. de Origem"),
    ("2", "GNRE Multiplas Receitas"),
]

# Indicador do
# Periodo: 0 –
# mensal; 1 –
# 1a.
# quinzena; 2
# – 2a.
# quinzena; 3
# – 1o.
# decêndio; 4
# – 2o.
# decêndio; 5
# – 3o.
# decêndio;
REFERENCIA_PERIODO = [
    ("0", "0"),
    ("1", "1"),
    ("2", "2"),
    ("3", "3"),
    ("4", "4"),
    ("5", "5"),
]

VALOR_TIPO = [
    ("11", "11"),
    ("12", "12"),
    ("21", "21"),
    ("22", "22"),
    ("31", "31"),
    ("32", "32"),
    ("41", "41"),
    ("42", "42"),
    ("51", "51"),
    ("52", "52"),
]
