# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

import textwrap

from odoo import fields, models

from .tipos_basico_gnre_v1_00 import TUF

__NAMESPACE__ = "http://www.gnre.pe.gov.br"

# Tipo da Consulta.
# C: Consulta por codigo de barras
# N: Consulta por numero controle
# D: Consulta por documento origem
# CD: Consulta por codigo de barras mais documento de origem
# ND: Consulta por numero de controle mais documento de origem
# CR: Consulta por codigo de barras mais codigo da receita
# NR: Consulta por numero de controle mais codigo da receita
CONSULTA_TIPOCONSULTA = [
    ("C", "C"),
    ("N", "N"),
    ("D", "D"),
    ("CD", "CD"),
    ("ND", "ND"),
    ("CR", "CR"),
    ("NR", "NR"),
]


class TloteConsultaGnre(models.AbstractModel):
    _description = "TLote_ConsultaGNRE"
    _name = "gnre.20.tloteconsultagnre"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TloteConsultaGnre"

    gnre20_consulta = fields.One2many(
        "gnre.20.consulta", "gnre20_consulta_TLote_ConsultaGNRE_id", string="consulta"
    )

    gnre20_versao = fields.Char(string="versao", xsd_required=True)


class Consulta(models.AbstractModel):
    _description = "consulta"
    _name = "gnre.20.consulta"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TloteConsultaGnre.Consulta"

    gnre20_consulta_TLote_ConsultaGNRE_id = fields.Many2one(
        comodel_name="gnre.20.tloteconsultagnre",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_uf = fields.Selection(
        TUF, string="Sigla da UF", xsd_required=True, xsd_type="TUf"
    )

    gnre20_emitenteId = fields.Many2one(
        comodel_name="gnre.20.tidentificacao2",
        string="Identificação do emitente",
        xsd_type="TIdentificacao2",
        help="Identificação do emitente. CPF, CNPJ ou IE.",
    )

    gnre20_codBarras = fields.Char(
        string="Código de barras da GNRE",
        help="Código de barras da GNRE. 44 ou 48 dígitos.",
    )

    gnre20_numControle = fields.Char(string="Número de Controle da GNRE")

    gnre20_docOrigem = fields.Many2one(
        comodel_name="gnre.20.docorigem", string="Número e tipo do Documento de Origem"
    )

    gnre20_idConsulta = fields.Char(
        string="Texto livre para ser utilizado",
        help=("Texto livre para ser utilizado como identificador da consulta no lote"),
    )

    gnre20_tipoConsulta = fields.Selection(
        CONSULTA_TIPOCONSULTA,
        string="Tipo da Consulta",
        xsd_required=True,
        help=(
            "Tipo da Consulta. \nC: Consulta por codigo de barras\nN: Consulta"
            " por numero controle\nD: Consulta por documento origem\nCD: "
            "Consulta por codigo de barras mais documento de origem\nND: "
            "Consulta por numero de controle mais documento de origem\nCR: "
            "Consulta por codigo de barras mais codigo da receita\nNR: "
            "Consulta por numero de controle mais codigo da receita"
        ),
    )


class DocOrigem(models.AbstractModel):
    "Número e tipo do Documento de Origem."

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.docorigem"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TloteConsultaGnre.Consulta.DocOrigem"

    gnre20_value = fields.Char(string="value", xsd_required=True)

    gnre20_tipo = fields.Char(string="tipo", xsd_required=True)
