# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

from odoo import fields, models

__NAMESPACE__ = "http://www.gnre.pe.gov.br"

TCONSLOTE_GNRE_AMBIENTE = [
    ("1", "1"),
    ("2", "2"),
]

TCONSLOTE_GNRE_INCLUIRARQUIVOPAGAMENTO = [
    ("S", "S"),
    ("N", "N"),
]

TCONSLOTE_GNRE_INCLUIRNOTICIAS = [
    ("S", "S"),
    ("N", "N"),
]

TCONSLOTE_GNRE_INCLUIRPDFGUIAS = [
    ("S", "S"),
    ("N", "N"),
]


class TconsLoteGnre(models.AbstractModel):
    _description = "TConsLote_GNRE"
    _name = "gnre.20.tconslotegnre"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TconsLoteGnre"

    gnre20_ambiente = fields.Selection(
        TCONSLOTE_GNRE_AMBIENTE, string="ambiente", xsd_required=True
    )

    gnre20_numeroRecibo = fields.Char(string="numeroRecibo", xsd_required=True)

    gnre20_incluirPDFGuias = fields.Selection(
        TCONSLOTE_GNRE_INCLUIRPDFGUIAS,
        string="indica se o pdf",
        help=(
            "indica se o pdf (string na base64) das guias processadas com "
            "sucesso deve ser incluido no retorno da consulta do lote"
        ),
    )

    gnre20_incluirArquivoPagamento = fields.Selection(
        TCONSLOTE_GNRE_INCLUIRARQUIVOPAGAMENTO,
        string="indica se o arquivo de pagamento",
        help=(
            "indica se o arquivo de pagamento, com as guias processadas com "
            "sucesso, deve ser incluido no retorno da consulta do lote"
        ),
    )

    gnre20_incluirNoticias = fields.Selection(
        TCONSLOTE_GNRE_INCLUIRNOTICIAS,
        string="incluirNoticias",
        help=(
            "indica se o arquivo de pagamento, com as guias processadas com "
            "sucesso, deve ser incluido no retorno da consulta do lote"
        ),
    )
