# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

from __future__ import annotations

import textwrap

from odoo import fields, models

from .dados_gnre_v1_00 import C05_REFERENCIA_PERIODO
from .dados_gnre_v2_00 import (
    DADOS_TIPOGNRE,
    REFERENCIA_PERIODO,
    VALOR_TIPO,
)
from .tipos_basico_gnre_v1_00 import (
    TIDENTIFICACAO,
    TMES,
    TTIPOCAMPOEXTRA,
    TUF,
)
from .tipos_basico_gnre_v2_00 import (
    TCAMPOSGNRE2,
)

__NAMESPACE__ = "http://www.gnre.pe.gov.br"

TRETORNO_GNRE_SITUACAO = [
    ("0", "0"),
    ("1", "1"),
    ("2", "2"),
    ("3", "3"),
]


class TretornoGnre(models.AbstractModel):
    _description = "TRetorno_GNRE"
    _name = "gnre.20.tretornognre"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre"

    gnre20_dados = fields.One2many(
        "gnre.20.dados", "gnre20_dados_TRetorno_GNRE_id", string="dados"
    )

    gnre20_situacao = fields.Selection(
        TRETORNO_GNRE_SITUACAO,
        string="Indica o status do processamento da guia",
        xsd_required=True,
        help=(
            "Indica o status do processamento da guia \n0 – Gerada com "
            "sucesso; \n1 – Erro de\tpreenchimento; \n2 – Erro de "
            "comunicação;\n3 - Pendencia de tempo de processamento"
        ),
    )

    gnre20_erros = fields.Many2one(
        comodel_name="gnre.20.erros", string="Erros no processamento da GNRE"
    )

    gnre20_linhaDigitavel = fields.Char(string="Linha digitável gerada nas UFs")

    gnre20_qrcodePayload = fields.Char(
        string="String que sera utilizada para a geracao",
        help=("String que sera utilizada para a geracao do QRCode do pagamento PIX."),
    )

    gnre20_dataEmissao = fields.Date(
        string="Data de emissão da guia.",
        xsd_type="TData",
        help="Data de emissão da guia. (Formato\nAAAA-MM-DD)",
    )

    gnre20_horaEmissao = fields.Char(
        string="Hora de emissão da guia",
        xsd_type="xs:time",
        help="Hora de emissão da guia. (Formato HH:MM:SS)",
    )

    gnre20_versao = fields.Char(string="versao", xsd_required=True)


class Dados(models.AbstractModel):
    _description = "dados"
    _name = "gnre.20.dados"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados"

    gnre20_dados_TRetorno_GNRE_id = fields.Many2one(
        comodel_name="gnre.20.tretornognre",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_ufFavorecida = fields.Selection(
        TUF,
        string="Código da UF Favorecida",
        help="Código da UF Favorecida. (Utilizar a Tabela do\nIBGE)",
    )

    gnre20_tipoGnre = fields.Selection(
        DADOS_TIPOGNRE,
        string="0 - GNRE Simples",
        help=(
            "0 - GNRE Simples\n1 - GNRE Multiplos Doc. de Origem\n2 - GNRE "
            "Multiplas Receitas"
        ),
    )

    gnre20_contribuinteEmitente = fields.Many2one(
        comodel_name="gnre.20.tretornognre_contribuinteemitente",
        string="contribuinteEmitente",
    )

    gnre20_itensGNRE = fields.Many2one(
        comodel_name="gnre.20.tretornognre_itensgnre", string="itensGNRE"
    )

    gnre20_valorGNRE = fields.Char(string="valorGNRE")

    gnre20_dataPagamento = fields.Char(
        string="Data prevista",
        help="Data prevista de pagamento informada pelo\ncontribuinte.",
    )

    gnre20_identificadorGuia = fields.Char(string="identificadorGuia")

    gnre20_dataLimitePagamento = fields.Date(
        string="Data máxima que o banco pode",
        choice="dados",
        xsd_choice_required=True,
        xsd_type="TData",
        help=(
            "Data máxima que o banco pode\nreceber o pagamento, que\nestará "
            "impressa na guia e no\ncódigo de barras."
        ),
    )

    gnre20_informacoesComplementares = fields.Many2one(
        comodel_name="gnre.20.tretornognre_informacoescomplementares",
        string="Informação complementar",
        choice="dados",
        xsd_choice_required=True,
        help="Informação complementar a\nser impressa na guia.",
    )

    gnre20_nossoNumero = fields.Char(
        string="Número interno da guia",
        choice="dados",
        xsd_choice_required=True,
        help="Número interno da guia\ngerado pela UF",
    )

    gnre20_dadosPagamento = fields.Many2one(
        comodel_name="gnre.20.dadospagamento",
        string="dadosPagamento",
        choice="dados",
        xsd_choice_required=True,
    )

    gnre20_c01_UfFavorecida = fields.Selection(
        TUF,
        string="Sigla da UF Favorecida",
        help="Sigla da UF Favorecida. (Utilizar a Tabela do IBGE)",
    )

    gnre20_c02_receita = fields.Char(string="Código da Receita")

    gnre20_c25_detalhamentoReceita = fields.Char(
        string="Código do Detalhamento da Receita"
    )

    gnre20_c26_produto = fields.Char(string="Código do Produto")

    gnre20_c27_tipoIdentificacaoEmitente = fields.Selection(
        TIDENTIFICACAO,
        string="Código do Tipo de Identificação",
        help="Código do Tipo de Identificação do Emitente:",
    )

    gnre20_c03_idContribuinteEmitente = fields.Many2one(
        comodel_name="gnre.20.tretornognre_c03idcontribuinteemitente",
        string="Número do Documento de Identificação",
        help=("Número do Documento de Identificação do\nContribuinte Emitente."),
    )

    gnre20_c28_tipoDocOrigem = fields.Char(
        string="Código do Tipo de Documento de Origem"
    )

    gnre20_c04_docOrigem = fields.Char(string="Número do Documento de Origem")

    gnre20_c06_valorPrincipal = fields.Char(string="Valor Original da Guia")

    gnre20_c07_atualizacaoMonetaria = fields.Monetary(
        string="Atualização monetária",
        choice="dados",
        xsd_choice_required=True,
        xsd_type="TDec_1502",
        currency_field="brl_currency_id",
        help=("Atualização monetária do\nvalor original até a data de\npagamento."),
    )

    gnre20_c08_juros = fields.Monetary(
        string="Valor de juros sobre o valor",
        choice="dados",
        xsd_choice_required=True,
        xsd_type="TDec_1502",
        currency_field="brl_currency_id",
        help=("Valor de juros sobre o valor\noriginal até a data de\npagamento."),
    )

    gnre20_c09_multa = fields.Monetary(
        string="Valor da multa aplicada",
        choice="dados",
        xsd_choice_required=True,
        xsd_type="TDec_1502",
        currency_field="brl_currency_id",
        help="Valor da multa aplicada\nsobre o valor original.",
    )

    gnre20_c10_valorTotal = fields.Char(
        string="Valor total da guia",
        help="Valor total da guia (valor original +\nencargos).",
    )

    gnre20_c14_dataVencimento = fields.Char(string="Data de vencimento da guia")

    gnre20_c29_dataLimitePagamento = fields.Date(
        string="c29_dataLimitePagamento",
        choice="dados",
        xsd_choice_required=True,
        xsd_type="TData",
        help=(
            "Data máxima que o banco pode\nreceber o pagamento, que\nestará "
            "impressa na guia e no\ncódigo de barras."
        ),
    )

    gnre20_c15_convenio = fields.Char(string="Número do convênio")

    gnre20_c16_razaoSocialEmitente = fields.Char(
        string="Nome da firma ou a Razão Social",
        help="Nome da firma ou a Razão Social do\nContribuinte.",
    )

    gnre20_c17_inscricaoEstadualEmitente = fields.Char(
        string="Inscrição Estadual do Contribuinte na UF",
        help="Inscrição Estadual do Contribuinte na UF\nfavorecida.",
    )

    gnre20_c18_enderecoEmitente = fields.Char(string="Endereço do Contribuinte")

    gnre20_c19_municipioEmitente = fields.Char(
        string="Código do Município de localização",
        help=(
            "Código do Município de localização do\nContribuinte.(Utilizar a "
            "tabela do IBGE)"
        ),
    )

    gnre20_c20_ufEnderecoEmitente = fields.Selection(
        TUF, string="Código da UF do Contribuinte"
    )

    gnre20_c21_cepEmitente = fields.Char(string="CEP do Contribuinte")

    gnre20_c22_telefoneEmitente = fields.Char(string="Telefone do contribuinte")

    gnre20_c34_tipoIdentificacaoDestinatario = fields.Selection(
        TIDENTIFICACAO, string="Tipo de Identificação do Destinatário"
    )

    gnre20_c35_idContribuinteDestinatario = fields.Many2one(
        comodel_name="gnre.20.tretornognre_c35idcontribuintedestinatario",
        string="c35_idContribuinteDestinatario",
        help=("Número do Documento de Identificação do\nContribuinte Destinatário."),
    )

    gnre20_c36_inscricaoEstadualDestinatario = fields.Char(
        string="c36_inscricaoEstadualDestinatario",
        help="Inscrição Estadual do Contribuinte na UF\nfavorecida.",
    )

    gnre20_c37_razaoSocialDestinatario = fields.Char(
        string="c37_razaoSocialDestinatario",
        help="Nome da firma ou a Razão Social do\nContribuinte.",
    )

    gnre20_c38_municipioDestinatario = fields.Char(
        string="Código do Município de Destino",
        help="Código do Município de Destino.(Utilizar a\ntabela do IBGE)",
    )

    gnre20_c23_informacoes = fields.Char(
        string="c23_informacoes",
        choice="dados",
        xsd_choice_required=True,
        help="Informação complementar a\nser impressa na guia.",
    )

    gnre20_c30_nossoNumero = fields.Char(
        string="Número interno da guia (c30_nossoNumero)",
        choice="dados",
        xsd_choice_required=True,
        help="Número interno da guia\ngerado pela UF",
    )

    gnre20_c24_autenticacao = fields.Char(
        string="Autenticação bancária",
        choice="dados",
        xsd_choice_required=True,
        help="Autenticação bancária do\npagamento da guia.",
    )

    gnre20_c31_banco = fields.Char(
        string="Código do Banco onde",
        choice="dados",
        xsd_choice_required=True,
        help="Código do Banco onde foi\npaga a guia.",
    )

    gnre20_c32_agencia = fields.Char(
        string="Código da Agência bancária",
        choice="dados",
        xsd_choice_required=True,
        help="Código da Agência bancária\nonde foi paga a guia.",
    )

    gnre20_c33_dataPagamento = fields.Char(
        string="Qdo for Envio",
        help=(
            "Qdo for Envio:\n           \t\t\t\t\t- Data prevista de pagamento"
            " informada pelo contribuinte.\n           \t\t\t\tQdo Retorno:\n"
            "           \t\t\t\t\t- Quando for uma validação retorna a Data "
            "prevista de pagamento informada pelo "
            "contribuinte.\t\t\t\t\t\t\n\t\t\t\t\t\t\t- Quando for uma "
            "consulta da guia retorna a Data do pagamento da guia no banco."
        ),
    )

    gnre20_c05_referencia = fields.Many2one(
        comodel_name="gnre.20.tretornognre_c05referencia", string="c05_referencia"
    )

    gnre20_c39_camposExtras = fields.Many2one(
        comodel_name="gnre.20.tretornognre_c39camposextras", string="c39_camposExtras"
    )

    gnre20_c42_identificadorGuia = fields.Char(string="c42_identificadorGuia")

    gnre20_dataEmissaoDados = fields.Date(
        string="Este campo deve ser preenchido",
        xsd_type="TData",
        help=(
            "Este campo deve ser preenchido quando do retorno de uma consulta "
            "de Guia por Documento de Origem, ocasião em que pode ocorrer a "
            "incidência de mais de uma Guia no mesmo retorno."
        ),
    )

    gnre20_horaEmissaoDados = fields.Char(
        string="horaEmissaoDados",
        xsd_type="xs:time",
        help=(
            "Este campo deve ser preenchido quando do retorno de uma consulta "
            "de Guia por Documento de Origem, ocasião em que pode ocorrer a "
            "incidência de mais de uma Guia no mesmo retorno."
        ),
    )

    gnre20_versao = fields.Char(string="versao", xsd_required=True)


class TretornoGnreInformacoesComplementares(models.AbstractModel):
    """Informação complementar a
    ser impressa na guia."""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.tretornognre_informacoescomplementares"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.InformacoesComplementares"

    gnre20_informacao = fields.Char(string="informacao")


class DadosPagamento(models.AbstractModel):
    _description = "dadosPagamento"
    _name = "gnre.20.dadospagamento"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.DadosPagamento"

    gnre20_data = fields.Char(
        string="Quando for uma validacao",
        xsd_type="TDataHora",
        help=(
            "Quando for uma validacao, retorna a Data prevista de pagamento "
            "informada pelo contribuinte. Quando for uma consulta da guia "
            "retorna a Data do pagamento da guia no banco."
        ),
    )

    gnre20_autenticacao = fields.Char(
        string="Autenticacao bancaria do pagamento",
        help="Autenticacao bancaria do pagamento da\tguia.",
    )

    gnre20_banco = fields.Char(string="Codigo do Banco onde foi paga a guia")

    gnre20_agencia = fields.Char(
        string="Código da Agencia bancaria onde foi paga",
        help="Código da Agencia bancaria onde foi paga a guia.",
    )

    gnre20_txId = fields.Char(string="Identificador da transacao PIX")

    gnre20_e2eId = fields.Char(string="Identificador fim a fim da transacao PIX")

    gnre20_pspPagador = fields.Char(
        string="Raiz do CNPJ",
        help=(
            "Raiz do CNPJ da instituicao financeira onde o contribuinte "
            "efetuou o pagamento da GNRE."
        ),
    )


class TretornoGnreContribuinteEmitente(models.AbstractModel):
    _description = "contribuinteEmitente"
    _name = "gnre.20.tretornognre_contribuinteemitente"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.ContribuinteEmitente"

    gnre20_identificacao = fields.Many2one(
        comodel_name="gnre.20.tidentificacao2",
        string="identificacao",
        xsd_required=True,
        xsd_type="TIdentificacao2",
    )

    gnre20_razaoSocial = fields.Char(string="razaoSocial")

    gnre20_endereco = fields.Char(string="Endereço do Contribuinte")

    gnre20_municipio = fields.Char(
        string="Código do Município de localização",
        xsd_type="TCodMunIBGE",
        help=(
            "Código do Município de localização\ndo Contribuinte.(Utilizar a "
            "tabela\ndo IBGE)"
        ),
    )

    gnre20_uf = fields.Selection(
        TUF, string="Código da UF do Contribuinte", xsd_type="TUf"
    )

    gnre20_cep = fields.Char(string="CEP do Contribuinte")

    gnre20_telefone = fields.Char(string="Telefone do contribuinte")


class TretornoGnreItensGnre(models.AbstractModel):
    _description = "itensGNRE"
    _name = "gnre.20.tretornognre_itensgnre"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.ItensGnre"

    gnre20_item = fields.One2many(
        "gnre.20.tretornognre_item", "gnre20_item_itensGNRE_id", string="item"
    )


class TretornoGnreItem(models.AbstractModel):
    _description = "item"
    _name = "gnre.20.tretornognre_item"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.ItensGnre.Item"

    gnre20_item_itensGNRE_id = fields.Many2one(
        comodel_name="gnre.20.tretornognre_itensgnre",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_receita = fields.Char(string="Código da Receita")

    gnre20_detalhamentoReceita = fields.Char(
        string="Código do Detalhamento", help="Código do Detalhamento\nda Receita."
    )

    gnre20_documentoOrigem = fields.Many2one(
        comodel_name="gnre.20.tretornognre_documentoorigem",
        string="Número do Documento",
        help="Número do Documento de\nOrigem.",
    )

    gnre20_produto = fields.Char(string="Código do Produto")

    gnre20_referencia = fields.Many2one(
        comodel_name="gnre.20.tretornognre_referencia", string="referencia"
    )

    gnre20_dataVencimento = fields.Date(
        string="Data de vencimento",
        xsd_type="TData",
        help="Data de vencimento da\nguia.",
    )

    gnre20_valor = fields.One2many(
        "gnre.20.tretornognre_valor", "gnre20_valor_item_id", string="valor"
    )

    gnre20_convenio = fields.Char(string="Número do convênio")

    gnre20_contribuinteDestinatario = fields.Many2one(
        comodel_name="gnre.20.tretornognre_contribuintedestinatario",
        string="contribuinteDestinatario",
    )

    gnre20_camposExtras = fields.Many2one(
        comodel_name="gnre.20.tretornognre_camposextras", string="camposExtras"
    )

    gnre20_numeroControle = fields.Char(string="numeroControle")

    gnre20_numeroControleFecp = fields.Char(string="numeroControleFecp")


class TretornoGnreDocumentoOrigem(models.AbstractModel):
    """Número do Documento de
    Origem."""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.tretornognre_documentoorigem"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.ItensGnre.Item.DocumentoOrigem"

    gnre20_value = fields.Char(string="value", xsd_required=True)

    gnre20_tipo = fields.Char(string="tipo", xsd_required=True)


class TretornoGnreReferencia(models.AbstractModel):
    """Informações de
    período de apuração"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.tretornognre_referencia"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.ItensGnre.Item.Referencia"

    gnre20_periodo = fields.Selection(
        REFERENCIA_PERIODO,
        string="Indicador",
        help=(
            "Indicador do\nPeriodo: 0 –\nmensal; 1 –\n1a.\nquinzena; 2\n– "
            "2a.\nquinzena; 3\n– 1o.\ndecêndio; 4\n– 2o.\ndecêndio; 5\n– "
            "3o.\ndecêndio;"
        ),
    )

    gnre20_mes = fields.Selection(
        TMES, string="Mês", xsd_type="TMes", help="Mês de\nreferência\nda Apuração"
    )

    gnre20_ano = fields.Char(
        string="Ano", xsd_type="TAno", help="Ano de\nreferência\nda Apuração"
    )

    gnre20_parcela = fields.Char(
        string="Parcela", help="Parcela de\nreferência\nda Apuração"
    )


class TretornoGnreValor(models.AbstractModel):
    _description = "valor"
    _name = "gnre.20.tretornognre_valor"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.ItensGnre.Item.Valor"

    gnre20_valor_item_id = fields.Many2one(
        comodel_name="gnre.20.tretornognre_item",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_value = fields.Char(string="value", xsd_required=True)

    gnre20_tipo = fields.Selection(
        VALOR_TIPO,
        string="11",
        xsd_required=True,
        help=(
            "11 -\nValor\nPrincipal\nICMS 12\n- Valor\nPrincipal\nFundo "
            "de\nPobreza\n(FP) 21\n- Valor\nTotal\nICMS 22\n- Valor\nTotal "
            "FP\n31 -\nValor\nMulta\nICMS 32\n- Valor\nMulta FP\n41 "
            "-\nValor\nJuros\nICMS 42\n- Valor\nJuros FP\n51 "
            "-\nValor\nAtualização\nMonetaria\nICMS 52\n- "
            "Valor\nAtualização\nMonetaria\nFP"
        ),
    )


class TretornoGnreContribuinteDestinatario(models.AbstractModel):
    _description = "contribuinteDestinatario"
    _name = "gnre.20.tretornognre_contribuintedestinatario"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.ItensGnre.Item.ContribuinteDestinatario"

    gnre20_identificacao = fields.Many2one(
        comodel_name="gnre.20.tidentificacao2",
        string="identificacao",
        xsd_required=True,
        xsd_type="TIdentificacao2",
    )

    gnre20_razaoSocial = fields.Char(
        string="Nome", help="Nome da\nfirma ou a\nRazão Social\ndo\nContribuinte."
    )

    gnre20_municipio = fields.Char(
        string="Código",
        xsd_type="TCodMunIBGE",
        help=("Código do\nMunicípio de\nDestino.(Utilizar\na tabela do\nIBGE)"),
    )


class TretornoGnreCamposExtras(models.AbstractModel):
    _description = "camposExtras"
    _name = "gnre.20.tretornognre_camposextras"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.ItensGnre.Item.CamposExtras"

    gnre20_campoExtra = fields.One2many(
        "gnre.20.tretornognre_item_campoextra",
        "gnre20_campoExtra_camposExtras_id",
        string="campoExtra",
    )


class TretornoGnreItemCampoExtra(models.AbstractModel):
    _description = "campoExtra"
    _name = "gnre.20.tretornognre_item_campoextra"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.ItensGnre.Item.CamposExtras.CampoExtra"

    gnre20_campoExtra_camposExtras_id = fields.Many2one(
        comodel_name="gnre.20.tretornognre_camposextras",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_codigo = fields.Integer(
        string="codigo", xsd_required=True, xsd_type="xs:int"
    )

    gnre20_valor = fields.Char(string="valor", xsd_required=True)


class TretornoGnreC03IdContribuinteEmitente(models.AbstractModel):
    """Número do Documento de Identificação do
    Contribuinte Emitente."""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.tretornognre_c03idcontribuinteemitente"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.C03IdContribuinteEmitente"

    gnre20_CNPJ = fields.Char(
        string="Número do CNPJ do Contribuinte",
        choice="c03_idcontribuinteemitente",
        xsd_choice_required=True,
        xsd_type="TCnpj",
    )

    gnre20_CPF = fields.Char(
        string="Número do CPF do Contribuinte",
        choice="c03_idcontribuinteemitente",
        xsd_choice_required=True,
        xsd_type="TCpf",
    )


class TretornoGnreC35IdContribuinteDestinatario(models.AbstractModel):
    """Número do Documento de Identificação do
    Contribuinte Destinatário."""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.tretornognre_c35idcontribuintedestinatario"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.C35IdContribuinteDestinatario"

    gnre20_CNPJ = fields.Char(
        string="Número do CNPJ do Contribuinte",
        choice="c35_idcontribuintedestinatario",
        xsd_choice_required=True,
        xsd_type="TCnpj",
        help="Número do CNPJ do Contribuinte\nDestinatário",
    )

    gnre20_CPF = fields.Char(
        string="Número do CPF do Contribuinte",
        choice="c35_idcontribuintedestinatario",
        xsd_choice_required=True,
        xsd_type="TCpf",
        help="Número do CPF do Contribuinte\nDestinatário",
    )


class TretornoGnreC05Referencia(models.AbstractModel):
    "Informações de período de apuração"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.tretornognre_c05referencia"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.C05Referencia"

    gnre20_periodo = fields.Selection(
        C05_REFERENCIA_PERIODO,
        string="Indicador do Periodo: 0 –",
        help=(
            "Indicador do Periodo: 0 –\nmensal; 1 – 1a. quinzena; 2 –\n2a. "
            "quinzena; 3 – 1o. decêndio;\n4 – 2o. decêndio; 5 – 3o.\ndecêndio;"
        ),
    )

    gnre20_mes = fields.Selection(
        TMES, string="Mês de referência da Apuração", xsd_type="TMes"
    )

    gnre20_ano = fields.Char(string="Ano de referência da Apuração", xsd_type="TAno")

    gnre20_parcela = fields.Char(
        string="Parcela de referência", help="Parcela de referência da\nApuração"
    )


class TretornoGnreC39CamposExtras(models.AbstractModel):
    _description = "c39_camposExtras"
    _name = "gnre.20.tretornognre_c39camposextras"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.C39CamposExtras"

    gnre20_campoExtra = fields.One2many(
        "gnre.20.tretornognre_campoextra",
        "gnre20_campoExtra_c39_camposExtras_id",
        string="campoExtra",
    )


class TretornoGnreCampoExtra(models.AbstractModel):
    _description = "campoExtra"
    _name = "gnre.20.tretornognre_campoextra"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Dados.C39CamposExtras.CampoExtra"

    gnre20_campoExtra_c39_camposExtras_id = fields.Many2one(
        comodel_name="gnre.20.tretornognre_c39camposextras",
        xsd_implicit=True,
        ondelete="cascade",
        index=True,
    )
    gnre20_codigo = fields.Integer(
        string="codigo", xsd_required=True, xsd_type="xs:int"
    )

    gnre20_tipo = fields.Selection(
        TTIPOCAMPOEXTRA, string="tipo", xsd_required=True, xsd_type="TTipoCampoExtra"
    )

    gnre20_valor = fields.Char(string="valor", xsd_required=True)


class Erros(models.AbstractModel):
    "Erros no processamento da GNRE."

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "gnre.20.erros"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Erros"

    gnre20_erro = fields.One2many(
        "gnre.20.erro",
        "gnre20_erro_erros_id",
        string="erro",
        choice="erros",
        xsd_choice_required=True,
    )


class Erro(models.AbstractModel):
    _description = "erro"
    _name = "gnre.20.erro"
    _inherit = "spec.mixin.gnre"
    _binding_type = "TretornoGnre.Erros.Erro"

    gnre20_erro_erros_id = fields.Many2one(
        comodel_name="gnre.20.erros", xsd_implicit=True, ondelete="cascade", index=True
    )
    gnre20_item = fields.Integer(
        string="Ordem do item onde",
        xsd_type="xs:integer",
        help="Ordem do item onde\ntem campo com erro\nde validação",
    )

    gnre20_campo = fields.Selection(
        TCAMPOSGNRE2,
        string="Campo que apresentou",
        xsd_type="TCamposGNRE2",
        help="Campo que apresentou\nerro durante o\nprocessamento.",
    )

    gnre20_mensagem = fields.Char(
        string="Mensagem",
        xsd_required=True,
        xsd_type="xs:string",
        help="Mensagem com o\nmotivo do erro\ngerado para o campo.",
    )
