# -*- coding: utf-8 -*-
# Copyright 2019 KMEE
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

MODELO_FISCAL_NFE = '55'
MODELO_FISCAL_NFCE = '65'
MODELO_FISCAL_NFSE = 'SE'
MODELO_FISCAL_CFE = '59'
MODELO_FISCAL_CUPOM_FISCAL_ECF = '2D'
MODELO_FISCAL_CTE = '57'
MODELO_FISCAL_RL = 'RL'

MODELO_FISCAL_EMISSAO_PRODUTO = (
    MODELO_FISCAL_NFE,
    MODELO_FISCAL_NFCE,
    MODELO_FISCAL_CFE,
    MODELO_FISCAL_CUPOM_FISCAL_ECF,
)
MODELO_FISCAL_EMISSAO_SERVICO = (
    MODELO_FISCAL_NFE,
    MODELO_FISCAL_NFCE,
    MODELO_FISCAL_NFSE,
    MODELO_FISCAL_RL,
)

AUTORIZADO = ('100', '150')
DENEGADO = ('110', '301', '302')
LOTE_RECEBIDO = ['103']
LOTE_PROCESSADO = ['104']
LOTE_EM_PROCESSAMENTO = ['105']

CANCELADO_DENTRO_PRAZO = ['135']
CANCELADO_FORA_PRAZO = ['155']

CANCELADO = CANCELADO_DENTRO_PRAZO + CANCELADO_FORA_PRAZO

AUTORIZADA_OU_DENEGADA = AUTORIZADO + DENEGADO
