# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

import textwrap

from odoo import fields, models

__NAMESPACE__ = "http://www.portalfiscal.inf.br/mdfe"

# Tipo do Componente
COMP_TPCOMP = [
    ("01", "Vale Pedágio"),
    ("02", "Impostos, taxas e contribuições"),
    ("03", "Despesas (bancárias, meios de pagamento, outras)"),
    ("99", "Outros"),
]

# Descrição do Evento - “Alteração Pagamento Serviço MDFe”
EVALTERACAOPAGTOSERVMDFE_DESCEVENTO = [
    ("Alteração Pagamento Serviço MDFe", "Alteração Pagamento Serviço MDFe"),
    ("Alteracao Pagamento Servico MDFe", "Alteracao Pagamento Servico MDFe"),
]

# Indicador para declarar concordância em antecipar o adiantamento
# Operação de transporte com utilização de veículos de frotas dedicadas ou
# fidelizadas.
# Preencher com “1” para indicar operação de transporte de alto desempenho,
# demais casos não informar a tag
INFPAG_INDANTECIPAADIANT = [
    ("1", "1"),
]

# Indicador da Forma de Pagamento
INFPAG_INDPAG = [
    ("0", "Pagamento à Vista"),
    ("1", "Pagamento à Prazo"),
]

# Tipo de Permissão em relação a antecipação das parcelas
INFPAG_TPANTECIP = [
    ("0", "Não permite antecipar"),
    ("1", "Permite antecipar as parcelas"),
    ("2", "Permite antecipar as parcelas mediante confirmação"),
]


class EvAlteracaoPagtoServMdfe(models.AbstractModel):
    """Schema XML de validação do evento de alteração do pagamento do serviçp
    de transporte 110118"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "mdfe.30.evalteracaopagtoservmdfe"
    _inherit = "spec.mixin.mdfe"
    _binding_type = "EvAlteracaoPagtoServMdfe"

    mdfe30_descEvento = fields.Selection(
        EVALTERACAOPAGTOSERVMDFE_DESCEVENTO,
        string="Descrição do Evento",
        xsd_required=True,
        help="Descrição do Evento - “Alteração Pagamento Serviço MDFe”",
    )

    mdfe30_nProt = fields.Char(
        string="Número do Protocolo de Status do MDF-e",
        xsd_required=True,
        xsd_type="TProt",
    )

    mdfe30_infPag = fields.One2many(
        "mdfe.30.evalteracaopagtoservmdfe_infpag",
        "mdfe30_infPag_evAlteracaoPagtoServMDFe_id",
        string="Informações do Pagamento do Frete",
    )


class EvAlteracaoPagtoServMdfeInfPag(models.AbstractModel):
    "Informações do Pagamento do Frete"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "mdfe.30.evalteracaopagtoservmdfe_infpag"
    _inherit = "spec.mixin.mdfe"
    _binding_type = "EvAlteracaoPagtoServMdfe.InfPag"

    mdfe30_infPag_evAlteracaoPagtoServMDFe_id = fields.Many2one(
        comodel_name="mdfe.30.evalteracaopagtoservmdfe",
        xsd_implicit=True,
        ondelete="cascade",
    )
    mdfe30_xNome = fields.Char(
        string="Razão social ou Nome do responsavel",
        help="Razão social ou Nome do responsavel pelo pagamento",
    )

    mdfe30_CPF = fields.Char(
        string="Número do CPF do responsável pelo pgto",
        choice="infpag",
        xsd_choice_required=True,
        xsd_type="TCpf",
        help=(
            "Número do CPF do responsável pelo pgto\nInformar os zeros não "
            "significativos."
        ),
    )

    mdfe30_CNPJ = fields.Char(
        string="Número do CNPJ do responsável pelo pgto",
        choice="infpag",
        xsd_choice_required=True,
        xsd_type="TCnpjOpc",
        help=(
            "Número do CNPJ do responsável pelo pgto\nInformar os zeros não "
            "significativos."
        ),
    )

    mdfe30_idEstrangeiro = fields.Char(
        string="Identificador do responsável pelo pgto",
        choice="infpag",
        xsd_choice_required=True,
        help=("Identificador do responsável pelo pgto em caso de ser estrangeiro"),
    )

    mdfe30_comp = fields.One2many(
        "mdfe.30.evalteracaopagtoservmdfe_comp",
        "mdfe30_Comp_infPag_id",
        string="Componentes do Pagamentoi do Frete",
    )

    mdfe30_vContrato = fields.Monetary(
        string="Valor Total do Contrato",
        xsd_required=True,
        xsd_type="TDec_1302",
        currency_field="brl_currency_id",
    )

    mdfe30_indPag = fields.Selection(
        INFPAG_INDPAG,
        string="Indicador da Forma",
        xsd_required=True,
        help=(
            "Indicador da Forma de Pagamento:0-Pagamento à Vista;1-Pagamento à Prazo;"
        ),
    )

    mdfe30_vAdiant = fields.Monetary(
        string="Valor do Adiantamento",
        xsd_type="TDec_1302",
        currency_field="brl_currency_id",
        help="Valor do Adiantamento (usar apenas em pagamento à Prazo",
    )

    mdfe30_indAntecipaAdiant = fields.Selection(
        INFPAG_INDANTECIPAADIANT,
        string="Indicador para declarar concordância",
        help=(
            "Indicador para declarar concordância em antecipar o "
            "adiantamento\nOperação de transporte com utilização de veículos "
            "de frotas dedicadas ou fidelizadas.\nPreencher com “1” para "
            "indicar operação de transporte de alto desempenho, demais casos "
            "não informar a tag"
        ),
    )

    mdfe30_infPrazo = fields.One2many(
        "mdfe.30.evalteracaopagtoservmdfe_infprazo",
        "mdfe30_infPrazo_infPag_id",
        string="Informações do pagamento a prazo",
        help=(
            "Informações do pagamento a prazo.\nInformar somente se indPag for à Prazo"
        ),
    )

    mdfe30_tpAntecip = fields.Selection(
        INFPAG_TPANTECIP,
        string="Tipo de Permissão em relação",
        help=(
            "Tipo de Permissão em relação a antecipação das parcelas\n0 - Não "
            "permite antecipar\n1 - Permite antecipar as parcelas\n2 - Permite"
            " antecipar as parcelas mediante confirmação"
        ),
    )

    mdfe30_infBanc = fields.Many2one(
        comodel_name="mdfe.30.evalteracaopagtoservmdfe_infbanc",
        string="Informações bancárias",
        xsd_required=True,
    )


class EvAlteracaoPagtoServMdfeComp(models.AbstractModel):
    "Componentes do Pagamentoi do Frete"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "mdfe.30.evalteracaopagtoservmdfe_comp"
    _inherit = "spec.mixin.mdfe"
    _binding_type = "EvAlteracaoPagtoServMdfe.InfPag.Comp"

    mdfe30_Comp_infPag_id = fields.Many2one(
        comodel_name="mdfe.30.evalteracaopagtoservmdfe_infpag",
        xsd_implicit=True,
        ondelete="cascade",
    )
    mdfe30_tpComp = fields.Selection(
        COMP_TPCOMP,
        string="Tipo do Componente",
        xsd_required=True,
        help=(
            "Tipo do Componente\n01 - Vale Pedágio; \n02 - Impostos, taxas e "
            "contribuições; \n03 - Despesas (bancárias, meios de pagamento, "
            "outras)\n; 99 - Outros"
        ),
    )

    mdfe30_vComp = fields.Monetary(
        string="Valor do componente",
        xsd_required=True,
        xsd_type="TDec_1302",
        currency_field="brl_currency_id",
    )

    mdfe30_xComp = fields.Char(string="Descrição do componente do tipo Outros")


class EvAlteracaoPagtoServMdfeInfPrazo(models.AbstractModel):
    """Informações do pagamento a prazo.
    Informar somente se indPag for à Prazo"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "mdfe.30.evalteracaopagtoservmdfe_infprazo"
    _inherit = "spec.mixin.mdfe"
    _binding_type = "EvAlteracaoPagtoServMdfe.InfPag.InfPrazo"

    mdfe30_infPrazo_infPag_id = fields.Many2one(
        comodel_name="mdfe.30.evalteracaopagtoservmdfe_infpag",
        xsd_implicit=True,
        ondelete="cascade",
    )
    mdfe30_nParcela = fields.Char(string="Número da Parcela", xsd_required=True)

    mdfe30_dVenc = fields.Date(
        string="Data de vencimento da Parcela",
        xsd_required=True,
        xsd_type="TData",
        help="Data de vencimento da Parcela (AAAA-MM-DD)",
    )

    mdfe30_vParcela = fields.Monetary(
        string="Valor da Parcela",
        xsd_required=True,
        xsd_type="TDec_1302Opc",
        currency_field="brl_currency_id",
    )


class EvAlteracaoPagtoServMdfeInfBanc(models.AbstractModel):
    "Informações bancárias"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "mdfe.30.evalteracaopagtoservmdfe_infbanc"
    _inherit = "spec.mixin.mdfe"
    _binding_type = "EvAlteracaoPagtoServMdfe.InfPag.InfBanc"

    mdfe30_codBanco = fields.Char(
        string="Número do banco", choice="infbanc", xsd_choice_required=True
    )

    mdfe30_codAgencia = fields.Char(
        string="Número da agência bancária", choice="infbanc", xsd_choice_required=True
    )

    mdfe30_CNPJIPEF = fields.Char(
        string="Número do CNPJ da Instituição",
        choice="infbanc",
        xsd_choice_required=True,
        xsd_type="TCnpjOpc",
        help=(
            "Número do CNPJ da Instituição de Pagamento Eletrônico do "
            "Frete\nInformar os zeros não significativos."
        ),
    )

    mdfe30_PIX = fields.Char(
        string="Chave PIX",
        choice="infbanc",
        xsd_choice_required=True,
        help=(
            "Chave PIX\nInformar a chave PIX para recebimento do frete. \nPode"
            " ser email, CPF/ CNPJ (somente numeros), Telefone com a seguinte "
            "formatação (+5599999999999) ou a chave aleatória gerada pela "
            "instituição."
        ),
    )
