{
    "name": "NFS-e Nacional Spec (DPS v1.0 Abstract Models)",
    "summary": "Abstract Odoo models generated by xsdata-odoo from DPS v1.0 XSD",
    "version": "16.0.1.0.0",
    "license": "LGPL-3",
    "author": "Akretion, Escodoo, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/l10n-brazil",
    "development_status": "Alpha",
    "category": "Accounting",
    "depends": ["spec_driven_model"],
    "external_dependencies": {
        "python": ["nfelib", "xsdata", "lxml"],
    },
    "installable": True,
    "application": False,
}
