{
    "name": "NFS-e abstract models",
    "version": "16.0.1.1.0",
    "author": "Akretion, Odoo Community Association (OCA)",
    "license": "LGPL-3",
    "category": "Accounting",
    "summary": "NFS-e abstract models generated by xsdata-odoo from the official xsd",
    "depends": [],
    "installable": True,
    "application": False,
    "development_status": "Alpha",
    "maintainers": ["rvalyi"],
    "website": "https://github.com/OCA/l10n-brazil",
}
