# Copyright 2023 - TODAY, Akretion - Raphael Valyi <raphael.valyi@akretion.com>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/sped-extractor and xsdata-odoo

from odoo import fields, models


class SpecMixinEFDICMSIPI(models.AbstractModel):
    _name = "l10n_br_sped.mixin.efd_icms_ipi"
    _description = "l10n_br_sped.mixin.efd_icms_ipi"
    _inherit = "l10n_br_sped.mixin"

    declaration_id = fields.Many2one(
        comodel_name="l10n_br_sped.efd_icms_ipi.0000",
        required=True,
        ondelete="cascade",
    )

    state = fields.Selection(related="declaration_id.state")

    def _format_field_value(self, field, value):
        # A zero is written only where the layout requires the field
        # (out_required); an optional numeric field is left blank.
        if field.type in ("integer", "float", "monetary") and not value:
            return "0" if getattr(field, "out_required", False) else ""
        return super()._format_field_value(field, value)
