{
    "name": "NF-e abstract models",
    "summary": "NF-e abstract models generated by xsdata-odoo from the official xsd",
    "version": "14.0.8.0.0",
    "author": "Akretion, Odoo Community Association (OCA)",
    "license": "LGPL-3",
    "category": "Accounting",
    "depends": [],
    "installable": True,
    "application": False,
    "development_status": "Mature",
    "maintainers": ["rvalyi"],
    "website": "https://github.com/OCA/l10n-brazil",
}
