# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

import textwrap
from odoo import fields, models
from .tipos_simples_v1_00 import (
    TCOBJETOLOCACAO,
    TSAMBGERADORNFSE,
    TSCATEGVEIC,
    TSCATEGORIASERVICO,
    TSCODJUSTSUBST,
    TSCODNAONIF,
    TSEMITENTEDPS,
    TSENVMDIC,
    TSIDEDEDRED,
    TSMECAFCOMEXPREST,
    TSMECAFCOMEXTOMA,
    TSMODOPRESTACAO,
    TSMOVTEMPBENS,
    TSOPCONSUMSERV,
    TSOPEXIGSUSPENSA,
    TSOPSIMPNAC,
    TSOPTIPOBM,
    TSPROCEMISSAO,
    TSREGESPTRIB,
    TSREGIMEAPURACAOSIMPNAC,
    TSRODAGEM,
    TSTIPOAMBIENTE,
    TSTIPOCST,
    TSTIPOEMISSAO,
    TSTIPOIMUNIDADEISSQN,
    TSTIPOINDTOTTRIB,
    TSTIPORETISSQN,
    TSTIPORETPISCOFINS,
    TSTRIBISSQN,
    TSUF,
    TSVINCPREST,
    TSTAT,
)

__NAMESPACE__ = "http://www.sped.fazenda.gov.br/nfse"


class Tccserv(models.AbstractModel):
    _description = "TCCServ"
    _name = "nfse.10.tccserv"
    _inherit = "spec.mixin.nfse"
    _binding_type = "Tccserv"


    
    nfse10_cTribNac = fields.Char(
        string="Código de tributação nacional do ISSQN",
        xsd_type="TSCodTribNac",
        help=(
            "Código de tributação nacional do ISSQN:\nRegra de formação - 6 "
            "dígitos numéricos sendo: 2 para Item (LC 116/2003), 2 para "
            "Subitem (LC 116/2003) e 2 para Desdobro Nacional"
        )
    )
    
    nfse10_cTribMun = fields.Char(
        string="Código de tributação municipal do ISSQN",
        xsd_type="TCCodTribMun"
    )
    
    nfse10_xDescServ = fields.Char(
        string="Descrição completa do serviço prestado",
        xsd_type="TSDesc2000"
    )
    
    nfse10_cNBS = fields.Char(
        string="Código NBS",
        xsd_type="TSCodNBS",
        help=(
            "Código NBS (Nomenclatura Brasileira de Serviços, Intangíveis e "
            "outras Operações que produzam Variações no Patrimônio) "
            "correspondente ao serviço prestado"
        )
    )
    
    nfse10_cIntContrib = fields.Char(
        string="Código interno do contribuinte",
        xsd_type="TSCodigoInternoContribuinte"
    )


class TcdocNfnfs(models.AbstractModel):
    _description = "TCDocNFNFS"
    _name = "nfse.10.tcdocnfnfs"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcdocNfnfs"


    
    nfse10_nNFS = fields.Char(
        string="Número da Nota Fiscal NF ou NFS",
        xsd_type="TSNum7Dig"
    )
    
    nfse10_modNFS = fields.Char(
        string="Modelo da Nota Fiscal NF ou NFS",
        xsd_type="TSNum15Dig"
    )
    
    nfse10_serieNFS = fields.Char(
        string="Série Nota Fiscal NF ou NFS",
        xsd_type="TSSerieNFNFS"
    )


class TcdocOutNfse(models.AbstractModel):
    _description = "TCDocOutNFSe"
    _name = "nfse.10.tcdocoutnfse"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcdocOutNfse"


    
    nfse10_cMunNFSeMun = fields.Char(
        string="Código Município emissor",
        xsd_type="TSCodMunIBGE",
        help=(
            "Código Município emissor da nota eletrônica municipal (Tabela do "
            "IBGE)"
        )
    )
    
    nfse10_nNFSeMun = fields.Char(
        string="Número da nota eletrônica municipal",
        xsd_type="TSNum15Dig"
    )
    
    nfse10_cVerifNFSeMun = fields.Char(
        string="Código de Verificação",
        xsd_type="TSCodVerificacao",
        help="Código de Verificação da nota eletrônica municipal"
    )


class TcenderExt(models.AbstractModel):
    _description = "TCEnderExt"
    _name = "nfse.10.tcenderext"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcenderExt"


    
    nfse10_cPais = fields.Char(
        string="Código do país",
        xsd_type="TSCodPaisISO",
        help="Código do país (Tabela de Países ISO)"
    )
    
    nfse10_cEndPost = fields.Char(
        string="Código alfanumérico",
        xsd_type="TSCodigoEndPostal",
        help=(
            "Código alfanumérico do Endereçamento Postal no exterior do "
            "prestador do serviço."
        )
    )
    
    nfse10_xCidade = fields.Char(
        string="Nome da cidade no exterior do prestador",
        xsd_type="TSCidade",
        help="Nome da cidade no exterior do prestador do serviço."
    )
    
    nfse10_xEstProvReg = fields.Char(
        string="Estado",
        xsd_type="TSEstadoProvRegiao",
        help=(
            "Estado, província ou região da cidade no exterior do prestador do"
            " serviço."
        )
    )


class TcenderExtSimples(models.AbstractModel):
    _description = "TCEnderExtSimples"
    _name = "nfse.10.tcenderextsimples"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcenderExtSimples"


    
    nfse10_cEndPost = fields.Char(
        string="Código alfanumérico",
        xsd_type="TSCodigoEndPostal",
        help=(
            "Código alfanumérico do Endereçamento Postal no exterior do "
            "prestador do serviço."
        )
    )
    
    nfse10_xCidade = fields.Char(
        string="Nome da cidade no exterior do prestador",
        xsd_type="TSCidade",
        help="Nome da cidade no exterior do prestador do serviço."
    )
    
    nfse10_xEstProvReg = fields.Char(
        string="Estado",
        xsd_type="TSEstadoProvRegiao",
        help=(
            "Estado, província ou região da cidade no exterior do prestador do"
            " serviço."
        )
    )


class TcenderNac(models.AbstractModel):
    _description = "TCEnderNac"
    _name = "nfse.10.tcendernac"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcenderNac"


    
    nfse10_cMun = fields.Char(
        string="Código do município",
        xsd_type="TSCodMunIBGE",
        help="Código do município, conforme Tabela do IBGE"
    )
    
    nfse10_CEP = fields.Char(
        string="Número do CEP",
        xsd_type="TSCEP"
    )


class TcenderObraEvento(models.AbstractModel):
    _description = "TCEnderObraEvento"
    _name = "nfse.10.tcenderobraevento"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcenderObraEvento"


    
    nfse10_cEndPost = fields.Char(
        string="Código de endereçamento postal",
        xsd_type="TSCodigoEndPostal"
    )
    
    nfse10_xLgr = fields.Char(
        string="Tipo e nome do logradouro da localização",
        xsd_type="TSLogradouro",
        help="Tipo e nome do logradouro da localização do imóvel"
    )
    
    nfse10_nro = fields.Char(
        string="Número do imóvel",
        xsd_type="TSNumeroEndereco"
    )
    
    nfse10_xCpl = fields.Char(
        string="Complemento do endereço",
        xsd_type="TSComplementoEndereco"
    )
    
    nfse10_xBairro = fields.Char(
        string="Bairro",
        xsd_type="TSBairro"
    )
    
    nfse10_xCidade = fields.Char(
        string="Cidade",
        xsd_type="TSCidade"
    )
    
    nfse10_xEstProvReg = fields.Char(
        string="Estado, província ou região",
        xsd_type="TSEstadoProvRegiao"
    )


class TcinfoCompl(models.AbstractModel):
    _description = "TCInfoCompl"
    _name = "nfse.10.tcinfocompl"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcinfoCompl"


    
    nfse10_idDocTec = fields.Char(
        string="Identificador de Documento",
        xsd_type="TSDRT",
        help=(
            "Identificador de Documento de Responsabilidade Técnica: ART, RRT,"
            " DRT, Outros."
        )
    )
    
    nfse10_docRef = fields.Char(
        string="Chave da nota",
        xsd_type="TSDesc255",
        help=(
            "Chave da nota, número identificador da nota, número do contrato "
            "ou outro identificador de documento emitido pelo prestador de "
            "serviços, que subsidia a emissão dessa nota pelo tomador do "
            "serviço ou intermediário (preenchimento obrigatório caso a nota "
            "esteja sendo emitida pelo Tomador ou intermediário do serviço)."
        )
    )
    
    nfse10_xInfComp = fields.Char(
        string="Informações complementares",
        xsd_type="TSDescInfCompl"
    )


class TctribTotalMonet(models.AbstractModel):
    _description = "TCTribTotalMonet"
    _name = "nfse.10.tctribtotalmonet"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TctribTotalMonet"


    
    nfse10_vTotTribFed = fields.Char(
        string="Valor monetário total aproximado",
        xsd_type="TSDec15V2",
        help="Valor monetário total aproximado dos tributos federais (R$)."
    )
    
    nfse10_vTotTribEst = fields.Char(
        string="vTotTribEst",
        xsd_type="TSDec15V2",
        help=(
            "Valor monetário total aproximado dos tributos estaduais (R$)."
        )
    )
    
    nfse10_vTotTribMun = fields.Char(
        string="vTotTribMun",
        xsd_type="TSDec15V2",
        help=(
            "Valor monetário total aproximado dos tributos municipais (R$)."
        )
    )


class TctribTotalPercent(models.AbstractModel):
    _description = "TCTribTotalPercent"
    _name = "nfse.10.tctribtotalpercent"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TctribTotalPercent"


    
    nfse10_pTotTribFed = fields.Char(
        string="Valor percentual total aproximado",
        xsd_type="TSDec3V2",
        help="Valor percentual total aproximado dos tributos federais (%)."
    )
    
    nfse10_pTotTribEst = fields.Char(
        string="pTotTribEst",
        xsd_type="TSDec3V2",
        help=(
            "Valor percentual total aproximado dos tributos estaduais (%)."
        )
    )
    
    nfse10_pTotTribMun = fields.Char(
        string="pTotTribMun",
        xsd_type="TSDec3V2",
        help=(
            "Valor percentual total aproximado dos tributos municipais (%)."
        )
    )


class TcvdescCondIncond(models.AbstractModel):
    _description = "TCVDescCondIncond"
    _name = "nfse.10.tcvdesccondincond"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcvdescCondIncond"


    
    nfse10_vDescIncond = fields.Char(
        string="Valor monetário",
        xsd_type="TSDec15V2",
        help="Valor monetário do desconto incondicionado (R$)"
    )
    
    nfse10_vDescCond = fields.Char(
        string="Valor monetário do desconto condicionado",
        xsd_type="TSDec15V2",
        help="Valor monetário do desconto condicionado (R$)"
    )


class TcvservPrest(models.AbstractModel):
    _description = "TCVServPrest"
    _name = "nfse.10.tcvservprest"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcvservPrest"


    
    nfse10_vReceb = fields.Char(
        string="Valor monetário recebido",
        xsd_type="TSDec15V2",
        help="Valor monetário recebido pelo intermediário do serviço (R$)"
    )
    
    nfse10_vServ = fields.Char(
        string="Valor dos serviços em R$",
        xsd_type="TSDec15V2"
    )


class TcvaloresNfse(models.AbstractModel):
    _description = "TCValoresNFSe"
    _name = "nfse.10.tcvaloresnfse"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcvaloresNfse"


    
    nfse10_vCalcDR = fields.Char(
        string="Valor monetário",
        xsd_type="TSDec15V2",
        help=(
            "Valor monetário (R$) de dedução/redução da base de cálculo (BC) "
            "do ISSQN."
        )
    )
    
    nfse10_tpBM = fields.Char(
        string="Tipo de Benefício Municipal (BM)",
        xsd_type="TSDesc40"
    )
    
    nfse10_vCalcBM = fields.Char(
        string="Valor monetário (vCalcBM)",
        xsd_type="TSDec15V2",
        help=(
            "Valor monetário (R$) do percentual de redução da base de cálculo "
            "(BC) do ISSQN devido a um benefício municipal (BM)."
        )
    )
    
    nfse10_vBC = fields.Char(
        string="Valor monetário (vBC)",
        xsd_type="TSDec15V2",
        help=(
            "Valor monetário (R$) do percentual de redução da base de cálculo "
            "(BC) do ISSQN devido a um benefício municipal (BM)."
        )
    )
    
    nfse10_pAliqAplic = fields.Char(
        string="Alíquota aplicada sobre a base",
        xsd_type="TSDec1V2",
        help=(
            "Alíquota aplicada sobre a base de cálculo para apuração do ISSQN."
        )
    )
    
    nfse10_vISSQN = fields.Char(
        string="Valor do ISSQN",
        xsd_type="TSDec15V2",
        help=(
            "Valor do ISSQN (R$) = Valor da Base de Cálculo x Alíquota ISSQN ="
            " vBC x pAliqAplic"
        )
    )
    
    nfse10_vTotalRet = fields.Char(
        string="Valor total",
        xsd_type="TSDec15V2",
        help=(
            "Valor total de retenções = Σ(CP + IRRF + CSLL  + ISSQN* +  (PIS +"
            " COFINS)**)\nvTotalRet (R$) = (vRetCP + vRetIRRF + vRetCSLL) + "
            "vISSQN* + (vPIS + vCOFINS)**"
        )
    )
    
    nfse10_vLiq = fields.Char(
        string="Valor líquido = Valor do serviço",
        xsd_type="TSDec15V2",
        help=(
            "Valor líquido = Valor do serviço - Desconto condicionado - "
            "Desconto incondicionado - Valores retidos (CP, IRRF, CSLL)* - "
            "Valores, se retidos (ISSQN, PIS, COFINS)**\nValor Líquido (R$) = "
            "vServ – vDescIncond – vDescCond – (vRetCP + vRetIRRF + vRetCSLL)*"
            " – (vISSQN - vPIS + vCOFINS)**"
        )
    )
    
    nfse10_xOutInf = fields.Char(
        string="Uso",
        xsd_type="TSDesc2000",
        help="Uso da Administração Tributária Municipal."
    )


class TcbeneficioMunicipal(models.AbstractModel):
    _description = "TCBeneficioMunicipal"
    _name = "nfse.10.tcbeneficiomunicipal"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcbeneficioMunicipal"


    
    nfse10_tpBM = fields.Selection(TSOPTIPOBM,
        string="Identificação da Lei parametrizada",
        xsd_type="TSOpTipoBM",
        help=(
            "Identificação da Lei parametrizada pelo município que define o "
            "benefício.\nTrata-se de um identificador único que foi gerado "
            "pelo Sistema Nacional no momento em que o município de incidência"
            " do ISSQN incluiu o benefício no sistema.\nTem a seguinte regra "
            "de formação: 7 dígitos com o código IBGE do município + 4 dígitos"
            " com número sequencial.\nDeve ser obtido da parametrização do "
            "município de incidência do ISSQN."
        )
    )
    
    nfse10_nBM = fields.Char(
        string="Identificador",
        xsd_type="TSNumBeneficioMunicipal",
        help=(
            "Identificador do benefício municipal parametrizado pelo "
            "município."
        )
    )
    
    nfse10_vRedBCBM = fields.Char(
        string="Valor monetário informado pelo emitente",
        choice="tcbeneficiomunicipal",
        xsd_choice_required=True,
        xsd_type="TSDec15V2",
        help=(
            "Valor monetário informado pelo emitente para redução da base de "
            "cálculo (BC) do ISSQN devido a um Benefício Municipal (BM)."
        )
    )
    
    nfse10_pRedBCBM = fields.Char(
        string="Valor percentual informado pelo emitente",
        choice="tcbeneficiomunicipal",
        xsd_choice_required=True,
        xsd_type="TSDec3V2",
        help=(
            "Valor percentual informado pelo emitente para redução da base de "
            "cálculo (BC) do ISSQN devido a um Benefício Municipal (BM)."
        )
    )


class TccomExterior(models.AbstractModel):
    _description = "TCComExterior"
    _name = "nfse.10.tccomexterior"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TccomExterior"


    
    nfse10_mdPrestacao = fields.Selection(TSMODOPRESTACAO,
        string="Modo de Prestação",
        xsd_type="TSModoPrestacao",
        help=(
            "Modo de Prestação:\n0 - Desconhecido (tipo não informado na nota "
            "de origem);\n1 - Transfronteiriço;\n2 - Consumo no Brasil;\n3 - "
            "Presença Comercial no Exterior;\n4 - Movimento Temporário de "
            "Pessoas Físicas;"
        )
    )
    
    nfse10_vincPrest = fields.Selection(TSVINCPREST,
        string="Vínculo entre as partes no negócio",
        xsd_type="TSVincPrest",
        help=(
            "Vínculo entre as partes no negócio:\n0 - Sem vínculo com o "
            "tomador/ Prestador\n1 - Controlada;\n2 - Controladora;\n3 - "
            "Coligada;\n4 - Matriz;\n5 - Filial ou sucursal;\n6 - Outro "
            "vínculo;"
        )
    )
    
    nfse10_tpMoeda = fields.Char(
        string="Identifica a moeda",
        xsd_type="TSCodMoeda",
        help="Identifica a moeda da transação comercial"
    )
    
    nfse10_vServMoeda = fields.Char(
        string="Valor do serviço prestado expresso",
        xsd_type="TSDec15V2",
        help=(
            "Valor do serviço prestado expresso em moeda estrangeira "
            "especificada em tpmoeda"
        )
    )
    
    nfse10_mecAFComexP = fields.Selection(TSMECAFCOMEXPREST,
        string="Mecanismo de apoio/fomento",
        xsd_type="TSMecAFComExPrest",
        help=(
            "Mecanismo de apoio/fomento ao Comércio Exterior utilizado pelo "
            "prestador do serviço:\n00 - Desconhecido (tipo não informado na "
            "nota de origem);\n01 - Nenhum;\n02 - ACC - Adiantamento sobre "
            "Contrato de Câmbio – Redução a Zero do IR e do IOF;\n03 - ACE – "
            "Adiantamento sobre Cambiais Entregues - Redução a Zero do IR e do"
            " IOF;\n04 - BNDES-Exim Pós-Embarque – Serviços;\n05 - BNDES-Exim "
            "Pré-Embarque - Serviços;\n06 - FGE - Fundo de Garantia à "
            "Exportação;\n07 - PROEX - EQUALIZAÇÃO\n08 - PROEX - "
            "Financiamento;"
        )
    )
    
    nfse10_mecAFComexT = fields.Selection(TSMECAFCOMEXTOMA,
        string="Mecanismo de apoio/fomento (mecAFComexT)",
        xsd_type="TSMecAFComExToma",
        help=(
            "Mecanismo de apoio/fomento ao Comércio Exterior utilizado pelo "
            "tomador do serviço:\n00 - Desconhecido (tipo não informado na "
            "nota de origem);\n01 - Nenhum;\n02 - Adm. Pública e Repr. "
            "Internacional;\n03 - Alugueis e Arrend. Mercantil de maquinas, "
            "equip., embarc. e aeronaves;\n04 - Arrendamento Mercantil de "
            "aeronave para empresa de transporte aéreo público;\n05 - Comissão"
            " a agentes externos na exportação;\n06 - Despesas de armazenagem,"
            " mov. e transporte de carga no exterior;\n07 - Eventos FIFA "
            "(subsidiária);\n08 - Eventos FIFA;\n09 - Fretes, arrendamentos de"
            " embarcações ou aeronaves e outros;\n10 - Material "
            "Aeronáutico;\n11 - Promoção de Bens no Exterior;\n12 - Promoção "
            "de Dest. Turísticos Brasileiros;\n13 - Promoção do Brasil no "
            "Exterior;\n14 - Promoção Serviços no Exterior;\n15 - RECINE;\n16 "
            "- RECOPA;\n17 - Registro e Manutenção de marcas, patentes e "
            "cultivares;\n18 - REICOMP;\n19 - REIDI;\n20 - REPENEC;\n21 - "
            "REPES;\n22 - RETAERO;\n23 - RETID;\n24 - Royalties, Assistência "
            "Técnica, Científica e Assemelhados;\n25 - Serviços de avaliação "
            "da conformidade vinculados aos Acordos da OMC;\n26 - ZPE;"
        )
    )
    
    nfse10_movTempBens = fields.Selection(TSMOVTEMPBENS,
        string="Operação está vinculada",
        xsd_type="TSMovTempBens",
        help=(
            "Operação está vinculada à Movimentação Temporária de Bens:\n0 - "
            "Desconhecido (tipo não informado na nota de origem);\n1 - Não\n2 "
            "- Vinculada - Declaração de Importação\n3 - Vinculada - "
            "Declaração de Exportação"
        )
    )
    
    nfse10_nDI = fields.Char(
        string="Número da Declaração de Importação",
        xsd_type="TSNumDocImport",
        help=(
            "Número da Declaração de Importação (DI/DSI/DA/DRI-E) averbado"
        )
    )
    
    nfse10_nRE = fields.Char(
        string="Número do Registro de Exportação",
        xsd_type="TSNumRegExport",
        help="Número do Registro de Exportação (RE) averbado"
    )
    
    nfse10_mdic = fields.Selection(TSENVMDIC,
        string="Compartilhar as informações",
        xsd_type="TSEnvMDIC",
        help=(
            "Compartilhar as informações da NFS-e gerada a partir desta DPS "
            "com a Secretaria de Comércio Exterior:\n0 - Não enviar para o "
            "MDIC;\n1 - Enviar para o MDIC;"
        )
    )


class Tcendereco(models.AbstractModel):
    _description = "TCEndereco"
    _name = "nfse.10.tcendereco"
    _inherit = "spec.mixin.nfse"
    _binding_type = "Tcendereco"


    
    nfse10_endNac = fields.Many2one(
        comodel_name="nfse.10.tcendernac",
        string="Grupo de informações específicas",
        choice="tcendereco",
        xsd_type="TCEnderNac",
        help="Grupo de informações específicas de endereço nacional"
    )
    
    nfse10_endExt = fields.Many2one(
        comodel_name="nfse.10.tcenderext",
        string="endExt",
        choice="tcendereco",
        xsd_type="TCEnderExt",
        help="Grupo de informações específicas de endereço no exterior"
    )
    
    nfse10_xLgr = fields.Char(
        string="Tipo e nome do logradouro da localização",
        xsd_type="TSLogradouro",
        help="Tipo e nome do logradouro da localização do imóvel"
    )
    
    nfse10_nro = fields.Char(
        string="Número do imóvel",
        xsd_type="TSNumeroEndereco"
    )
    
    nfse10_xCpl = fields.Char(
        string="Complemento do endereço",
        xsd_type="TSComplementoEndereco"
    )
    
    nfse10_xBairro = fields.Char(
        string="Bairro",
        xsd_type="TSBairro"
    )


class TcenderecoEmitente(models.AbstractModel):
    _description = "TCEnderecoEmitente"
    _name = "nfse.10.tcenderecoemitente"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcenderecoEmitente"


    
    nfse10_xLgr = fields.Char(
        string="Tipo e nome do logradouro da localização",
        xsd_type="TSLogradouro",
        help="Tipo e nome do logradouro da localização do imóvel"
    )
    
    nfse10_nro = fields.Char(
        string="Número do imóvel",
        xsd_type="TSNumeroEndereco"
    )
    
    nfse10_xCpl = fields.Char(
        string="Complemento do endereço",
        xsd_type="TSComplementoEndereco"
    )
    
    nfse10_xBairro = fields.Char(
        string="Bairro",
        xsd_type="TSBairro"
    )
    
    nfse10_cMun = fields.Char(
        string="Código do município",
        xsd_type="TSCodMunIBGE",
        help="Código do município, conforme Tabela do IBGE"
    )
    
    nfse10_UF = fields.Selection(TSUF,
        string="Sigla da unidade da federação",
        xsd_type="TSUF",
        help=(
            "Sigla da unidade da federação do município do endereço do "
            "emitente."
        )
    )
    
    nfse10_CEP = fields.Char(
        string="Número do CEP",
        xsd_type="TSCEP"
    )


class TcenderecoSimples(models.AbstractModel):
    _description = "TCEnderecoSimples"
    _name = "nfse.10.tcenderecosimples"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcenderecoSimples"


    
    nfse10_CEP = fields.Char(
        string="Número do CEP",
        choice="tcenderecosimples",
        xsd_choice_required=True,
        xsd_type="TSCEP"
    )
    
    nfse10_endExt = fields.Many2one(
        comodel_name="nfse.10.tcenderextsimples",
        string="Grupo de informações específicas",
        choice="tcenderecosimples",
        xsd_choice_required=True,
        xsd_type="TCEnderExtSimples",
        help="Grupo de informações específicas de endereço no exterior"
    )
    
    nfse10_xLgr = fields.Char(
        string="Tipo e nome do logradouro da localização",
        xsd_type="TSLogradouro",
        help="Tipo e nome do logradouro da localização do imóvel"
    )
    
    nfse10_nro = fields.Char(
        string="Número do imóvel",
        xsd_type="TSNumeroEndereco"
    )
    
    nfse10_xCpl = fields.Char(
        string="Complemento do endereço",
        xsd_type="TSComplementoEndereco"
    )
    
    nfse10_xBairro = fields.Char(
        string="Bairro",
        xsd_type="TSBairro"
    )


class TcexigSuspensa(models.AbstractModel):
    _description = "TCExigSuspensa"
    _name = "nfse.10.tcexigsuspensa"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcexigSuspensa"


    
    nfse10_tpSusp = fields.Selection(TSOPEXIGSUSPENSA,
        string="Opção para Exigibilidade Suspensa",
        xsd_type="TSOpExigSuspensa",
        help=(
            "Opção para Exigibilidade Suspensa:\n1 - Exigibilidade Suspensa "
            "por Decisão Judicial;\n2 - Exigibilidade Suspensa por Processo "
            "Administrativo;"
        )
    )
    
    nfse10_nProcesso = fields.Char(
        string="Número do processo judicial",
        xsd_type="TSNumProcExigSuspensa",
        help=(
            "Número do processo judicial ou administrativo de suspensão da "
            "exigibilidade"
        )
    )


class TcexploracaoRodoviaria(models.AbstractModel):
    _description = "TCExploracaoRodoviaria"
    _name = "nfse.10.tcexploracaorodoviaria"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcexploracaoRodoviaria"


    
    nfse10_categVeic = fields.Selection(TSCATEGVEIC,
        string="Categorias de veículos para cobrança",
        xsd_type="TSCategVeic",
        help=(
            "Categorias de veículos para cobrança:\n00 - Categoria de Veículos"
            " (tipo não informado na nota de origem);\n01 - Automóvel, "
            "caminhonete e furgão;\n02 - Caminhão leve, ônibus, caminhão "
            "trator e furgão;\n03 - Automóvel e caminhonete com "
            "semireboque;\n04 - Caminhão, caminhão-trator, caminhão-trator com"
            " semi-reboque e ônibus;\n05 - Automóvel e caminhonete com "
            "reboque;\n06 - Caminhão com reboque e caminhãotrator com semi-"
            "reboque;\n07 - Caminhão com reboque e caminhãotrator com semi-"
            "reboque;\n08 - Caminhão com reboque e caminhãotrator com semi-"
            "reboque;\n09 - Motocicletas, motonetas e bicicletas "
            "motorizadas;\n10 - Veículo especial;\n11 - Veículo Isento;"
        )
    )
    
    nfse10_nEixos = fields.Char(
        string="Número de eixos para fins de cobrança",
        xsd_type="TSNumEixos"
    )
    
    nfse10_rodagem = fields.Selection(TSRODAGEM,
        string="Tipo de rodagem",
        xsd_type="TSRodagem"
    )
    
    nfse10_sentido = fields.Char(
        string="Placa do veículo",
        xsd_type="TSSentido"
    )
    
    nfse10_placa = fields.Char(
        string="Placa do veículo (placa)",
        xsd_type="TSPlaca"
    )
    
    nfse10_codAcessoPed = fields.Char(
        string="Código de acesso gerado automaticamente",
        xsd_type="TSCodAcessoPed",
        help=(
            "Código de acesso gerado automaticamente pelo sistema emissor da "
            "concessionária."
        )
    )
    
    nfse10_codContrato = fields.Char(
        string="Código",
        xsd_type="TSCodContrato",
        help=(
            "Código de contrato gerado automaticamente pelo sistema nacional "
            "no cadastro da concessionária."
        )
    )


class TclocPrest(models.AbstractModel):
    _description = "TCLocPrest"
    _name = "nfse.10.tclocprest"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TclocPrest"


    
    nfse10_cLocPrestacao = fields.Char(
        string="Código do município onde o serviço",
        xsd_type="TSCodMunIBGE",
        help=(
            "Código do município onde o serviço foi prestado (tabela do IBGE)"
        )
    )
    
    nfse10_cPaisPrestacao = fields.Char(
        string="Código do país onde o serviço",
        xsd_type="TSCodPaisISO",
        help=(
            "Código do país onde o serviço foi prestado (Tabela de Países ISO)"
        )
    )
    
    nfse10_opConsumServ = fields.Selection(TSOPCONSUMSERV,
        string="Opção",
        xsd_type="TSOpConsumServ",
        help=(
            "Opção para que o emitente informe onde ocorreu o consumo do "
            "serviço prestado.\n0 - Consumo do serviço prestado ocorrido no "
            "município do local da prestação;\n1 - Consumo do serviço prestado"
            " ocorrido ocorrido no exterior ;"
        )
    )


class TclocacaoSublocacao(models.AbstractModel):
    _description = "TCLocacaoSublocacao"
    _name = "nfse.10.tclocacaosublocacao"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TclocacaoSublocacao"


    
    nfse10_categ = fields.Selection(TSCATEGORIASERVICO,
        string="Categoria do serviço",
        xsd_type="TSCategoriaServico"
    )
    
    nfse10_objeto = fields.Selection(TCOBJETOLOCACAO,
        string="Tipo de objetos da locação",
        xsd_type="TCObjetoLocacao",
        help=(
            "Tipo de objetos da locação, sublocação, arrendamento, direito de "
            "passagem ou permissão de uso"
        )
    )
    
    nfse10_extensao = fields.Char(
        string="Extensão total da ferrovia, rodovia",
        xsd_type="TSExtensaoTotal",
        help=(
            "Extensão total da ferrovia, rodovia, cabos, dutos ou condutos"
        )
    )
    
    nfse10_nPostes = fields.Char(
        string="Número total de postes",
        xsd_type="TSNumeroPostes"
    )


class TcregTrib(models.AbstractModel):
    _description = "TCRegTrib"
    _name = "nfse.10.tcregtrib"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcregTrib"


    
    nfse10_opSimpNac = fields.Selection(TSOPSIMPNAC,
        string="Situação perante o Simples Nacional",
        xsd_type="TSOpSimpNac",
        help=(
            "Situação perante o Simples Nacional:\n1 - Não Optante;\n2 - "
            "Optante - Microempreendedor Individual (MEI);\n3 - Optante - "
            "Microempresa ou Empresa de Pequeno Porte (ME/EPP);"
        )
    )
    
    nfse10_regApTribSN = fields.Selection(TSREGIMEAPURACAOSIMPNAC,
        string="Opção para que o contribuinte optante",
        xsd_type="TSRegimeApuracaoSimpNac",
        help=(
            "Opção para que o contribuinte optante pelo Simples Nacional "
            "ME/EPP (opSimpNac = 3) possa indicar, ao emitir o documento "
            "fiscal, em qual regime de apuração os tributos federais e "
            "municipal estão inseridos, caso tenha ultrapassado algum "
            "sublimite ou limite definido para o Simples Nacional.\n1 – Regime"
            " de apuração dos tributos federais e municipal pelo SN;\n2 – "
            "Regime de apuração dos tributos federais pelo SN e ISSQN  por "
            "fora do SN conforme respectiva legislação municipal do "
            "tributo;\n3 – Regime de apuração dos tributos federais e "
            "municipal por fora do SN conforme respectivas legilações federal "
            "e municipal de cada tributo;"
        )
    )
    
    nfse10_regEspTrib = fields.Selection(TSREGESPTRIB,
        string="Tipos de Regimes Especiais de Tributação",
        xsd_type="TSRegEspTrib",
        help=(
            "Tipos de Regimes Especiais de Tributação:\n0 - Nenhum;\n1 - Ato "
            "Cooperado (Cooperativa);\n2 - Estimativa;\n3 - Microempresa "
            "Municipal;\n4 - Notário ou Registrador;\n5 - Profissional "
            "Autônomo;\n6 - Sociedade de Profissionais;"
        )
    )


class Tcsubstituicao(models.AbstractModel):
    _description = "TCSubstituicao"
    _name = "nfse.10.tcsubstituicao"
    _inherit = "spec.mixin.nfse"
    _binding_type = "Tcsubstituicao"


    
    nfse10_chSubstda = fields.Char(
        string="Chave de acesso da NFS-e",
        xsd_type="TSChaveNFSe",
        help="Chave de acesso da NFS-e a ser substituída"
    )
    
    nfse10_cMotivo = fields.Selection(TSCODJUSTSUBST,
        string="Código de justificativa",
        xsd_type="TSCodJustSubst",
        help=(
            "Código de justificativa para substituição de NFS-e:\n01 - "
            "Desenquadramento de NFS-e do Simples Nacional;\n02 - "
            "Enquadramento de NFS-e no Simples Nacional;\n03 - Inclusão "
            "Retroativa de Imunidade/Isenção para NFS-e;\n04 - Exclusão "
            "Retroativa de Imunidade/Isenção para NFS-e;\n05 - Rejeição de "
            "NFS-e pelo tomador ou pelo intermediário se responsável pelo "
            "recolhimento do tributo;\n99 - Outros;"
        )
    )
    
    nfse10_xMotivo = fields.Char(
        string="Descrição do motivo da substituição",
        xsd_type="TSMotivo",
        help="Descrição do motivo da substituição da NFS-e"
    )


class TctribOutrosPisCofins(models.AbstractModel):
    _description = "TCTribOutrosPisCofins"
    _name = "nfse.10.tctriboutrospiscofins"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TctribOutrosPisCofins"


    
    nfse10_CST = fields.Selection(TSTIPOCST,
        string="Código de Situação Tributária",
        xsd_type="TSTipoCST",
        help=(
            "Código de Situação Tributária do PIS/COFINS (CST):\n00 - "
            "Nenhum;\n01 - Operação Tributável com Alíquota Básica;\n02 - "
            "Operação Tributável com Alíquota Diferenciada;\n03 - Operação "
            "Tributável com Alíquota por Unidade de Medida de Produto;\n04 - "
            "Operação Tributável monofásica - Revenda a Alíquota Zero;\n05 - "
            "Operação Tributável por Substituição Tributária;\n06 - Operação "
            "Tributável a Alíquota Zero;\n07 - Operação Tributável da "
            "Contribuição;\n08 - Operação sem Incidência da Contribuição;\n09 "
            "- Operação com Suspensão da Contribuição;"
        )
    )
    
    nfse10_vBCPisCofins = fields.Char(
        string="Valor da Base de Cálculo do PIS/COFINS",
        xsd_type="TSDec15V2",
        help="Valor da Base de Cálculo do PIS/COFINS (R$)."
    )
    
    nfse10_pAliqPis = fields.Char(
        string="Valor da Alíquota do PIS (%)",
        xsd_type="TSDec2V2"
    )
    
    nfse10_pAliqCofins = fields.Char(
        string="Valor da Alíquota da COFINS (%)",
        xsd_type="TSDec2V2"
    )
    
    nfse10_vPis = fields.Char(
        string="Valor monetário do PIS (R$)",
        xsd_type="TSDec15V2"
    )
    
    nfse10_vCofins = fields.Char(
        string="Valor monetário do COFINS (R$)",
        xsd_type="TSDec15V2"
    )
    
    nfse10_tpRetPisCofins = fields.Selection(TSTIPORETPISCOFINS,
        string="Tipo de retencao do Pis/Cofins",
        xsd_type="TSTipoRetPISCofins",
        help=(
            "Tipo de retencao do Pis/Cofins:\n1 - Retido;\n2 - Não Retido;"
        )
    )


class TctribTotal(models.AbstractModel):
    _description = "TCTribTotal"
    _name = "nfse.10.tctribtotal"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TctribTotal"


    
    nfse10_vTotTrib = fields.Many2one(
        comodel_name="nfse.10.tctribtotalmonet",
        string="Valor monetário total aproximado",
        choice="tctribtotal",
        xsd_choice_required=True,
        xsd_type="TCTribTotalMonet",
        help=(
            "Valor monetário total aproximado dos tributos, em conformidade "
            "com o artigo 1o da Lei no 12.741/2012"
        )
    )
    
    nfse10_pTotTrib = fields.Many2one(
        comodel_name="nfse.10.tctribtotalpercent",
        string="Valor percentual total aproximado",
        choice="tctribtotal",
        xsd_choice_required=True,
        xsd_type="TCTribTotalPercent",
        help=(
            "Valor percentual total aproximado dos tributos, em conformidade "
            "com o artigo 1o da Lei no 12.741/2012"
        )
    )
    
    nfse10_indTotTrib = fields.Selection(TSTIPOINDTOTTRIB,
        string="Indicador de informação de valor total",
        choice="tctribtotal",
        xsd_choice_required=True,
        xsd_type="TSTipoIndTotTrib",
        help=(
            "Indicador de informação de valor total de tributos. Possui valor "
            "fixo igual a zero (indTotTrib=0).\nNão informar nenhum valor "
            "estimado para os Tributos (Decreto 8.264/2014).\n0 - Não;"
        )
    )
    
    nfse10_pTotTribSN = fields.Char(
        string="Valor percentual aproximado do total",
        choice="tctribtotal",
        xsd_choice_required=True,
        xsd_type="TSDec2V2",
        help=(
            "Valor percentual aproximado do total dos tributos da alíquota do "
            "Simples Nacional (%)"
        )
    )


class TcatvEvento(models.AbstractModel):
    _description = "TCAtvEvento"
    _name = "nfse.10.tcatvevento"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcatvEvento"


    
    nfse10_desc = fields.Char(
        string="Descrição do evento Artístico",
        xsd_type="TSDesc255",
        help="Descrição do evento Artístico, Cultural, Esportivo, etc"
    )
    
    nfse10_dtIni = fields.Date(
        string="Data de início da atividade de evento",
        xsd_type="xs:date",
        help=(
            "Data de início da atividade de evento. Ano, Mês e Dia (AAAA-MM-"
            "DD)"
        )
    )
    
    nfse10_dtFim = fields.Date(
        string="Data de fim da atividade de evento",
        xsd_type="xs:date",
        help=(
            "Data de fim da atividade de evento. Ano, Mês e Dia (AAAA-MM-DD)"
        )
    )
    
    nfse10_id = fields.Char(
        string="Identificação da Atividade de Evento",
        choice="tcatvevento",
        xsd_choice_required=True,
        xsd_type="TSIdeEvento",
        help=(
            "Identificação da Atividade de Evento (código identificador de "
            "evento determinado pela Administração Tributária Municipal)"
        )
    )
    
    nfse10_end = fields.Many2one(
        comodel_name="nfse.10.tcenderecosimples",
        string="Grupo de informações relativas",
        choice="tcatvevento",
        xsd_choice_required=True,
        xsd_type="TCEnderecoSimples",
        help=(
            "Grupo de informações relativas ao endereço da atividade, evento "
            "ou local do serviço prestado"
        )
    )


class Tcemitente(models.AbstractModel):
    _description = "TCEmitente"
    _name = "nfse.10.tcemitente"
    _inherit = "spec.mixin.nfse"
    _binding_type = "Tcemitente"


    
    nfse10_CNPJ = fields.Char(
        string="Número do CNPJ do emitente da NFS-e",
        choice="tcemitente",
        xsd_choice_required=True,
        xsd_type="TSCNPJ"
    )
    
    nfse10_CPF = fields.Char(
        string="Número do CPF do emitente da NFS-e",
        choice="tcemitente",
        xsd_choice_required=True,
        xsd_type="TSCPF"
    )
    
    nfse10_IM = fields.Char(
        string="Número da inscrição municipal",
        xsd_type="TSInscMun"
    )
    
    nfse10_xNome = fields.Char(
        string="Nome / Razão Social do emitente",
        xsd_type="TSNomeRazaoSocial"
    )
    
    nfse10_xFant = fields.Char(
        string="Nome / Fantasia do emitente",
        xsd_type="TSNomeFantasia"
    )
    
    nfse10_enderNac = fields.Many2one(
        comodel_name="nfse.10.tcenderecoemitente",
        string="Grupo de informações",
        xsd_type="TCEnderecoEmitente",
        help=(
            "Grupo de informações do endereço nacional do Emitente da NFS-e"
        )
    )
    
    nfse10_fone = fields.Char(
        string="Número do telefone do emitente",
        xsd_type="TSTelefone",
        help=(
            "Número do telefone do emitente.\n(Preencher com o Código DDD + "
            "número do telefone.\nNas operações com exterior é permitido "
            "informar o código do país + código da localidade + número do "
            "telefone)"
        )
    )
    
    nfse10_email = fields.Char(
        string="E-mail do emitente",
        xsd_type="TSEmail"
    )


class TcinfoObra(models.AbstractModel):
    _description = "TCInfoObra"
    _name = "nfse.10.tcinfoobra"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcinfoObra"


    
    nfse10_cObra = fields.Char(
        string="Número de identificação da obra",
        choice="tcinfoobra",
        xsd_choice_required=True,
        xsd_type="TSCodObra",
        help=(
            "Número de identificação da obra.\nCadastro Nacional de Obras "
            "(CNO) ou Cadastro Específico do INSS (CEI)."
        )
    )
    
    nfse10_inscImobFisc = fields.Char(
        string="Inscrição imobiliária fiscal",
        choice="tcinfoobra",
        xsd_choice_required=True,
        xsd_type="TSInscImobFisc",
        help=(
            "Inscrição imobiliária fiscal (código fornecido pela Prefeitura "
            "Municipal para a identificação da obra ou para fins de "
            "recolhimento do IPTU)"
        )
    )
    
    nfse10_end = fields.Many2one(
        comodel_name="nfse.10.tcenderecosimples",
        string="Grupo de informações do endereço da obra",
        choice="tcinfoobra",
        xsd_choice_required=True,
        xsd_type="TCEnderecoSimples",
        help="Grupo de informações do endereço da obra do serviço prestado"
    )


class TcinfoPessoa(models.AbstractModel):
    """Informações das pessoas envolvidas na NFS-e. Pode ser o tomador, o
    intermediário ou o fornecedor (dedução/redução)"""
    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfse.10.tcinfopessoa"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcinfoPessoa"


    
    nfse10_CNPJ = fields.Char(
        string="Número do CNPJ",
        choice="tcinfopessoa",
        xsd_choice_required=True,
        xsd_type="TSCNPJ"
    )
    
    nfse10_CPF = fields.Char(
        string="Número do CPF",
        choice="tcinfopessoa",
        xsd_choice_required=True,
        xsd_type="TSCPF"
    )
    
    nfse10_NIF = fields.Char(
        string="Número de Identificação Fiscal fornecido",
        choice="tcinfopessoa",
        xsd_choice_required=True,
        xsd_type="TSNIF",
        help=(
            "Número de Identificação Fiscal fornecido por órgão de "
            "administração tributária no exterior"
        )
    )
    
    nfse10_cNaoNIF = fields.Selection(TSCODNAONIF,
        string="Motivo para não informação do NIF",
        choice="tcinfopessoa",
        xsd_choice_required=True,
        xsd_type="TSCodNaoNIF",
        help=(
            "Motivo para não informação do NIF:\n0 - Não informado na nota de "
            "origem;\n1 - Dispensado do NIF;\n2 - Não exigência do NIF;"
        )
    )
    
    nfse10_CAEPF = fields.Char(
        string="Número do Cadastro",
        xsd_type="TSCAEPF",
        help=(
            "Número do Cadastro de Atividade Econômica da Pessoa Física "
            "(CAEPF)"
        )
    )
    
    nfse10_IM = fields.Char(
        string="Número da inscrição municipal",
        xsd_type="TSInscMun"
    )
    
    nfse10_xNome = fields.Char(
        string="Nome/Nome Empresarial",
        xsd_type="TSNomeRazaoSocial"
    )
    
    nfse10_end = fields.Many2one(
        comodel_name="nfse.10.tcendereco",
        string="Dados de endereço",
        xsd_type="TCEndereco"
    )
    
    nfse10_fone = fields.Char(
        string="Número do telefone do prestador",
        xsd_type="TSTelefone",
        help=(
            "Número do telefone do prestador:\nPreencher com o Código DDD + "
            "número do telefone.\nNas operações com exterior é permitido "
            "informar o código do país + código da localidade + número do "
            "telefone)"
        )
    )
    
    nfse10_email = fields.Char(
        string="E-mail",
        xsd_type="TSEmail"
    )


class TcinfoPrestador(models.AbstractModel):
    """Informações do prestador da NFS-e. Difere das demais pessoas por causa
    das informações de regimes de tributação"""
    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfse.10.tcinfoprestador"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcinfoPrestador"


    
    nfse10_CNPJ = fields.Char(
        string="Número do CNPJ",
        choice="tcinfoprestador",
        xsd_choice_required=True,
        xsd_type="TSCNPJ"
    )
    
    nfse10_CPF = fields.Char(
        string="Número do CPF",
        choice="tcinfoprestador",
        xsd_choice_required=True,
        xsd_type="TSCPF"
    )
    
    nfse10_NIF = fields.Char(
        string="Número de Identificação Fiscal fornecido",
        choice="tcinfoprestador",
        xsd_choice_required=True,
        xsd_type="TSNIF",
        help=(
            "Número de Identificação Fiscal fornecido por órgão de "
            "administração tributária no exterior"
        )
    )
    
    nfse10_cNaoNIF = fields.Selection(TSCODNAONIF,
        string="Motivo para não informação do NIF",
        choice="tcinfoprestador",
        xsd_choice_required=True,
        xsd_type="TSCodNaoNIF",
        help=(
            "Motivo para não informação do NIF:\n1 - Dispensado do NIF;\n2 - "
            "Não exigência do NIF;"
        )
    )
    
    nfse10_CAEPF = fields.Char(
        string="Número do Cadastro",
        xsd_type="TSCAEPF",
        help=(
            "Número do Cadastro de Atividade Econômica da Pessoa Física "
            "(CAEPF) do prestador do serviço."
        )
    )
    
    nfse10_IM = fields.Char(
        string="Número da inscrição municipal",
        xsd_type="TSInscMun"
    )
    
    nfse10_xNome = fields.Char(
        string="Nome/Nome Empresarial do prestador",
        xsd_type="TSNomeRazaoSocial"
    )
    
    nfse10_end = fields.Many2one(
        comodel_name="nfse.10.tcendereco",
        string="Dados de endereço do prestador",
        xsd_type="TCEndereco"
    )
    
    nfse10_fone = fields.Char(
        string="Número do telefone do prestador",
        xsd_type="TSTelefone",
        help=(
            "Número do telefone do prestador:\nPreencher com o Código DDD + "
            "número do telefone.\nNas operações com exterior é permitido "
            "informar o código do país + código da localidade + número do "
            "telefone)"
        )
    )
    
    nfse10_email = fields.Char(
        string="E-mail",
        xsd_type="TSEmail"
    )
    
    nfse10_regTrib = fields.Many2one(
        comodel_name="nfse.10.tcregtrib",
        string="Grupo de informações relativas",
        xsd_type="TCRegTrib",
        help=(
            "Grupo de informações relativas aos regimes de tributação do "
            "prestador de serviços"
        )
    )


class TctribMunicipal(models.AbstractModel):
    _description = "TCTribMunicipal"
    _name = "nfse.10.tctribmunicipal"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TctribMunicipal"


    
    nfse10_tribISSQN = fields.Selection(TSTRIBISSQN,
        string="Tributação do ISSQN sobre",
        xsd_type="TSTribISSQN",
        help=(
            "Tributação do ISSQN sobre o serviço prestado:\n1 - Operação "
            "tributável;\n2 - Exportação de serviço;\n3 - Não Incidência;\n4 -"
            " Imunidade;"
        )
    )
    
    nfse10_cPaisResult = fields.Char(
        string="Código do país onde se verficou",
        xsd_type="TSCodPaisISO",
        help=(
            "Código do país onde se verficou o resultado da prestação do "
            "serviço para o caso de Exportação de Serviço.(Tabela de Países "
            "ISO)"
        )
    )
    
    nfse10_BM = fields.Many2one(
        comodel_name="nfse.10.tcbeneficiomunicipal",
        string="Tributação do ISSQN sobre (BM)",
        xsd_type="TCBeneficioMunicipal",
        help=(
            "Tributação do ISSQN sobre o serviço prestado:\n1 - Operação "
            "tributável;\n2 - Exportação de serviço;\n3 - Não Incidência;\n4 -"
            " Imunidade;"
        )
    )
    
    nfse10_exigSusp = fields.Many2one(
        comodel_name="nfse.10.tcexigsuspensa",
        string="Informações para a suspensão",
        xsd_type="TCExigSuspensa",
        help="Informações para a suspensão da Exigibilidade do ISSQN"
    )
    
    nfse10_tpImunidade = fields.Selection(TSTIPOIMUNIDADEISSQN,
        string="Identificação da Imunidade",
        xsd_type="TSTipoImunidadeISSQN",
        help=(
            "Identificação da Imunidade do ISSQN – somente para o caso de "
            "Imunidade:\n0 - Imunidade (tipo não informado na nota de "
            "origem);\n1 - Patrimônio, renda ou serviços, uns dos outros "
            "(CF88, Art 150, VI, a);\n2 - Templos de qualquer culto (CF88, Art"
            " 150, VI, b);\n3 - Patrimônio, renda ou serviços dos partidos "
            "políticos, inclusive suas fundações, das entidades sindicais dos "
            "trabalhadores, das instituições de educação e de assistência "
            "social, sem fins lucrativos, atendidos os requisitos da lei "
            "(CF88, Art 150, VI, c);\n4 - Livros, jornais, periódicos e o "
            "papel destinado a sua impressão (CF88, Art 150, VI, d);"
        )
    )
    
    nfse10_pAliq = fields.Char(
        string="Valor da alíquota",
        xsd_type="TSDec1V2",
        help=(
            "Valor da alíquota (%) do serviço prestado relativo ao município "
            "sujeito ativo (município de incidência) do ISSQN.\nSe o município"
            " de incidência pertence ao Sistema Nacional NFS-e a alíquota "
            "estará parametrizada e, portanto, será fornecida pelo "
            "sistema.\nSe o município de incidência não pertence ao Sistema "
            "Nacional NFS-e a alíquota não estará parametrizada e, por isso, "
            "deverá ser fornecida pelo emitente."
        )
    )
    
    nfse10_tpRetISSQN = fields.Selection(TSTIPORETISSQN,
        string="Tipo de retencao do ISSQN",
        xsd_type="TSTipoRetISSQN",
        help=(
            "Tipo de retencao do ISSQN:\n1 - Não Retido;\n2 - Retido pelo "
            "Tomador;\n3 - Retido pelo Intermediario;"
        )
    )


class TctribNacional(models.AbstractModel):
    _description = "TCTribNacional"
    _name = "nfse.10.tctribnacional"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TctribNacional"


    
    nfse10_piscofins = fields.Many2one(
        comodel_name="nfse.10.tctriboutrospiscofins",
        string="Grupo de informações",
        xsd_type="TCTribOutrosPisCofins",
        help="Grupo de informações dos tributos PIS/COFINS"
    )
    
    nfse10_vRetCP = fields.Char(
        string="Valor monetário do CP(R$)",
        xsd_type="TSDec15V2"
    )
    
    nfse10_vRetIRRF = fields.Char(
        string="Valor monetário do IRRF (R$)",
        xsd_type="TSDec15V2"
    )
    
    nfse10_vRetCSLL = fields.Char(
        string="Valor monetário do CSLL (R$)",
        xsd_type="TSDec15V2"
    )


class TcdocDedRed(models.AbstractModel):
    _description = "TCDocDedRed"
    _name = "nfse.10.tcdocdedred"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcdocDedRed"


    nfse10_docDedRed_TCListaDocDedRed_id = fields.Many2one(
        comodel_name="nfse.10.tclistadocdedred",
        xsd_implicit=True,
        ondelete="cascade"
    )
    nfse10_chNFSe = fields.Char(
        string="Chave de Acesso da NFS-e",
        choice="tcdocdedred",
        xsd_choice_required=True,
        xsd_type="TSChaveNFSe",
        help="Chave de Acesso da NFS-e (Padrão Nacional)"
    )
    
    nfse10_chNFe = fields.Char(
        string="Chave de Acesso da NF-e",
        choice="tcdocdedred",
        xsd_choice_required=True,
        xsd_type="TSChaveNFe"
    )
    
    nfse10_NFSeMun = fields.Many2one(
        comodel_name="nfse.10.tcdocoutnfse",
        string="Grupo de informações de Outras NFS-e",
        choice="tcdocdedred",
        xsd_choice_required=True,
        xsd_type="TCDocOutNFSe",
        help=(
            "Grupo de informações de Outras NFS-e (Padrão anterior de NFS-e)"
        )
    )
    
    nfse10_NFNFS = fields.Many2one(
        comodel_name="nfse.10.tcdocnfnfs",
        string="Grupo de informações de NF ou NFS",
        choice="tcdocdedred",
        xsd_choice_required=True,
        xsd_type="TCDocNFNFS",
        help="Grupo de informações de NF ou NFS (Modelo não eletrônico)"
    )
    
    nfse10_nDocFisc = fields.Char(
        string="Número de documento fiscal",
        choice="tcdocdedred",
        xsd_choice_required=True,
        xsd_type="TSDesc255"
    )
    
    nfse10_nDoc = fields.Char(
        string="Número de documento não fiscal",
        choice="tcdocdedred",
        xsd_choice_required=True,
        xsd_type="TSDesc255"
    )
    
    nfse10_tpDedRed = fields.Selection(TSIDEDEDRED,
        string="Identificação da Dedução/Redução",
        xsd_type="TSIdeDedRed",
        help=(
            "Identificação da Dedução/Redução:\n1 – Alimentação e "
            "bebidas/frigobar;\n2 – Materiais;\n3 – Produção externa;\n4 – "
            "Reembolso de despesas;\n5 – Repasse consorciado;\n6 – Repasse "
            "plano de saúde;\n7 – Serviços;\n8 – Subempreitada de mão de "
            "obra;\n99 – Outras deduções;"
        )
    )
    
    nfse10_xDescOutDed = fields.Char(
        string="Descrição da Dedução/Redução",
        xsd_type="TSDescOutDedRed",
        help=(
            "Descrição da Dedução/Redução quando a opção é '99 – Outras "
            "Deduções'"
        )
    )
    
    nfse10_dtEmiDoc = fields.Date(
        string="Data da emissão do documento dedutível",
        xsd_type="xs:date",
        help=(
            "Data da emissão do documento dedutível. Ano, mês e dia (AAAA-MM-"
            "DD)"
        )
    )
    
    nfse10_vDedutivelRedutivel = fields.Char(
        string="vDedutivelRedutivel",
        xsd_type="TSDec15V2",
        help=(
            "Valor monetário total dedutível/redutível no documento informado "
            "(R$).\nEste é o valor total no documento informado que é passível"
            " de dedução/redução."
        )
    )
    
    nfse10_vDeducaoReducao = fields.Char(
        string="Valor monetário utilizado",
        xsd_type="TSDec15V2",
        help=(
            "Valor monetário utilizado para dedução/redução do valor do "
            "serviço da NFS-e que está sendo emitida (R$).\nDeve ser menor ou "
            "igual ao valor deduzível/redutível (vDedutivelRedutivel)."
        )
    )
    
    nfse10_fornec = fields.Many2one(
        comodel_name="nfse.10.tcinfopessoa",
        string="Grupo de informações do Fornecedor",
        xsd_type="TCInfoPessoa",
        help="Grupo de informações do Fornecedor em Deduções de Serviços"
    )


class TcinfoTributacao(models.AbstractModel):
    _description = "TCInfoTributacao"
    _name = "nfse.10.tcinfotributacao"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcinfoTributacao"


    
    nfse10_tribMun = fields.Many2one(
        comodel_name="nfse.10.tctribmunicipal",
        string="Grupo de informações relacionados",
        xsd_type="TCTribMunicipal",
        help=(
            "Grupo de informações relacionados ao Imposto Sobre Serviços de "
            "Qualquer Natureza - ISSQN"
        )
    )
    
    nfse10_tribFed = fields.Many2one(
        comodel_name="nfse.10.tctribnacional",
        string="Grupo de informações",
        xsd_type="TCTribNacional",
        help=(
            "Grupo de informações de outros tributos relacionados ao serviço "
            "prestado"
        )
    )
    
    nfse10_totTrib = fields.Many2one(
        comodel_name="nfse.10.tctribtotal",
        string="Grupo de informações (totTrib)",
        xsd_type="TCTribTotal",
        help=(
            "Grupo de informações para totais aproximados dos tributos "
            "relacionados ao serviço prestado"
        )
    )


class Tcserv(models.AbstractModel):
    _description = "TCServ"
    _name = "nfse.10.tcserv"
    _inherit = "spec.mixin.nfse"
    _binding_type = "Tcserv"


    
    nfse10_locPrest = fields.Many2one(
        comodel_name="nfse.10.tclocprest",
        string="Grupo de informações relativas ao local",
        xsd_type="TCLocPrest",
        help=(
            "Grupo de informações relativas ao local da prestação do serviço"
        )
    )
    
    nfse10_cServ = fields.Many2one(
        comodel_name="nfse.10.tccserv",
        string="Grupo de informações relativas ao código",
        xsd_type="TCCServ",
        help="Grupo de informações relativas ao código do serviço prestado"
    )
    
    nfse10_comExt = fields.Many2one(
        comodel_name="nfse.10.tccomexterior",
        string="Grupo de informações relativas",
        xsd_type="TCComExterior",
        help=(
            "Grupo de informações relativas à exportação/importação de serviço"
            " prestado"
        )
    )
    
    nfse10_lsadppu = fields.Many2one(
        comodel_name="nfse.10.tclocacaosublocacao",
        string="Grupo de informações relativas (lsadppu)",
        xsd_type="TCLocacaoSublocacao",
        help=(
            "Grupo de informações relativas a atividades de Locação, "
            "sublocação, arrendamento, direito de passagem ou permissão de "
            "uso, compartilhado ou não, de ferrovia, rodovia, postes, cabos, "
            "dutos e condutos de qualquer natureza"
        )
    )
    
    nfse10_obra = fields.Many2one(
        comodel_name="nfse.10.tcinfoobra",
        string="Grupo de informações do DPS relativas",
        xsd_type="TCInfoObra",
        help="Grupo de informações do DPS relativas à serviço de obra"
    )
    
    nfse10_atvEvento = fields.Many2one(
        comodel_name="nfse.10.tcatvevento",
        string="atvEvento",
        xsd_type="TCAtvEvento",
        help="Grupo de informações do DPS relativas à Evento"
    )
    
    nfse10_explRod = fields.Many2one(
        comodel_name="nfse.10.tcexploracaorodoviaria",
        string="Grupo de informações relativas a pedágio",
        xsd_type="TCExploracaoRodoviaria"
    )
    
    nfse10_infoCompl = fields.Many2one(
        comodel_name="nfse.10.tcinfocompl",
        string="Grupo",
        xsd_type="TCInfoCompl",
        help=(
            "Grupo de informações complementares disponível para todos os "
            "serviços prestados"
        )
    )


class TclistaDocDedRed(models.AbstractModel):
    _description = "TCListaDocDedRed"
    _name = "nfse.10.tclistadocdedred"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TclistaDocDedRed"


    
    nfse10_docDedRed = fields.One2many("nfse.10.tcdocdedred", "nfse10_docDedRed_TCListaDocDedRed_id",
        string="Grupo de informações",
        xsd_type="TCDocDedRed",
        help=(
            "Grupo de informações de documento utilizado para Dedução/Redução "
            "do valor do serviço"
        )
    )


class TcinfoDedRed(models.AbstractModel):
    _description = "TCInfoDedRed"
    _name = "nfse.10.tcinfodedred"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcinfoDedRed"


    
    nfse10_pDR = fields.Char(
        string="Valor percentual padrão",
        choice="tcinfodedred",
        xsd_choice_required=True,
        xsd_type="TSDec3V2",
        help=(
            "Valor percentual padrão para dedução/redução do valor do serviço"
        )
    )
    
    nfse10_vDR = fields.Char(
        string="Valor monetário padrão",
        choice="tcinfodedred",
        xsd_choice_required=True,
        xsd_type="TSDec15V2",
        help=(
            "Valor monetário padrão para dedução/redução do valor do serviço"
        )
    )
    
    nfse10_documentos = fields.Many2one(
        comodel_name="nfse.10.tclistadocdedred",
        string="Grupo de informações",
        choice="tcinfodedred",
        xsd_choice_required=True,
        xsd_type="TCListaDocDedRed",
        help=(
            "Grupo de informações de documento utilizado para Dedução/Redução "
            "do valor do serviço"
        )
    )


class TcinfoValores(models.AbstractModel):
    _description = "TCInfoValores"
    _name = "nfse.10.tcinfovalores"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcinfoValores"


    
    nfse10_vServPrest = fields.Many2one(
        comodel_name="nfse.10.tcvservprest",
        string="Grupo de informações relativas",
        xsd_type="TCVServPrest",
        help=(
            "Grupo de informações relativas aos valores do serviço prestado"
        )
    )
    
    nfse10_vDescCondIncond = fields.Many2one(
        comodel_name="nfse.10.tcvdesccondincond",
        string="vDescCondIncond",
        xsd_type="TCVDescCondIncond",
        help=(
            "Grupo de informações relativas aos descontos condicionados e "
            "incondicionados"
        )
    )
    
    nfse10_vDedRed = fields.Many2one(
        comodel_name="nfse.10.tcinfodedred",
        string="Grupo de informações relativas (vDedRed)",
        xsd_type="TCInfoDedRed",
        help=(
            "Grupo de informações relativas ao valores para dedução/redução do"
            " valor da base de cálculo (valor do serviço)"
        )
    )
    
    nfse10_trib = fields.Many2one(
        comodel_name="nfse.10.tcinfotributacao",
        string="Grupo de informações relacionados",
        xsd_type="TCInfoTributacao",
        help=(
            "Grupo de informações relacionados aos tributos relacionados ao "
            "serviço prestado"
        )
    )


class TcinfDps(models.AbstractModel):
    _description = "TCInfDPS"
    _name = "nfse.10.tcinfdps"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcinfDps"


    
    nfse10_tpAmb = fields.Selection(TSTIPOAMBIENTE,
        string="Identificação do Ambiente: 1",
        xsd_type="TSTipoAmbiente",
        help="Identificação do Ambiente: 1 - Produção; 2 - Homologação"
    )
    
    nfse10_dhEmi = fields.Char(
        string="Data e hora da emissão do DPS",
        xsd_type="TSDateTimeUTC",
        help=(
            "Data e hora da emissão do DPS. Data e hora no formato UTC "
            "(Universal Coordinated Time): AAAA-MM-DDThh:mm:ssTZD"
        )
    )
    
    nfse10_verAplic = fields.Char(
        string="Versão do aplicativo que gerou o DPS",
        xsd_type="TSVerAplic"
    )
    
    nfse10_serie = fields.Char(
        string="Número do equipamento emissor do DPS",
        xsd_type="TSSerieDPS",
        help="Número do equipamento emissor do DPS ou série do DPS"
    )
    
    nfse10_nDPS = fields.Char(
        string="Número do DPS",
        xsd_type="TSNumDPS"
    )
    
    nfse10_dCompet = fields.Char(
        string="Data em que se iniciou a prestação",
        xsd_type="TSData",
        help=(
            "Data em que se iniciou a prestação do serviço: Dia, mês e ano "
            "(AAAAMMDD)"
        )
    )
    
    nfse10_tpEmit = fields.Selection(TSEMITENTEDPS,
        string="Emitente da DPS: 1 - Prestador; 2",
        xsd_type="TSEmitenteDPS",
        help=(
            "Emitente da DPS: 1 - Prestador; 2 - Tomador; 3 - Intermediário"
        )
    )
    
    nfse10_cLocEmi = fields.Char(
        string="O código de município utilizado",
        xsd_type="TSCodMunIBGE",
        help=(
            "O código de município utilizado pelo Sistema Nacional NFS-e é o "
            "código definido para cada município pertencente ao ''Anexo V – "
            "Tabela de Código de Municípios do IBGE'', que consta ao final do "
            "Manual de Orientação ao Contribuinte do ISSQN para a Sefin "
            "Nacional NFS-e.\nO município emissor da NFS-e é aquele município "
            "em que o emitente da DPS está cadastrado e autorizado a 'emitir "
            "uma NFS-e', ou seja, emitir uma DPS para que o sistema nacional "
            "valide as informações nela prestadas e gere a NFS-e "
            "correspondente para o emitente.\nPara que o sistema nacional "
            "emita a NFS-e o município emissor deve ser conveniado e estar "
            "ativo no sistema nacional. Além disso o convênio do município "
            "deve permitir que os contribuintes do município utilize os "
            "emissores públicos do Sistema Nacional NFS-e"
        )
    )
    
    nfse10_subst = fields.Many2one(
        comodel_name="nfse.10.tcsubstituicao",
        string="Dados da NFS-e a ser substituída",
        xsd_type="TCSubstituicao"
    )
    
    nfse10_prest = fields.Many2one(
        comodel_name="nfse.10.tcinfoprestador",
        string="Grupo de informações do DPS relativas",
        xsd_type="TCInfoPrestador",
        help=(
            "Grupo de informações do DPS relativas ao Prestador de Serviços"
        )
    )
    
    nfse10_toma = fields.Many2one(
        comodel_name="nfse.10.tcinfopessoa",
        string="toma",
        xsd_type="TCInfoPessoa",
        help="Grupo de informações do DPS relativas ao Tomador de Serviços"
    )
    
    nfse10_interm = fields.Many2one(
        comodel_name="nfse.10.tcinfopessoa",
        string="interm",
        xsd_type="TCInfoPessoa",
        help=(
            "Grupo de informações do DPS relativas ao Intermediário de "
            "Serviços"
        )
    )
    
    nfse10_serv = fields.Many2one(
        comodel_name="nfse.10.tcserv",
        string="serv",
        xsd_type="TCServ",
        help="Grupo de informações do DPS relativas ao Serviço Prestado"
    )
    
    nfse10_valores = fields.Many2one(
        comodel_name="nfse.10.tcinfovalores",
        string="Grupo de informações relativas à valores",
        xsd_type="TCInfoValores",
        help="Grupo de informações relativas à valores do serviço prestado"
    )
    
    nfse10_Id = fields.Char(
        string="Id",
        xsd_type="TSIdDPS"
    )


class Tcdps(models.AbstractModel):
    _description = "TCDPS"
    _name = "nfse.10.tcdps"
    _inherit = "spec.mixin.nfse"
    _binding_type = "Tcdps"


    
    nfse10_infDPS = fields.Many2one(
        comodel_name="nfse.10.tcinfdps",
        string="infDPS",
        xsd_type="TCInfDPS"
    )
    
    nfse10_versao = fields.Char(
        string="versao",
        xsd_type="TVerNFSe"
    )


class TcinfNfse(models.AbstractModel):
    _description = "TCInfNFSe"
    _name = "nfse.10.tcinfnfse"
    _inherit = "spec.mixin.nfse"
    _binding_type = "TcinfNfse"


    
    nfse10_xLocEmi = fields.Char(
        string="Descrição do código do IBGE",
        xsd_type="TSDesc150",
        help="Descrição do código do IBGE do município emissor da NFS-e."
    )
    
    nfse10_xLocPrestacao = fields.Char(
        string="Descrição do local da prestação",
        xsd_type="TSDesc150",
        help="Descrição do local da prestação do serviço."
    )
    
    nfse10_nNFSe = fields.Char(
        string="Número sequencial por tipo de emitente",
        xsd_type="TSNNFSe",
        help=(
            "Número sequencial por tipo de emitente da NFS-e.\nA Sefin "
            "Nacional NFS-e irá gerar o número da NFS-e de forma sequencial "
            "por emitente. Por se tratar de um ambiente altamente "
            "transacional, a Sefin Nacional NFS-e não irá reutilizar números "
            "inutilizados durante a geração da NFS-e."
        )
    )
    
    nfse10_cLocIncid = fields.Char(
        string="O código de município utilizado",
        xsd_type="TSCodMunIBGE",
        help=(
            "O código de município utilizado pelo Sistema Nacional NFS-e é o "
            "código definido para cada município pertencente ao ''Anexo V – "
            "Tabela de Código de Municípios do IBGE'', que consta ao final do "
            "Manual de Orientação ao Contribuinte do ISSQN para a Sefin "
            "Nacional NFS-e.\nO município de incidência do ISSQN é determinado"
            " automaticamente pelo sistema, conforme regras do aspecto "
            "espacial da lei complementar federal (LC 116/03) que são válidas "
            "para todos  os municípios.\nhttp://www.planalto.gov.br/ccivil_03/"
            "Leis/LCP/Lcp116.htm"
        )
    )
    
    nfse10_xLocIncid = fields.Char(
        string="A descrição do código",
        xsd_type="TSDesc150",
        help=(
            "A descrição do código de município utilizado pelo Sistema "
            "Nacional NFS-e é o nome de cada município pertencente ao 'Anexo V"
            " – Tabela de Código de Municípios do IBGE', que consta ao final "
            "do Manual de Orientação ao Contribuinte do ISSQN para a Sefin "
            "Nacional NFS-e."
        )
    )
    
    nfse10_xTribNac = fields.Char(
        string="Descrição do código",
        xsd_type="TSDesc600",
        help="Descrição do código de tributação nacional do ISSQN."
    )
    
    nfse10_xTribMun = fields.Char(
        string="Descrição do código (xTribMun)",
        xsd_type="TSDesc600",
        help="Descrição do código de tributação municipal do ISSQN."
    )
    
    nfse10_xNBS = fields.Char(
        string="Descrição do código da NBS",
        xsd_type="TSDesc600"
    )
    
    nfse10_verAplic = fields.Char(
        string="Versão do aplicativo que gerou a NFS-e",
        xsd_type="TSVerAplic"
    )
    
    nfse10_ambGer = fields.Selection(TSAMBGERADORNFSE,
        string="Ambiente gerador da NFS-e",
        xsd_type="TSAmbGeradorNFSe"
    )
    
    nfse10_tpEmis = fields.Selection(TSTIPOEMISSAO,
        string="Processo de Emissão da DPS",
        xsd_type="TSTipoEmissao",
        help=(
            "Processo de Emissão da DPS:\n1 - Emissão com aplicativo do "
            "contribuinte (via Web Service);\n2 - Emissão com aplicativo "
            "disponibilizado pelo fisco (Web);\n3 - Emissão com aplicativo "
            "disponibilizado pelo fisco (App);"
        )
    )
    
    nfse10_procEmi = fields.Selection(TSPROCEMISSAO,
        string="Processo de Emissão da DPS (procEmi)",
        xsd_type="TSProcEmissao",
        help=(
            "Processo de Emissão da DPS:\n1 - Emissão com aplicativo do "
            "contribuinte (via Web Service);\n2 - Emissão com aplicativo "
            "disponibilizado pelo fisco (Web);\n3 - Emissão com aplicativo "
            "disponibilizado pelo fisco (App);"
        )
    )
    
    nfse10_cStat = fields.Selection(TSTAT,
        string="Código do Status da mensagem",
        xsd_type="TStat"
    )
    
    nfse10_dhProc = fields.Char(
        string="Data/Hora da validação da DPS e geração",
        xsd_type="TSDateTimeUTC",
        help=(
            "Data/Hora da validação da DPS e geração da NFS-e. Data e hora no "
            "formato UTC (Universal Coordinated Time):AAAA-MM-DDThh:mm:ssTZD"
        )
    )
    
    nfse10_nDFSe = fields.Char(
        string="Número sequencial do documento gerado",
        xsd_type="TSNDFSe",
        help=(
            "Número sequencial do documento gerado por ambiente gerador de "
            "DFSe do múnicípio."
        )
    )
    
    nfse10_emit = fields.Many2one(
        comodel_name="nfse.10.tcemitente",
        string="Grupo de informações da DPS relativas",
        xsd_type="TCEmitente",
        help="Grupo de informações da DPS relativas ao emitente da NFS-e"
    )
    
    nfse10_valores = fields.Many2one(
        comodel_name="nfse.10.tcvaloresnfse",
        string="Grupo de valores referentes",
        xsd_type="TCValoresNFSe",
        help="Grupo de valores referentes ao Serviço Prestado"
    )
    
    nfse10_DPS = fields.Many2one(
        comodel_name="nfse.10.tcdps",
        string="DPS",
        xsd_type="TCDPS",
        help="Grupo de informações da DPS relativas ao serviço prestado"
    )
    
    nfse10_Id = fields.Char(
        string="Id",
        xsd_type="TSIdNFSe"
    )


class Tcnfse(models.AbstractModel):
    _description = "TCNFSe"
    _name = "nfse.10.tcnfse"
    _inherit = "spec.mixin.nfse"
    _binding_type = "Tcnfse"


    
    nfse10_infNFSe = fields.Many2one(
        comodel_name="nfse.10.tcinfnfse",
        string="infNFSe",
        xsd_type="TCInfNFSe"
    )
    
    nfse10_versao = fields.Char(
        string="versao",
        xsd_type="TVerNFSe"
    )
