# Copyright 2022 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo
#
import textwrap
from odoo import fields, models

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"


class Duto(models.AbstractModel):
    "Informações do modal Dutoviário"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "cte.30.duto"
    _inherit = "spec.mixin.cte"
    _binding_type = "Duto"

    cte30_vTar = fields.Float(
        string="Valor da tarifa",
        xsd_type="TDec_0906Opc",
        digits=(
            9,
            6,
        ),
    )

    cte30_dIni = fields.Date(
        string="Data de Início da prestação do serviço",
        xsd_required=True,
        xsd_type="TData",
    )

    cte30_dFim = fields.Date(
        string="Data de Fim da prestação do serviço",
        xsd_required=True,
        xsd_type="TData",
    )
