# Copyright 2022 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo
#
import textwrap
from odoo import fields, models
from .tipos_geral_cte_v3_00 import (
    TAMB,
    TCORGAOIBGE,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"

"Tipo Modal transporte"
TMODTRANSP = [
    ("01", "01"),
    ("02", "02"),
    ("03", "03"),
    ("04", "04"),
    ("05", "05"),
    ("06", "06"),
]


class Tevento(models.AbstractModel):
    "Tipo Evento"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "cte.30.tevento"
    _inherit = "spec.mixin.cte"
    _binding_type = "Tevento"

    cte30_infEvento = fields.Many2one(
        comodel_name="cte.30.tevento_infevento", string="infEvento", xsd_required=True
    )

    cte30_versao = fields.Char(
        string="versao", xsd_required=True, xsd_type="TVerEvento"
    )


class TeventoInfEvento(models.AbstractModel):
    _description = "infEvento"
    _name = "cte.30.tevento_infevento"
    _inherit = "spec.mixin.cte"
    _binding_type = "Tevento.InfEvento"

    cte30_cOrgao = fields.Selection(
        TCORGAOIBGE,
        string="Código do órgão de recepção do Evento",
        xsd_required=True,
        xsd_type="TCOrgaoIBGE",
        help=(
            "Código do órgão de recepção do Evento. Utilizar a Tabela do IBGE "
            "extendida, utilizar 90 para identificar SUFRAMA"
        ),
    )

    cte30_tpAmb = fields.Selection(
        TAMB,
        string="Identificação do Ambiente",
        xsd_required=True,
        xsd_type="TAmb",
        help="Identificação do Ambiente:\n1 - Produção\n2 - Homologação",
    )

    cte30_CNPJ = fields.Char(
        string="CNPJ do emissor do evento",
        choice="infevento",
        xsd_choice_required=True,
        xsd_type="TCnpj",
    )

    cte30_CPF = fields.Char(
        string="CPF do emissor do evento",
        choice="infevento",
        xsd_choice_required=True,
        xsd_type="TCpf",
        help=(
            "CPF do emissor do evento\nInformar zeros não "
            "significativos.\n\nUsar com série específica 920-969 para "
            "emitente pessoa física com inscrição estadual"
        ),
    )

    cte30_chCTe = fields.Char(
        string="Chave de Acesso do CT-e vinculado",
        xsd_required=True,
        xsd_type="TChNFe",
        help="Chave de Acesso do CT-e vinculado ao evento",
    )

    cte30_dhEvento = fields.Datetime(
        string="Data e Hora do Evento",
        xsd_required=True,
        xsd_type="TDateTimeUTC",
        help="Data e Hora do Evento, formato UTC (AAAA-MM-DDThh:mm:ssTZD)",
    )

    cte30_tpEvento = fields.Char(string="Tipo do Evento", xsd_required=True)

    cte30_nSeqEvento = fields.Char(
        string="Seqüencial do evento para o mesmo tipo",
        xsd_required=True,
        help=(
            "Seqüencial do evento para o mesmo tipo de evento.  Para maioria "
            "dos eventos será 1, nos casos em que possa existir mais de um "
            "evento o autor do evento deve numerar de forma seqüencial."
        ),
    )

    cte30_detEvento = fields.Many2one(
        comodel_name="cte.30.detevento",
        string="Detalhamento do evento específico",
        xsd_required=True,
    )

    cte30_infSolicNFF = fields.Many2one(
        comodel_name="cte.30.infevento_infsolicnff",
        string="Grupo de informações do pedido",
        help=(
            "Grupo de informações do pedido de registro de evento da Nota "
            "Fiscal Fácil"
        ),
    )

    cte30_Id = fields.Char(
        string="Identificador da TAG a ser assinada",
        xsd_required=True,
        help=(
            "Identificador da TAG a ser assinada, a regra de formação do Id "
            "é:\n“ID” + tpEvento +  chave do CT-e + nSeqEvento"
        ),
    )


class DetEvento(models.AbstractModel):
    "Detalhamento do evento específico"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "cte.30.detevento"
    _inherit = "spec.mixin.cte"
    _binding_type = "Tevento.InfEvento.DetEvento"

    cte30_versaoEvento = fields.Char(string="versaoEvento", xsd_required=True)


class InfEventoInfSolicNff(models.AbstractModel):
    """Grupo de informações do pedido de registro de evento da Nota Fiscal
    Fácil"""

    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "cte.30.infevento_infsolicnff"
    _inherit = "spec.mixin.cte"
    _binding_type = "Tevento.InfEvento.InfSolicNff"

    cte30_xSolic = fields.Char(
        string="Solicitação do pedido de registro",
        xsd_required=True,
        help=(
            "Solicitação do pedido de registro de evento da NFF.\nSerá "
            "preenchido com a totalidade de campos informados no aplicativo "
            "emissor serializado."
        ),
    )


class TretEvento(models.AbstractModel):
    "Tipo retorno do Evento"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "cte.30.tretevento"
    _inherit = "spec.mixin.cte"
    _binding_type = "TretEvento"

    cte30_infEvento = fields.Many2one(
        comodel_name="cte.30.tretevento_infevento",
        string="infEvento",
        xsd_required=True,
    )

    cte30_versao = fields.Char(string="versao", xsd_required=True)


class TretEventoInfEvento(models.AbstractModel):
    _description = "infEvento"
    _name = "cte.30.tretevento_infevento"
    _inherit = "spec.mixin.cte"
    _binding_type = "TretEvento.InfEvento"

    cte30_tpAmb = fields.Selection(
        TAMB,
        string="Identificação do Ambiente",
        xsd_required=True,
        xsd_type="TAmb",
        help="Identificação do Ambiente:\n1 - Produção\n2 - Homologação",
    )

    cte30_verAplic = fields.Char(
        string="Versão do Aplicativo que recebeu",
        xsd_required=True,
        xsd_type="TVerAplic",
        help="Versão do Aplicativo que recebeu o Evento",
    )

    cte30_cOrgao = fields.Selection(
        TCORGAOIBGE,
        string="Código do órgão de recepção do Evento",
        xsd_required=True,
        xsd_type="TCOrgaoIBGE",
        help=(
            "Código do órgão de recepção do Evento. Utilizar a Tabela do IBGE "
            "extendida, utilizar 90 para identificar SUFRAMA"
        ),
    )

    cte30_cStat = fields.Char(
        string="Código do status da registro do Evento",
        xsd_required=True,
        xsd_type="TStat",
    )

    cte30_xMotivo = fields.Char(
        string="Descrição literal do status do registro",
        xsd_required=True,
        xsd_type="TMotivo",
        help="Descrição literal do status do registro do Evento",
    )

    cte30_chCTe = fields.Char(
        string="Chave de Acesso CT-e vinculado", xsd_type="TChNFe"
    )

    cte30_tpEvento = fields.Char(string="Tipo do Evento vinculado")

    cte30_xEvento = fields.Char(string="Descrição do Evento")

    cte30_nSeqEvento = fields.Char(string="Seqüencial do evento")

    cte30_dhRegEvento = fields.Datetime(
        string="Data e Hora de do recebimento",
        xsd_type="TDateTimeUTC",
        help=(
            "Data e Hora de do recebimento do evento ou do registro do evento "
            "formato AAAA-MM-DDThh:mm:ssTZD"
        ),
    )

    cte30_nProt = fields.Char(
        string="Número do protocolo de registro",
        xsd_type="TProt",
        help="Número do protocolo de registro do evento",
    )

    cte30_Id = fields.Char(string="Id")


class TprocEvento(models.AbstractModel):
    "Tipo procEvento"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "cte.30.tprocevento"
    _inherit = "spec.mixin.cte"
    _binding_type = "TprocEvento"

    cte30_eventoCTe = fields.Many2one(
        comodel_name="cte.30.tevento",
        string="eventoCTe",
        xsd_required=True,
        xsd_type="TEvento",
    )

    cte30_retEventoCTe = fields.Many2one(
        comodel_name="cte.30.tretevento",
        string="retEventoCTe",
        xsd_required=True,
        xsd_type="TRetEvento",
    )

    cte30_versao = fields.Char(
        string="versao", xsd_required=True, xsd_type="TVerEvento"
    )

    cte30_ipTransmissor = fields.Char(
        string="IP do transmissor",
        xsd_type="TIPv4",
        help=("IP do transmissor do documento fiscal para o ambiente autorizador"),
    )

    cte30_nPortaCon = fields.Char(
        string="Porta de origem utilizada na conexão",
        help="Porta de origem utilizada na conexão (De 0 a 65535)",
    )

    cte30_dhConexao = fields.Datetime(
        string="Data e Hora da Conexão de Origem", xsd_type="TDateTimeUTC"
    )
