# Copyright (C) 2026  Renato Lima - Akretion <renato.lima@akretion.com.br>
# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html

from odoo import _, api, fields, models
from odoo.exceptions import ValidationError

from ..constants import (
    FCI_FIELD_SEPARATOR,
    FCI_LINE_VALIDATION,
    FCI_UOM_CODE_OTHER,
    FCI_UOM_CODES,
)
from ..tools import compute_import_content, format_amount, sanitize_code, sanitize_text


class FCILine(models.Model):
    """Goods of a FCI file, register 5020 of the layout.

    One FCI control number is generated by the tax administration for each
    line of the file.
    """

    _name = "l10n_br_fiscal.fci.line"
    _description = "FCI Line"
    _order = "fci_id, sequence, id"

    fci_id = fields.Many2one(
        comodel_name="l10n_br_fiscal.fci.header",
        string="FCI",
        required=True,
        ondelete="cascade",
        index=True,
    )

    sequence = fields.Integer(default=10)

    company_id = fields.Many2one(
        comodel_name="res.company",
        related="fci_id.company_id",
        store=True,
        index=True,
    )

    currency_id = fields.Many2one(
        comodel_name="res.currency",
        related="company_id.currency_id",
        string="Currency",
    )

    state = fields.Selection(
        related="fci_id.state",
        string="Status",
        store=True,
    )

    product_id = fields.Many2one(
        comodel_name="product.product",
        string="Product",
        index=True,
        check_company=True,
        help="Product of the goods. It is not written in the file, it links "
        "the FCI control number to the product. It may be empty right after "
        "the import of a file generated in another platform, when no product "
        "matches the code of the goods.",
    )

    product_tmpl_id = fields.Many2one(
        comodel_name="product.template",
        related="product_id.product_tmpl_id",
        string="Product Template",
        store=True,
        index=True,
    )

    name = fields.Char(
        string="Description",
        size=255,
        required=True,
        compute="_compute_product_fields",
        store=True,
        readonly=False,
        precompute=True,
        help="Register 5020 field NOME_MERCADORIA.",
    )

    ncm_id = fields.Many2one(
        comodel_name="l10n_br_fiscal.ncm",
        string="NCM",
        compute="_compute_product_fields",
        store=True,
        readonly=False,
        precompute=True,
    )

    ncm_code = fields.Char(
        related="ncm_id.code_unmasked",
        string="NCM Code",
        help="Register 5020 field CODIGO_NCM.",
    )

    product_code = fields.Char(
        size=50,
        required=True,
        compute="_compute_product_fields",
        store=True,
        readonly=False,
        precompute=True,
        help="Internal code identifying the goods in the establishment, "
        "register 5020 field CODIGO_MERCADORIA.",
    )

    gtin = fields.Char(
        string="GTIN",
        size=14,
        compute="_compute_product_fields",
        store=True,
        readonly=False,
        precompute=True,
        help="Global Trade Item Number, register 5020 field CODIGO_GTIN. "
        "This field is optional.",
    )

    uom_id = fields.Many2one(
        comodel_name="uom.uom",
        string="Unit of Measure",
        compute="_compute_product_fields",
        store=True,
        readonly=False,
        precompute=True,
    )

    uom_code = fields.Char(
        string="Unit Code",
        size=6,
        required=True,
        compute="_compute_uom_code",
        store=True,
        readonly=False,
        precompute=True,
        help="Abbreviation of the unit of measure of the goods, register "
        "5020 field UNIDADE_MERCADORIA. Use '99' for units which are not "
        "in the table of the Ato COTEPE ICMS 61/2012.",
    )

    amount_interstate = fields.Monetary(
        string="Interstate Output Amount",
        required=True,
        help="Total amount of the interstate output of the goods per unit of "
        "measure, register 5020 field "
        "VALOR_SAIDA_MERCADORIA_INTERESTADUAL.",
    )

    amount_imported = fields.Monetary(
        string="Imported Amount",
        required=True,
        help="Amount of the parcel imported from abroad per unit of measure, "
        "register 5020 field VALOR_PARCELA_IMPORTADA_EXTERIOR.",
    )

    import_content = fields.Float(
        string="Import Content (%)",
        digits=(6, 2),
        compute="_compute_import_content",
        store=True,
        help="Percentage of the import content, register 5020 field "
        "CONTEUDO_IMPORTACAO_CI.",
    )

    fci_code = fields.Char(
        string="FCI Control Number",
        size=36,
        readonly=True,
        copy=False,
        index=True,
        help="FCI control number returned by the tax administration, to be "
        "written in the NF-e field nFCI.",
    )

    validation_indicator = fields.Selection(
        selection=FCI_LINE_VALIDATION,
        readonly=True,
        copy=False,
        help="Register 5020 field IN_VALIDACAO_FICHA of the return file.",
    )

    @api.depends("product_id")
    def _compute_product_fields(self):
        for line in self:
            product = line.product_id
            line.name = sanitize_text(product.display_name, 255)
            line.ncm_id = product.ncm_id
            line.product_code = sanitize_text(product.default_code, 50)
            line.gtin = sanitize_code(product.barcode, 14)
            line.uom_id = product.uom_id

    @api.depends("uom_id")
    def _compute_uom_code(self):
        for line in self:
            code = sanitize_text(line.uom_id.code, 6)
            line.uom_code = code if code in FCI_UOM_CODES else FCI_UOM_CODE_OTHER

    @api.depends("amount_interstate", "amount_imported")
    def _compute_import_content(self):
        for line in self:
            line.import_content = compute_import_content(
                line.amount_imported, line.amount_interstate
            )

    @api.onchange("uom_code")
    def _onchange_uom_code(self):
        if self.uom_code and self.uom_code not in FCI_UOM_CODES:
            return {
                "warning": {
                    "title": _("Unit of Measure"),
                    "message": _(
                        "The unit '%s' does not belong to the table of the "
                        "Ato COTEPE ICMS 61/2012. The file will be accepted "
                        "but the validator will raise a warning. Use '99' "
                        "for other units."
                    )
                    % self.uom_code,
                }
            }

    @api.constrains("ncm_id")
    def _check_ncm(self):
        for line in self.filtered("ncm_id"):
            code = line.ncm_code or ""
            if len(code) != 8 or not code.isdigit():
                raise ValidationError(
                    _("The NCM %s must have 8 digits to be used in a FCI.")
                    % line.ncm_id.code
                )
            if code.startswith("00"):
                raise ValidationError(
                    _("The NCM %s can not start with two consecutive zeros.")
                    % line.ncm_id.code
                )

    @api.constrains("amount_interstate", "amount_imported")
    def _check_amounts(self):
        for line in self:
            if line.amount_interstate <= 0:
                raise ValidationError(
                    _(
                        "The interstate output amount of the product %s must "
                        "be greater than zero."
                    )
                    % line.product_id.display_name
                )
            if line.amount_imported <= 0:
                raise ValidationError(
                    _(
                        "The imported amount of the product %s must be "
                        "greater than zero."
                    )
                    % line.product_id.display_name
                )

    def _check_before_generate(self):
        """Return the list of the blocking problems found in the line."""
        self.ensure_one()
        errors = []
        product_name = self.product_id.display_name or self.name or self.product_code
        if not self.ncm_id:
            errors.append(_("The NCM of the goods %s is empty.") % product_name)
        if not self.name:
            errors.append(
                _("The description of the product %s is empty.") % product_name
            )
        if not self.product_code:
            errors.append(_("The code of the product %s is empty.") % product_name)
        if not self.uom_code:
            errors.append(
                _("The unit of measure of the product %s is empty.") % product_name
            )
        if self.gtin and len(self.gtin) not in (8, 12, 13, 14):
            errors.append(
                _("The GTIN of the product %s must have 8, 12, 13 or 14 digits.")
                % product_name
            )
        return errors

    def _prepare_register_5020(self):
        self.ensure_one()
        return FCI_FIELD_SEPARATOR.join(
            [
                "5020",
                sanitize_text(self.name, 255),
                self.ncm_code or "",
                sanitize_text(self.product_code, 50),
                sanitize_code(self.gtin, 14),
                sanitize_text(self.uom_code, 6),
                format_amount(self.amount_interstate),
                format_amount(self.amount_imported),
                format_amount(self.import_content),
            ]
        )
