# Copyright 2022 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo
#
import textwrap
from odoo import fields, models

from .leiaute_nfe_v4_00 import TconsReciNfe

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


class ConsReciNfe(models.AbstractModel):
    """Schema XML de validação do Pedido de Consulta do Recido do Lote de Notas
    Fiscais Eletrônicas"""

    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "nfe.40.consrecinfe"
    _inherit = "spec.mixin.nfe"
    _binding_type = "ConsReciNfe"
