"""This file was generated by xsdata, v24.11, on 2025-12-22 02:37:10

Generator: OdooGenerator
See: https://xsdata.readthedocs.io/
"""
# Copyright 2025 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo

import textwrap

from odoo import fields, models

# Tipo de Ente Governamental
TENTEGOV = [
    ("1", "1"),
    ("2", "2"),
    ("3", "3"),
    ("4", "4"),
]

# Tipo Indicador de Doação
TINDDOACAO = [
    ("1", "1"),
]

# Tipo da Operação com Ente Governamental
TOPERCOMPRAGOV = [
    ("1", "1"),
    ("2", "2"),
]

# Tipo de classificação do Crédito Presumido IBS ZFM
TTPCREDPRESIBSZFM = [
    ("0", "0"),
    ("1", "1"),
    ("2", "2"),
    ("3", "3"),
    ("4", "4"),
]


class TajusteCompet(models.AbstractModel):
    "Tipo Ajuste de Competência"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tajustecompet"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TajusteCompet"

    nfe40_vIBS = fields.Char(
        string="Valor do IBS", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vCBS = fields.Char(
        string="Valor da CBS", xsd_required=True, xsd_type="TDec1302RTC"
    )


class TcredPres(models.AbstractModel):
    "Tipo Crédito Presumido"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tcredpres"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TcredPres"

    nfe40_pCredPres = fields.Float(
        string="Percentual do Crédito Presumido",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
    )

    nfe40_vCredPres = fields.Char(
        string="Valor do Crédito Presumido",
        choice="tcredpres",
        xsd_choice_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_vCredPresCondSus = fields.Char(
        string="Valor",
        choice="tcredpres",
        xsd_choice_required=True,
        xsd_type="TDec1302RTC",
        help=(
            "Valor do Crédito Presumido Condição Suspensiva, preencher apenas "
            "para cCredPres que possui indicação de Condição Suspensiva"
        ),
    )


class TdevTrib(models.AbstractModel):
    "Tipo Devolução Tributo"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tdevtrib"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TdevTrib"

    nfe40_vDevTrib = fields.Char(
        string="Valor do tributo devolvido",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help=(
            "Valor do tributo devolvido. No fornecimento de energia elétrica, "
            "água, esgoto e\ngás natural e em outras hipóteses definidas no "
            "regulamento"
        ),
    )


class Tdif(models.AbstractModel):
    "Tipo Diferimento"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tdif"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tdif"

    nfe40_pDif = fields.Float(
        string="Percentual do diferimento",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
    )

    nfe40_vDif = fields.Char(
        string="Valor do diferimento", xsd_required=True, xsd_type="TDec1302RTC"
    )


class TestornoCred(models.AbstractModel):
    "Tipo Estorno de Crédito"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.testornocred"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TestornoCred"

    nfe40_vIBSEstCred = fields.Char(
        string="Valor do IBS a ser estornado", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vCBSEstCred = fields.Char(
        string="Valor da CBS a ser estornada", xsd_required=True, xsd_type="TDec1302RTC"
    )


class TibscbsmonoTot(models.AbstractModel):
    "Grupo de informações de totais da CBS/IBS com monofasia"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbsmonotot"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TibscbsmonoTot"

    nfe40_vBCIBSCBS = fields.Char(
        string="Total Base de Calculo", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_gIBS = fields.Many2one(
        comodel_name="nfe.40.tibscbsmonotot_gibs", string="Totalização do IBS"
    )

    nfe40_gCBS = fields.Many2one(
        comodel_name="nfe.40.tibscbsmonotot_gcbs", string="Totalização da CBS"
    )

    nfe40_gMono = fields.Many2one(
        comodel_name="nfe.40.gmono",
        string="Totais da Monofasia",
        help=("Totais da Monofasia\nSó deverá ser utilizado para DFe modelos 55 e 65"),
    )

    nfe40_gEstornoCred = fields.Many2one(
        comodel_name="nfe.40.tibscbsmonotot_gestornocred",
        string="Totalização do estorno de crédito",
    )


class TibscbsmonoTotGIbs(models.AbstractModel):
    "Totalização do IBS"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbsmonotot_gibs"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TibscbsmonoTot.GIbs"

    nfe40_gIBSUF = fields.Many2one(
        comodel_name="nfe.40.tibscbsmonotot_gibsuf",
        string="Totalização do IBS de competência da UF",
        xsd_required=True,
    )

    nfe40_gIBSMun = fields.Many2one(
        comodel_name="nfe.40.tibscbsmonotot_gibsmun",
        string="Totalização do IBS",
        xsd_required=True,
        help="Totalização do IBS de competência Municipal",
    )

    nfe40_vIBS = fields.Char(
        string="Valor total do IBS", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vCredPres = fields.Char(
        string="Total do Crédito Presumido", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vCredPresCondSus = fields.Char(
        string="Total",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help="Total do Crédito Presumido Condição Suspensiva",
    )


class TibscbsmonoTotGIbsuf(models.AbstractModel):
    "Totalização do IBS de competência da UF"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbsmonotot_gibsuf"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TibscbsmonoTot.GIbs.GIbsuf"

    nfe40_vDif = fields.Char(
        string="Total do Diferimento", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vDevTrib = fields.Char(
        string="Total de devoluções de tributos",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_vIBSUF = fields.Char(
        string="Valor total do IBS Estadual", xsd_required=True, xsd_type="TDec1302RTC"
    )


class TibscbsmonoTotGIbsmun(models.AbstractModel):
    "Totalização do IBS de competência Municipal"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbsmonotot_gibsmun"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TibscbsmonoTot.GIbs.GIbsmun"

    nfe40_vDif = fields.Char(
        string="Total do Diferimento", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vDevTrib = fields.Char(
        string="Total de devoluções de tributos",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_vIBSMun = fields.Char(
        string="Valor total do IBS Municipal", xsd_required=True, xsd_type="TDec1302RTC"
    )


class TibscbsmonoTotGCbs(models.AbstractModel):
    "Totalização da CBS"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbsmonotot_gcbs"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TibscbsmonoTot.GCbs"

    nfe40_vDif = fields.Char(
        string="Total do Diferimento", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vDevTrib = fields.Char(
        string="Total de devoluções de tributos",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_vCBS = fields.Char(
        string="Valor total da CBS", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vCredPres = fields.Char(
        string="Total do Crédito Presumido", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vCredPresCondSus = fields.Char(
        string="Total",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help="Total do Crédito Presumido Condição Suspensiva",
    )


class GMono(models.AbstractModel):
    """Totais da Monofasia
    Só deverá ser utilizado para DFe modelos 55 e 65"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.gmono"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TibscbsmonoTot.GMono"

    nfe40_vIBSMono = fields.Char(
        string="Valor total do IBS monofásico",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_vCBSMono = fields.Char(
        string="Valor total da CBS monofásica",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_vIBSMonoReten = fields.Char(
        string="Valor total do IBS monofásico sujeito",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help="Valor total do IBS monofásico sujeito a retenção",
    )

    nfe40_vCBSMonoReten = fields.Char(
        string="Valor total da CBS monofásica sujeita",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help="Valor total da CBS monofásica sujeita a retenção",
    )

    nfe40_vIBSMonoRet = fields.Char(
        string="Valor",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help="Valor do IBS monofásico retido anteriormente",
    )

    nfe40_vCBSMonoRet = fields.Char(
        string="Valor (vCBSMonoRet)",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help="Valor da CBS monofásica retida anteriormente",
    )


class TibscbsmonoTotGEstornoCred(models.AbstractModel):
    "Informado conforme indicador no cClassTrib"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbsmonotot_gestornocred"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TibscbsmonoTot.GEstornoCred"

    nfe40_vIBSEstCred = fields.Char(
        string="Valor total do IBS estornado", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vCBSEstCred = fields.Char(
        string="Valor total da CBS estornada", xsd_required=True, xsd_type="TDec1302RTC"
    )


class Tibscbstot(models.AbstractModel):
    "Grupo de informações de totais da CBS/IBS"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbstot"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tibscbstot"

    nfe40_vBCIBSCBS = fields.Char(
        string="Total Base de Calculo", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_gIBS = fields.Many2one(
        comodel_name="nfe.40.tibscbstot_gibs",
        string="Totalização do IBS",
        xsd_required=True,
    )

    nfe40_gCBS = fields.Many2one(
        comodel_name="nfe.40.tibscbstot_gcbs",
        string="Totalização da CBS",
        xsd_required=True,
    )

    nfe40_gEstornoCred = fields.Many2one(
        comodel_name="nfe.40.tibscbstot_gestornocred",
        string="Totalização do estorno de crédito",
    )


class TibscbstotGIbs(models.AbstractModel):
    "Totalização do IBS"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbstot_gibs"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tibscbstot.GIbs"

    nfe40_gIBSUF = fields.Many2one(
        comodel_name="nfe.40.tibscbstot_gibsuf",
        string="Totalização do IBS de competência da UF",
        xsd_required=True,
    )

    nfe40_gIBSMun = fields.Many2one(
        comodel_name="nfe.40.tibscbstot_gibsmun",
        string="Totalização do IBS",
        xsd_required=True,
        help="Totalização do IBS de competência Municipal",
    )

    nfe40_vIBS = fields.Char(
        string="Valor total do IBS", xsd_required=True, xsd_type="TDec1302RTC"
    )


class TibscbstotGIbsuf(models.AbstractModel):
    "Totalização do IBS de competência da UF"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbstot_gibsuf"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tibscbstot.GIbs.GIbsuf"

    nfe40_vDif = fields.Char(
        string="Total do Diferimento", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vDevTrib = fields.Char(
        string="Total de devoluções de tributos",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_vIBSUF = fields.Char(
        string="Valor total do IBS Estadual", xsd_required=True, xsd_type="TDec1302RTC"
    )


class TibscbstotGIbsmun(models.AbstractModel):
    "Totalização do IBS de competência Municipal"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbstot_gibsmun"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tibscbstot.GIbs.GIbsmun"

    nfe40_vDif = fields.Char(
        string="Total do Diferimento", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vDevTrib = fields.Char(
        string="Total de devoluções de tributos",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_vIBSMun = fields.Char(
        string="Valor total do IBS Municipal", xsd_required=True, xsd_type="TDec1302RTC"
    )


class TibscbstotGCbs(models.AbstractModel):
    "Totalização da CBS"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbstot_gcbs"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tibscbstot.GCbs"

    nfe40_vDif = fields.Char(
        string="Total do Diferimento", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vDevTrib = fields.Char(
        string="Total de devoluções de tributos",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_vCBS = fields.Char(
        string="Valor total da CBS", xsd_required=True, xsd_type="TDec1302RTC"
    )


class TibscbstotGEstornoCred(models.AbstractModel):
    "Informado conforme indicador no cClassTrib"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tibscbstot_gestornocred"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tibscbstot.GEstornoCred"

    nfe40_vIBSEstCred = fields.Char(
        string="Valor total do IBS estornado", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vCBSEstCred = fields.Char(
        string="Valor total da CBS estornada", xsd_required=True, xsd_type="TDec1302RTC"
    )


class Tis(models.AbstractModel):
    "Grupo de informações do Imposto Seletivo"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tis"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tis"

    nfe40_CSTIS = fields.Char(
        string="Código Situação Tributária",
        xsd_required=True,
        xsd_type="TCST",
        help="Código Situação Tributária do Imposto Seletivo",
    )

    nfe40_cClassTribIS = fields.Char(
        string="cClassTribIS", xsd_required=True, xsd_type="TcClassTrib"
    )

    nfe40_vBCIS = fields.Char(string="Valor do BC", xsd_type="TDec1302RTC")

    nfe40_pIS = fields.Float(
        string="Alíquota do Imposto Seletivo",
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help="Alíquota do Imposto Seletivo (percentual)",
    )

    nfe40_pISEspec = fields.Float(
        string="Alíquota do Imposto Seletivo (pISEspec)",
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help="Alíquota do Imposto Seletivo (por valor)",
    )

    nfe40_uTrib = fields.Char(
        string="Unidade",
        help=(
            "Unidade de medida apropriada especificada em Lei Ordinaria para "
            "fins de apuração do Imposto Seletivo"
        ),
    )

    nfe40_qTrib = fields.Float(
        string="Quantidade com abse",
        xsd_type="TDec_1104OpRTC",
        digits=(
            11,
            4,
        ),
        help="Quantidade com abse no campo uTrib informado",
    )

    nfe40_vIS = fields.Char(
        string="Valor do Imposto Seletivo calculado", xsd_type="TDec1302RTC"
    )


class Tistot(models.AbstractModel):
    "Grupo de informações de totais do Imposto Seletivo"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tistot"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tistot"

    nfe40_vIS = fields.Char(
        string="Valor Total do Imposto Seletivo",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )


class Tmonofasia(models.AbstractModel):
    "Tipo Monofasia"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tmonofasia"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tmonofasia"

    nfe40_gMonoPadrao = fields.Many2one(
        comodel_name="nfe.40.gmonopadrao",
        string="Grupo de informações",
        help="Grupo de informações da Tributação Monofásica padrão",
    )

    nfe40_gMonoReten = fields.Many2one(
        comodel_name="nfe.40.gmonoreten",
        string="Grupo de informações (gMonoReten)",
        help=("Grupo de informações da Tributação Monofásica sujeita a retenção"),
    )

    nfe40_gMonoRet = fields.Many2one(
        comodel_name="nfe.40.gmonoret",
        string="Grupo de informações (gMonoRet)",
        help=("Grupo de informações da Tributação Monofásica retida anteriormente"),
    )

    nfe40_gMonoDif = fields.Many2one(
        comodel_name="nfe.40.gmonodif",
        string="Grupo de informações do diferimento",
        help="Grupo de informações do diferimento da Tributação Monofásica",
    )

    nfe40_vTotIBSMonoItem = fields.Char(
        string="Total de IBS monofásico do item",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_vTotCBSMonoItem = fields.Char(
        string="Total da CBS monofásica do item",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )


class GMonoPadrao(models.AbstractModel):
    "Grupo de informações da Tributação Monofásica padrão"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.gmonopadrao"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tmonofasia.GMonoPadrao"

    nfe40_qBCMono = fields.Char(
        string="Quantidade tributada na monofasia",
        xsd_required=True,
        xsd_type="TDec1104RTC",
    )

    nfe40_adRemIBS = fields.Monetary(
        string="Alíquota ad rem do IBS",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        currency_field="brl_currency_id",
    )

    nfe40_adRemCBS = fields.Monetary(
        string="Alíquota ad rem da CBS",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        currency_field="brl_currency_id",
    )

    nfe40_vIBSMono = fields.Char(
        string="Valor do IBS monofásico", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_vCBSMono = fields.Char(
        string="Valor da CBS monofásica", xsd_required=True, xsd_type="TDec1302RTC"
    )


class GMonoReten(models.AbstractModel):
    "Grupo de informações da Tributação Monofásica sujeita a retenção"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.gmonoreten"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tmonofasia.GMonoReten"

    nfe40_qBCMonoReten = fields.Char(
        string="Quantidade tributada sujeita a retenção",
        xsd_required=True,
        xsd_type="TDec1104RTC",
    )

    nfe40_adRemIBSReten = fields.Monetary(
        string="Alíquota ad rem do IBS sujeito",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        currency_field="brl_currency_id",
        help="Alíquota ad rem do IBS sujeito a retenção",
    )

    nfe40_vIBSMonoReten = fields.Char(
        string="Valor do IBS monofásico sujeito",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help="Valor do IBS monofásico sujeito a retenção",
    )

    nfe40_adRemCBSReten = fields.Monetary(
        string="Alíquota ad rem da CBS sujeita",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        currency_field="brl_currency_id",
        help="Alíquota ad rem da CBS sujeita a retenção",
    )

    nfe40_vCBSMonoReten = fields.Char(
        string="Valor da CBS monofásica sujeita",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help="Valor da CBS monofásica sujeita a retenção",
    )


class GMonoRet(models.AbstractModel):
    "Grupo de informações da Tributação Monofásica retida anteriormente"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.gmonoret"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tmonofasia.GMonoRet"

    nfe40_qBCMonoRet = fields.Char(
        string="qBCMonoRet",
        xsd_required=True,
        xsd_type="TDec1104RTC",
        help="Quantidade tributada retida anteriormente",
    )

    nfe40_adRemIBSRet = fields.Monetary(
        string="Alíquota ad rem",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        currency_field="brl_currency_id",
        help="Alíquota ad rem do IBS retido anteriormente",
    )

    nfe40_vIBSMonoRet = fields.Char(
        string="Valor do IBS retido anteriormente",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_adRemCBSRet = fields.Monetary(
        string="Alíquota ad rem (adRemCBSRet)",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        currency_field="brl_currency_id",
        help="Alíquota ad rem da CBS retida anteriormente",
    )

    nfe40_vCBSMonoRet = fields.Char(
        string="Valor da CBS retida anteriormente",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )


class GMonoDif(models.AbstractModel):
    "Grupo de informações do diferimento da Tributação Monofásica"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.gmonodif"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tmonofasia.GMonoDif"

    nfe40_pDifIBS = fields.Float(
        string="Percentual do diferimento",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help="Percentual do diferimento do imposto monofásico",
    )

    nfe40_vIBSMonoDif = fields.Char(
        string="Valor do IBS monofásico diferido",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_pDifCBS = fields.Float(
        string="Percentual do diferimento (pDifCBS)",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help="Percentual do diferimento do imposto monofásico",
    )

    nfe40_vCBSMonoDif = fields.Char(
        string="Valor da CBS monofásica diferida",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )


class Tred(models.AbstractModel):
    "Tipo Redução Base de Cálculo"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tred"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tred"

    nfe40_pRedAliq = fields.Float(
        string="Percentual de redução de aliquota",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help="Percentual de redução de aliquota do cClassTrib",
    )

    nfe40_pAliqEfet = fields.Float(
        string="Aliquota Efetiva que será aplicada",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help=("Aliquota Efetiva que será aplicada a Base de Calculo (em percentual)"),
    )


class TtransfCred(models.AbstractModel):
    "Tipo Transferência de Crédito"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.ttransfcred"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TtransfCred"

    nfe40_vIBS = fields.Char(
        string="Valor do IBS a ser transferido",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )

    nfe40_vCBS = fields.Char(
        string="Valor da CBS a ser transferida",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )


class TtribCompraGov(models.AbstractModel):
    "Tipo Tributação Compra Governamental"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.ttribcompragov"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TtribCompraGov"

    nfe40_pAliqIBSUF = fields.Float(
        string="pAliqIBSUF",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
    )

    nfe40_vTribIBSUF = fields.Char(
        string="Valor que seria devido a UF",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help=("Valor que seria devido a UF, sem aplicação do Art. 473. da LC 214/2025"),
    )

    nfe40_pAliqIBSMun = fields.Float(
        string="pAliqIBSMun",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
    )

    nfe40_vTribIBSMun = fields.Char(
        string="Valor que seria devido ao município",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help=(
            "Valor que seria devido ao município, sem aplicação do Art. 473. "
            "da LC 214/2025"
        ),
    )

    nfe40_pAliqCBS = fields.Float(
        string="pAliqCBS",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
    )

    nfe40_vTribCBS = fields.Char(
        string="Valor que seria devido a CBS",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help=(
            "Valor que seria devido a CBS, sem aplicação do Art. 473. da LC 214/2025"
        ),
    )


class TtribRegular(models.AbstractModel):
    "Tipo Tributação Regular"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.ttribregular"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TtribRegular"

    nfe40_CSTReg = fields.Char(
        string="Código da Situação Tributária do IBS",
        xsd_required=True,
        xsd_type="TCST",
        help=(
            "Código da Situação Tributária do IBS e CBS\nInformar qual seria o"
            " CST caso não cumprida a condição resolutória/suspensiva"
        ),
    )

    nfe40_cClassTribReg = fields.Char(
        string="Informar qual seria o cClassTrib caso",
        xsd_required=True,
        xsd_type="TcClassTrib",
        help=(
            "Informar qual seria o cClassTrib caso não cumprida a condição "
            "resolutória/suspensiva"
        ),
    )

    nfe40_pAliqEfetRegIBSUF = fields.Float(
        string="Alíquota do IBS da UF",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help=(
            "Alíquota do IBS da UF\nInformar como seria a Alíquota caso não "
            "cumprida a condição resolutória/suspensiva"
        ),
    )

    nfe40_vTribRegIBSUF = fields.Char(
        string="Valor do IBS da UF",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help=(
            "Valor do IBS da UF\nInformar como seria o valor do Tributo caso "
            "não cumprida a condição resolutória/suspensiva"
        ),
    )

    nfe40_pAliqEfetRegIBSMun = fields.Float(
        string="Alíquota do IBS do Município",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help=(
            "Alíquota do IBS do Município\nInformar como seria a Alíquota caso"
            " não cumprida a condição resolutória/suspensiva"
        ),
    )

    nfe40_vTribRegIBSMun = fields.Char(
        string="Valor do IBS do Município",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help=(
            "Valor do IBS do Município\nInformar como seria o valor do Tributo"
            " caso não cumprida a condição resolutória/suspensiva"
        ),
    )

    nfe40_pAliqEfetRegCBS = fields.Float(
        string="Alíquota da CBS",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help=(
            "Alíquota da CBS\nInformar como seria a Alíquota caso não cumprida"
            " a condição resolutória/suspensiva"
        ),
    )

    nfe40_vTribRegCBS = fields.Char(
        string="Valor da CBS",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help=(
            "Valor da CBS\nInformar como seria o valor do Tributo caso não "
            "cumprida a condição resolutória/suspensiva"
        ),
    )


class Tcibs(models.AbstractModel):
    "Tipo CBS IBS Completo"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tcibs"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tcibs"

    nfe40_vBC = fields.Char(
        string="Valor do BC", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_gIBSUF = fields.Many2one(
        comodel_name="nfe.40.tcibs_gibsuf",
        string="Grupo de informações do IBS na UF",
        xsd_required=True,
    )

    nfe40_gIBSMun = fields.Many2one(
        comodel_name="nfe.40.tcibs_gibsmun",
        string="Grupo de Informações do IBS no Município",
        xsd_required=True,
    )

    nfe40_vIBS = fields.Char(
        string="Valor do IBS", xsd_required=True, xsd_type="TDec1302RTC"
    )

    nfe40_gCBS = fields.Many2one(
        comodel_name="nfe.40.tcibs_gcbs",
        string="Grupo de Tributação da CBS",
        xsd_required=True,
    )

    nfe40_gTribRegular = fields.Many2one(
        comodel_name="nfe.40.ttribregular",
        string="Grupo de informações",
        xsd_type="TTribRegular",
        help=(
            "Grupo de informações da Tributação Regular. Informar como seria a"
            " tributação caso não cumprida a condição resolutória/suspensiva. "
            "Exemplo 1: Art. 442, §4. Operações com ZFM e ALC. Exemplo 2: "
            "Operações com suspensão do tributo."
        ),
    )

    nfe40_gTribCompraGov = fields.Many2one(
        comodel_name="nfe.40.ttribcompragov",
        string="Grupo de informações da composição",
        xsd_type="TTribCompraGov",
        help=(
            "Grupo de informações da composição do valor do IBS e da CBS em "
            "compras governamental"
        ),
    )


class TcibsGCbs(models.AbstractModel):
    "Totalização da CBS"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tcibs_gcbs"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tcibs.GCbs"

    nfe40_pCBS = fields.Float(
        string="Aliquota da CBS (em percentual)",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
    )

    nfe40_gDif = fields.Many2one(
        comodel_name="nfe.40.tdif",
        string="Grupo de campos do Diferimento",
        xsd_type="TDif",
    )

    nfe40_gDevTrib = fields.Many2one(
        comodel_name="nfe.40.tdevtrib",
        string="Grupo de Informações da devolução",
        xsd_type="TDevTrib",
        help="Grupo de Informações da devolução de tributos",
    )

    nfe40_gRed = fields.Many2one(
        comodel_name="nfe.40.tred",
        string="Grupo de campos da redução de aliquota",
        xsd_type="TRed",
    )

    nfe40_vCBS = fields.Char(
        string="Valor da CBS", xsd_required=True, xsd_type="TDec1302RTC"
    )


class TcibsGIbsuf(models.AbstractModel):
    "Totalização do IBS de competência da UF"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tcibs_gibsuf"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tcibs.GIbsuf"

    nfe40_pIBSUF = fields.Float(
        string="Aliquota do IBS de competência das UF",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help="Aliquota do IBS de competência das UF (em percentual)",
    )

    nfe40_gDif = fields.Many2one(
        comodel_name="nfe.40.tdif",
        string="Grupo de campos do Diferimento",
        xsd_type="TDif",
    )

    nfe40_gDevTrib = fields.Many2one(
        comodel_name="nfe.40.tdevtrib",
        string="Grupo de Informações da devolução",
        xsd_type="TDevTrib",
        help="Grupo de Informações da devolução de tributos",
    )

    nfe40_gRed = fields.Many2one(
        comodel_name="nfe.40.tred",
        string="Grupo de campos da redução de aliquota",
        xsd_type="TRed",
    )

    nfe40_vIBSUF = fields.Char(
        string="Valor do IBS de competência das UF",
        xsd_required=True,
        xsd_type="TDec1302RTC",
    )


class TcibsGIbsmun(models.AbstractModel):
    "Totalização do IBS de competência Municipal"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tcibs_gibsmun"
    _inherit = "spec.mixin.nfe"
    _binding_type = "Tcibs.GIbsmun"

    nfe40_pIBSMun = fields.Float(
        string="Aliquota do IBS Municipal",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help="Aliquota do IBS Municipal (em percentual)",
    )

    nfe40_gDif = fields.Many2one(
        comodel_name="nfe.40.tdif",
        string="Grupo de campos do Diferimento",
        xsd_type="TDif",
    )

    nfe40_gDevTrib = fields.Many2one(
        comodel_name="nfe.40.tdevtrib",
        string="Grupo de Informações da devolução",
        xsd_type="TDevTrib",
        help="Grupo de Informações da devolução de tributos",
    )

    nfe40_gRed = fields.Many2one(
        comodel_name="nfe.40.tred",
        string="Grupo de campos da redução de aliquota",
        xsd_type="TRed",
    )

    nfe40_vIBSMun = fields.Char(
        string="Valor do IBS Municipal", xsd_required=True, xsd_type="TDec1302RTC"
    )


class TcompraGov(models.AbstractModel):
    """Tipo Compras Governamentais
    Cada DFe que utilizar deverá utilizar esses tipo no grupo ide"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tcompragov"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TcompraGov"

    nfe40_tpEnteGov = fields.Selection(
        TENTEGOV,
        string="Para administração pública direta",
        xsd_required=True,
        xsd_type="TEnteGov",
        help=(
            "Para administração pública direta e suas autarquias e "
            "fundações:\n1=União\n2=Estados\n3=Distrito Federal\n4=Municípios"
        ),
    )

    nfe40_pRedutor = fields.Float(
        string="Percentual de redução de aliquota",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help="Percentual de redução de aliquota em compra governamental",
    )

    nfe40_tpOperGov = fields.Selection(
        TOPERCOMPRAGOV,
        string="Tipo da operação com ente governamental",
        xsd_required=True,
        xsd_type="TOperCompraGov",
        help=(
            "Tipo da operação com ente governamental:\n1 - Fornecimento\n2 - "
            "Recebimento do Pagamento"
        ),
    )


class TcompraGovReduzido(models.AbstractModel):
    """Tipo Compras Governamentais
    Cada DFe que utilizar deverá utilizar esses tipo no grupo ide"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tcompragovreduzido"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TcompraGovReduzido"

    nfe40_tpEnteGov = fields.Selection(
        TENTEGOV,
        string="Para administração pública direta",
        xsd_required=True,
        xsd_type="TEnteGov",
        help=(
            "Para administração pública direta e suas autarquias e "
            "fundações:\n1=União\n2=Estados\n3=Distrito Federal\n4=Municípios"
        ),
    )

    nfe40_pRedutor = fields.Float(
        string="Percentual de redução de aliquota",
        xsd_required=True,
        xsd_type="TDec_0302_04RTC",
        digits=(
            3,
            2,
        ),
        help="Percentual de redução de aliquota em compra governamental",
    )


class TcredPresIbszfm(models.AbstractModel):
    """Tipo Informações do crédito presumido de IBS para fornecimentos a partir
    da ZFM"""

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tcredpresibszfm"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TcredPresIbszfm"

    nfe40_tpCredPresIBSZFM = fields.Selection(
        TTPCREDPRESIBSZFM,
        string="Classificação de acordo com o art",
        xsd_required=True,
        xsd_type="TTpCredPresIBSZFM",
        help=(
            "Classificação de acordo com o art. 450, § 1º, da LC 214/25 para o"
            " cálculo do crédito presumido na ZFM\n0 - Sem crédito "
            "presumido;\n1 - Bens de consumo final (55%);\n2 - Bens de capital"
            " (75%);\n3 - Bens intermediários (90,25%);\n4 - Bens de "
            "informática e outros definidos em legislação (100%).\nOBS: "
            "Percentuais definidos no art. 450, § 1º, da LC 214/25 para o "
            "cálculo do crédito presumido"
        ),
    )

    nfe40_vCredPresIBSZFM = fields.Char(
        string="Valor",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help=("Valor do crédito presumido calculado sobre o saldo devedor apurado"),
    )


class TcredPresOper(models.AbstractModel):
    "Tipo Crédito Presumido da Operação"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.tcredpresoper"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TcredPresOper"

    nfe40_vBCCredPres = fields.Char(
        string="Valor da Base de Cálculo",
        xsd_required=True,
        xsd_type="TDec1302RTC",
        help="Valor da Base de Cálculo do Crédito Presumido da Operação",
    )

    nfe40_cCredPres = fields.Char(
        string="Código de Classificação",
        xsd_required=True,
        xsd_type="TcCredPres",
        help="Código de Classificação do Crédito Presumido do IBS e da CBS",
    )

    nfe40_gIBSCredPres = fields.Many2one(
        comodel_name="nfe.40.tcredpres",
        string="Grupo de Informações",
        xsd_type="TCredPres",
        help=(
            "Grupo de Informações do Crédito Presumido referente ao IBS, "
            "quando aproveitado pelo emitente do documento."
        ),
    )

    nfe40_gCBSCredPres = fields.Many2one(
        comodel_name="nfe.40.tcredpres",
        string="Grupo de Informações (gCBSCredPres)",
        xsd_type="TCredPres",
        help=(
            "Grupo de Informações do Crédito Presumido referente a CBS, quando"
            " aproveitado pelo emitente do documento."
        ),
    )


class TtribBpe(models.AbstractModel):
    "Grupo de informações da Tributação do BPe"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.ttribbpe"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TtribBpe"

    nfe40_CST = fields.Char(
        string="Código Situação Tributária do IBS/CBS",
        xsd_required=True,
        xsd_type="TCST",
    )

    nfe40_cClassTrib = fields.Char(
        string="cClassTrib", xsd_required=True, xsd_type="TcClassTrib"
    )

    nfe40_indDoacao = fields.Selection(
        TINDDOACAO, string="indDoacao", xsd_type="TIndDoacao"
    )

    nfe40_gIBSCBS = fields.Many2one(
        comodel_name="nfe.40.tcibs", string="gIBSCBS", xsd_type="TCIBS"
    )

    nfe40_gEstornoCred = fields.Many2one(
        comodel_name="nfe.40.testornocred",
        string="Informado conforme indicador",
        xsd_type="TEstornoCred",
        help="Informado conforme indicador no cClassTrib",
    )


class TtribCte(models.AbstractModel):
    "Grupo de informações da Tributação do CTe"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.ttribcte"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TtribCte"

    nfe40_CST = fields.Char(
        string="Código Situação Tributária do IBS/CBS",
        xsd_required=True,
        xsd_type="TCST",
    )

    nfe40_cClassTrib = fields.Char(
        string="cClassTrib", xsd_required=True, xsd_type="TcClassTrib"
    )

    nfe40_indDoacao = fields.Selection(
        TINDDOACAO, string="indDoacao", xsd_type="TIndDoacao"
    )

    nfe40_gIBSCBS = fields.Many2one(
        comodel_name="nfe.40.tcibs", string="gIBSCBS", xsd_type="TCIBS"
    )

    nfe40_gEstornoCred = fields.Many2one(
        comodel_name="nfe.40.testornocred",
        string="Informado conforme indicador",
        xsd_type="TEstornoCred",
        help="Informado conforme indicador no cClassTrib",
    )


class TtribNf3E(models.AbstractModel):
    "Grupo de informações da Tributação da NF3e"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.ttribnf3e"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TtribNf3E"

    nfe40_CST = fields.Char(
        string="Código Situação Tributária do IBS/CBS",
        xsd_required=True,
        xsd_type="TCST",
    )

    nfe40_cClassTrib = fields.Char(
        string="cClassTrib", xsd_required=True, xsd_type="TcClassTrib"
    )

    nfe40_indDoacao = fields.Selection(
        TINDDOACAO, string="Indica se a operação é de doação", xsd_type="TIndDoacao"
    )

    nfe40_gIBSCBS = fields.Many2one(
        comodel_name="nfe.40.tcibs", string="gIBSCBS", xsd_type="TCIBS"
    )

    nfe40_gEstornoCred = fields.Many2one(
        comodel_name="nfe.40.testornocred",
        string="Informado conforme indicador",
        xsd_type="TEstornoCred",
        help="Informado conforme indicador no cClassTrib",
    )


class TtribNfag(models.AbstractModel):
    "Grupo de informações da Tributação da NFAg"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.ttribnfag"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TtribNfag"

    nfe40_CST = fields.Char(
        string="Código Situação Tributária do IBS/CBS",
        xsd_required=True,
        xsd_type="TCST",
    )

    nfe40_cClassTrib = fields.Char(
        string="cClassTrib", xsd_required=True, xsd_type="TcClassTrib"
    )

    nfe40_indDoacao = fields.Selection(
        TINDDOACAO, string="indDoacao", xsd_type="TIndDoacao"
    )

    nfe40_gIBSCBS = fields.Many2one(
        comodel_name="nfe.40.tcibs", string="gIBSCBS", xsd_type="TCIBS"
    )

    nfe40_gEstornoCred = fields.Many2one(
        comodel_name="nfe.40.testornocred",
        string="Informado conforme indicador",
        xsd_type="TEstornoCred",
        help="Informado conforme indicador no cClassTrib",
    )


class TtribNfce(models.AbstractModel):
    "Grupo de informações da Tributação da NFCe"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.ttribnfce"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TtribNfce"

    nfe40_CST = fields.Char(
        string="Código Situação Tributária do IBS/CBS",
        xsd_required=True,
        xsd_type="TCST",
    )

    nfe40_cClassTrib = fields.Char(
        string="cClassTrib", xsd_required=True, xsd_type="TcClassTrib"
    )

    nfe40_indDoacao = fields.Selection(
        TINDDOACAO, string="Indica se a operação é de doação", xsd_type="TIndDoacao"
    )

    nfe40_gIBSCBS = fields.Many2one(
        comodel_name="nfe.40.tcibs",
        string="gIBSCBS",
        choice="ttribnfce",
        xsd_type="TCIBS",
    )

    nfe40_gIBSCBSMono = fields.Many2one(
        comodel_name="nfe.40.tmonofasia",
        string="gIBSCBSMono",
        choice="ttribnfce",
        xsd_type="TMonofasia",
    )


class TtribNfcom(models.AbstractModel):
    "Grupo de informações da Tributação da NFCom"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.ttribnfcom"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TtribNfcom"

    nfe40_CST = fields.Char(
        string="Código Situação Tributária do IBS/CBS",
        xsd_required=True,
        xsd_type="TCST",
    )

    nfe40_cClassTrib = fields.Char(
        string="cClassTrib", xsd_required=True, xsd_type="TcClassTrib"
    )

    nfe40_indDoacao = fields.Selection(
        TINDDOACAO, string="Indica se a operação é de doação", xsd_type="TIndDoacao"
    )

    nfe40_gIBSCBS = fields.Many2one(
        comodel_name="nfe.40.tcibs", string="gIBSCBS", xsd_type="TCIBS"
    )

    nfe40_gEstornoCred = fields.Many2one(
        comodel_name="nfe.40.testornocred",
        string="Informado conforme indicador",
        xsd_type="TEstornoCred",
        help="Informado conforme indicador no cClassTrib",
    )


class TtribNfgas(models.AbstractModel):
    "Grupo de informações da Tributação da NFGas"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.ttribnfgas"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TtribNfgas"

    nfe40_CST = fields.Char(
        string="Código Situação Tributária do IBS/CBS",
        xsd_required=True,
        xsd_type="TCST",
    )

    nfe40_cClassTrib = fields.Char(
        string="cClassTrib", xsd_required=True, xsd_type="TcClassTrib"
    )

    nfe40_indDoacao = fields.Selection(
        TINDDOACAO, string="indDoacao", xsd_type="TIndDoacao"
    )

    nfe40_gIBSCBS = fields.Many2one(
        comodel_name="nfe.40.tcibs",
        string="gIBSCBS",
        choice="ttribnfgas",
        xsd_type="TCIBS",
    )

    nfe40_gIBSCBSMono = fields.Many2one(
        comodel_name="nfe.40.tmonofasia",
        string="Informar essa opção da Choice",
        choice="ttribnfgas",
        xsd_type="TMonofasia",
        help="Informar essa opção da Choice para Monofasia",
    )

    nfe40_gEstornoCred = fields.Many2one(
        comodel_name="nfe.40.testornocred",
        string="Informado conforme indicador",
        xsd_type="TEstornoCred",
        help="Informado conforme indicador no cClassTrib",
    )


class TtribNfe(models.AbstractModel):
    "Grupo de informações da Tributação da NFe"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "nfe.40.ttribnfe"
    _inherit = "spec.mixin.nfe"
    _binding_type = "TtribNfe"

    nfe40_CST = fields.Char(
        string="Código Situação Tributária do IBS/CBS",
        xsd_required=True,
        xsd_type="TCST",
    )

    nfe40_cClassTrib = fields.Char(
        string="cClassTrib", xsd_required=True, xsd_type="TcClassTrib"
    )

    nfe40_indDoacao = fields.Selection(
        TINDDOACAO, string="Indica se a operação é de doação", xsd_type="TIndDoacao"
    )

    nfe40_gIBSCBS = fields.Many2one(
        comodel_name="nfe.40.tcibs",
        string="gIBSCBS",
        choice="ttribnfe",
        xsd_type="TCIBS",
    )

    nfe40_gIBSCBSMono = fields.Many2one(
        comodel_name="nfe.40.tmonofasia",
        string="Informar essa opção da Choice",
        choice="ttribnfe",
        xsd_type="TMonofasia",
        help="Informar essa opção da Choice para Monofasia (CST 620)",
    )

    nfe40_gTransfCred = fields.Many2one(
        comodel_name="nfe.40.ttransfcred",
        string="gTransfCred",
        choice="ttribnfe",
        xsd_type="TTransfCred",
        help="Informar essa opção da Choice para o CST 800",
    )

    nfe40_gAjusteCompet = fields.Many2one(
        comodel_name="nfe.40.tajustecompet",
        string="gAjusteCompet",
        choice="ttribnfe",
        xsd_type="TAjusteCompet",
        help="Informar essa opção da Choice para o CST 811",
    )

    nfe40_gEstornoCred = fields.Many2one(
        comodel_name="nfe.40.testornocred",
        string="Informado conforme indicador",
        xsd_type="TEstornoCred",
        help="Informado conforme indicador no cClassTrib",
    )

    nfe40_gCredPresOper = fields.Many2one(
        comodel_name="nfe.40.tcredpresoper",
        string="Crédito Presumido da Operação",
        choice="ttribnfe",
        xsd_type="TCredPresOper",
        help=(
            "Crédito Presumido da Operação. Informado conforme indicador no cClassTrib."
        ),
    )

    nfe40_gCredPresIBSZFM = fields.Many2one(
        comodel_name="nfe.40.tcredpresibszfm",
        string="Classificação de acordo com o art",
        choice="ttribnfe",
        xsd_type="TCredPresIBSZFM",
        help=(
            "Classificação de acordo com o art. 450, § 1º, da LC 214/25 para o"
            " cálculo do crédito presumido na ZFM. Informado conforme "
            "indicador no cClassTrib."
        ),
    )
