# Copyright 2022 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo
#
import textwrap
from odoo import fields, models

from .leiaute_inut_nfe_v4_00 import TprocInutNfe

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


class ProcInutNfe(models.AbstractModel):
    "Pedido de inutilização de númeração de NF-e processado"
    _description = textwrap.dedent("    %s" % (__doc__,))
    _name = "nfe.40.procinutnfe"
    _inherit = "spec.mixin.nfe"
    _binding_type = "ProcInutNfe"
