# Copyright 2022 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo
#
import textwrap
from odoo import fields, models

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"

"Tipo Ambiente"
TAMB = [
    ("1", "None"),
    ("2", "None"),
]

"Tipo Código de orgão (UF da tabela do IBGE + 90 RFB)"
TCORGAOIBGE = [
    ("11", "None"),
    ("12", "None"),
    ("13", "None"),
    ("14", "None"),
    ("15", "None"),
    ("16", "None"),
    ("17", "None"),
    ("21", "None"),
    ("22", "None"),
    ("23", "None"),
    ("24", "None"),
    ("25", "None"),
    ("26", "None"),
    ("27", "None"),
    ("28", "None"),
    ("29", "None"),
    ("31", "None"),
    ("32", "None"),
    ("33", "None"),
    ("35", "None"),
    ("41", "None"),
    ("42", "None"),
    ("43", "None"),
    ("50", "None"),
    ("51", "None"),
    ("52", "None"),
    ("53", "None"),
    ("90", "None"),
    ("91", "None"),
    ("92", "None"),
]

"Tipo Código da UF da tabela do IBGE"
TCODUFIBGE = [
    ("11", "None"),
    ("12", "None"),
    ("13", "None"),
    ("14", "None"),
    ("15", "None"),
    ("16", "None"),
    ("17", "None"),
    ("21", "None"),
    ("22", "None"),
    ("23", "None"),
    ("24", "None"),
    ("25", "None"),
    ("26", "None"),
    ("27", "None"),
    ("28", "None"),
    ("29", "None"),
    ("31", "None"),
    ("32", "None"),
    ("33", "None"),
    ("35", "None"),
    ("41", "None"),
    ("42", "None"),
    ("43", "None"),
    ("50", "None"),
    ("51", "None"),
    ("52", "None"),
    ("53", "None"),
]

"Tipo Modelo Documento Fiscal"
TMOD = [
    ("55", "None"),
    ("65", "None"),
]

"Tipo Sigla da UF"
TUF = [
    ("AC", "None"),
    ("AL", "None"),
    ("AM", "None"),
    ("AP", "None"),
    ("BA", "None"),
    ("CE", "None"),
    ("DF", "None"),
    ("ES", "None"),
    ("GO", "None"),
    ("MA", "None"),
    ("MG", "None"),
    ("MS", "None"),
    ("MT", "None"),
    ("PA", "None"),
    ("PB", "None"),
    ("PE", "None"),
    ("PI", "None"),
    ("PR", "None"),
    ("RJ", "None"),
    ("RN", "None"),
    ("RO", "None"),
    ("RR", "None"),
    ("RS", "None"),
    ("SC", "None"),
    ("SE", "None"),
    ("SP", "None"),
    ("TO", "None"),
    ("EX", "None"),
]

"Tipo Sigla da UF de emissor // acrescentado em 24/10/08"
TUFEMI = [
    ("AC", "None"),
    ("AL", "None"),
    ("AM", "None"),
    ("AP", "None"),
    ("BA", "None"),
    ("CE", "None"),
    ("DF", "None"),
    ("ES", "None"),
    ("GO", "None"),
    ("MA", "None"),
    ("MG", "None"),
    ("MS", "None"),
    ("MT", "None"),
    ("PA", "None"),
    ("PB", "None"),
    ("PE", "None"),
    ("PI", "None"),
    ("PR", "None"),
    ("RJ", "None"),
    ("RN", "None"),
    ("RO", "None"),
    ("RR", "None"),
    ("RS", "None"),
    ("SC", "None"),
    ("SE", "None"),
    ("SP", "None"),
    ("TO", "None"),
]
