[project]
name = "odoo-addons-oca-l10n-brazil"
version = "19.0.20260507.5"
dependencies = [
    "odoo-addon-l10n_br_base==19.0.*",
    "odoo-addon-l10n_br_coa==19.0.*",
    "odoo-addon-l10n_br_currency_rate_update==19.0.*",
    "odoo-addon-l10n_br_hr==19.0.*",
    "odoo-addon-l10n_br_resource==19.0.*",
    "odoo-addon-l10n_br_zip==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
