[project]
name = "odoo-addons-oca-l10n-brazil"
version = "19.0.20260903.0"
dependencies = [
    "odoo-addon-l10n_br_account_due_list==19.0.*",
    "odoo-addon-l10n_br_base==19.0.*",
    "odoo-addon-l10n_br_cnpj_search==19.0.*",
    "odoo-addon-l10n_br_coa==19.0.*",
    "odoo-addon-l10n_br_coa_generic==19.0.*",
    "odoo-addon-l10n_br_coa_simple==19.0.*",
    "odoo-addon-l10n_br_crm==19.0.*",
    "odoo-addon-l10n_br_crm_cnpj_search==19.0.*",
    "odoo-addon-l10n_br_currency_rate_update==19.0.*",
    "odoo-addon-l10n_br_fiscal==19.0.*",
    "odoo-addon-l10n_br_hr==19.0.*",
    "odoo-addon-l10n_br_mis_report==19.0.*",
    "odoo-addon-l10n_br_resource==19.0.*",
    "odoo-addon-l10n_br_setup_tests==19.0.*",
    "odoo-addon-l10n_br_zip==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
